### '서민금융한눈에' api 연결

In [16]:
import requests
import pandas as pd
import certifi

service_key = "OOMzi/L4lsQBtwINCMNBqO7LJpepiMcGg5Hnx0rJ5keZ7Zfb/8bYyDgzjsGgPmlvK2afF0Qf+OnsOARuV0IPcQ=="

url = "http://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo"

params = {
    "serviceKey": service_key,
    "pageNo": 1,
    "numOfRows": 300,
    "resultType": "json",
    "likeTrgt": "사업자"
}

response = requests.get(url, params=params, verify=certifi.where())

if response.status_code == 200:
    data = response.json()
    items = data.get("response", {}).get("body", {}).get("items", {}).get("item", [])
    df = pd.DataFrame(items)
    print(df.shape)
else:
    print("❌ API 호출 오류:", response.status_code, response.text)

(300, 47)

In [140]:
import requests
import pandas as pd
import certifi
import time

service_key = "OOMzi/L4lsQBtwINCMNBqO7LJpepiMcGg5Hnx0rJ5keZ7Zfb/8bYyDgzjsGgPmlvK2afF0Qf+OnsOARuV0IPcQ=="
url = "http://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo"

params = {
    "serviceKey": service_key,
    "pageNo": 1,
    "numOfRows": 100,  # 한 페이지 최대값으로 설정
    "resultType": "json",
    "likeTrgt": "사업자"
}

all_items = []

# 1. 첫 페이지 요청
response = requests.get(url, params=params, verify=certifi.where())
if response.status_code != 200:
    raise Exception(f"❌ API 호출 오류: {response.status_code}, {response.text}")

data = response.json()
body = data.get("response", {}).get("body", {})
total_count = body.get("totalCount", 0)
num_of_rows = body.get("numOfRows", 100)

# 2. 전체 페이지 수 계산
total_pages = (total_count // num_of_rows) + (1 if total_count % num_of_rows > 0 else 0)
print(f"전체 건수: {total_count}, 전체 페이지 수: {total_pages}")

# 3. 페이지 반복
for page in range(1, total_pages + 1):
    params["pageNo"] = page
    response = requests.get(url, params=params, verify=certifi.where())
    if response.status_code != 200:
        print(f"❌ {page} 페이지 호출 실패:", response.status_code)
        continue
    data = response.json()
    items = data.get("response", {}).get("body", {}).get("items", {}).get("item", [])
    all_items.extend(items)
    time.sleep(0.2)  # API 과부하 방지

# 4. DataFrame으로 변환
df = pd.DataFrame(all_items)
print("📦 최종 데이터 크기:", df.shape)

전체 건수: 1734, 전체 페이지 수: 18
📦 최종 데이터 크기: (1734, 47)

In [24]:
import requests
import pandas as pd
import certifi
import time

service_key = "OOMzi/L4lsQBtwINCMNBqO7LJpepiMcGg5Hnx0rJ5keZ7Zfb/8bYyDgzjsGgPmlvK2afF0Qf+OnsOARuV0IPcQ=="
url = "http://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo"

params = {
    "serviceKey": service_key,
    "pageNo": 1,
    "numOfRows": 100,  # 한 페이지 최대값으로 설정
    "resultType": "json",
    "likeTrgt": "소상공인"
}

all_items = []

# 1. 첫 페이지 요청
response = requests.get(url, params=params, verify=certifi.where())
if response.status_code != 200:
    raise Exception(f"❌ API 호출 오류: {response.status_code}, {response.text}")

data = response.json()
body = data.get("response", {}).get("body", {})
total_count = body.get("totalCount", 0)
num_of_rows = body.get("numOfRows", 100)

# 2. 전체 페이지 수 계산
total_pages = (total_count // num_of_rows) + (1 if total_count % num_of_rows > 0 else 0)
print(f"전체 건수: {total_count}, 전체 페이지 수: {total_pages}")

# 3. 페이지 반복
for page in range(1, total_pages + 1):
    params["pageNo"] = page
    response = requests.get(url, params=params, verify=certifi.where())
    if response.status_code != 200:
        print(f"❌ {page} 페이지 호출 실패:", response.status_code)
        continue
    data = response.json()
    items = data.get("response", {}).get("body", {}).get("items", {}).get("item", [])
    all_items.extend(items)
    time.sleep(0.2)  # API 과부하 방지

# 4. DataFrame으로 변환
df2 = pd.DataFrame(all_items)
print("📦 최종 데이터 크기:", df2.shape)

전체 건수: 2197, 전체 페이지 수: 22
📦 최종 데이터 크기: (2197, 47)

In [102]:
final = pd.concat([df, df2], ignore_index=True).sort_values('basYm', ascending=False)
subset = final[final['finPrdNm'] == '보은군 소상공인지원자금']

# 각 열별 고유값 개수 확인
col_uniques = subset.nunique()

# 모든 열의 고유값이 1개면 모든 값이 같음
all_equal = (col_uniques <= 1).all()

print("모든 열 값이 동일한가요? 👉", all_equal)

# 열 중에서 값이 여러 개인 열만 출력
print(col_uniques[col_uniques > 1])

모든 열 값이 동일한가요? 👉 False
basYm           7
snq             2
irt             2
instCtg         2
lnIcdcst        2
hdlInstDtlVw    2
fileWrtDt       7
dtype: int64

In [96]:
subset

,basYm,snq,finPrdNm,lnLmt,irtCtg,irt,maxTotLnTrm,maxDfrmTrm,maxRdptTrm,rdptMthd,...,prdExisYn,cv19Rfrc,prdCtg,prdNm,cv19SuprCtg,cv19SuprCtn,cv19SuprTgtDtlCtn,mgmDln,prdCtg2,fileWrtDt
1810,202506,227,보은군 소상공인지원자금,5000만원,변동금리,은행금리 - 2,3년,-,-,일시상환,...,Y,-,1,대출상품,-,-,-,None,-,202507010700
1961,202505,227,보은군 소상공인지원자금,5000만원,변동금리,은행금리 - 2,3년,-,-,일시상환,...,Y,-,1,대출상품,-,-,-,None,-,202506010700
2112,202504,227,보은군 소상공인지원자금,5000만원,변동금리,은행금리 - 2,3년,-,-,일시상환,...,Y,-,1,대출상품,-,-,-,None,-,202505010700
2263,202503,227,보은군 소상공인지원자금,5000만원,변동금리,은행금리 - 2,3년,-,-,일시상환,...,Y,-,1,대출상품,-,-,-,None,-,202504010700
2414,202502,227,보은군 소상공인지원자금,5000만원,변동금리,은행금리 - 2,3년,-,-,일시상환,...,Y,-,1,대출상품,-,-,-,None,-,202503010700
2566,202501,227,보은군 소상공인지원자금,5000만원,변동금리,은행금리 - 2,3년,-,-,일시상환,...,Y,-,1,대출상품,-,-,-,None,-,202502071556
3921,202110,404,보은군 소상공인지원자금,5000만원,변동금리,은행금리 - 2%,3년,-,-,일시상환,...,Y,None,1,대출상품,None,None,None,None,None,202502010700

basYm : 기준년월
fileWrtDt : 파일작성일시 \
=> 파일이 계속 업뎃되는 과정에서 누적것 같음. \
=> 그래서 basYm 기준으로 내림차순한 뒤, 중복값 제거 ==> final

In [103]:
final = final.drop_duplicates(subset=['finPrdNm', 'ofrInstNm'],keep = 'first')

In [104]:
final[['finPrdNm', 'ofrInstNm']].value_counts()

finPrdNm                ofrInstNm
(2023) 포항시 소상공인 특례보증    경북신용보증재단     1
옥천군 중·저신용 소상공인 특례보증     충북신용보증재단     1
울산광역시 소상공인 경영안정자금       울산신용보증재단     1
울산광역시 북구 소상공인 경영안정자금    울산신용보증재단     1
울산광역시 동구 소상공인 경영안정자금    울산신용보증재단     1
                                    ..
대환대출 지원 특별보증            서울신용보증재단     1
대전광역시 중소기업 경영안정자금 우대보증  대전신용보증재단     1
대전광역시 소상공인경영개선자금 우대보증   대전신용보증재단     1
대전광역시 소상공인 경영개선자금       대전신용보증재단     1
희망플러스 특례보증              신용보증재단중앙회    1
Name: count, Length: 539, dtype: int64

In [108]:
final['basYm'].value_counts().sort_index(ascending=False)

basYm
202506    192
202501      1
202202    275
202201      5
202110     66
Name: count, dtype: int64

In [109]:
# 2022년도 이하 제거(상품이 업뎃 안되었거나 오래된 상품 같아서 삭제)
final = final[final['basYm'].str[:4].astype(int) > 2022]
final['basYm'].value_counts()

basYm
202506    192
202501      1
Name: count, dtype: int64

In [111]:
# 총 상품수 = 193
len(final)

193

In [113]:
final.head()

,basYm,snq,finPrdNm,lnLmt,irtCtg,irt,maxTotLnTrm,maxDfrmTrm,maxRdptTrm,rdptMthd,...,prdExisYn,cv19Rfrc,prdCtg,prdNm,cv19SuprCtg,cv19SuprCtn,cv19SuprTgtDtlCtn,mgmDln,prdCtg2,fileWrtDt
0,202506,4,경상남도 청년 전세자금(경상남도 협약 상품)(경상남도 청년주택 임차보증금 이자지원사업),9000만원,변동금리,은행별 상이,임대차계약기간 이내 최대 2년,0년,0년,일시상환,...,Y,-,1,대출상품,-,-,-,상시,-,202507010700
1838,202506,282,서울시 중소기업 육성자금 지원(특별자금_희망동행자금),10000만원,변동금리,-,5년,1년,4년,균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202507010700
1831,202506,275,"운송업(화물,택시) 및 건설장비 운영업 저금리 상생 특별보증",20000만원,특정금리,은행별 상이,5년,1년,4년,"만기일시상환, 원금균등분할상환",...,Y,-,1,대출상품,-,-,-,한도 소진 시까지,-,202507010700
1832,202506,276,2024년 북구 소상공인 경영안정자금 지원 특례보증(Ⅱ),3000만원,은행금리,은행별 상이,5년,1년,4년,일시상환/분할상환,...,Y,-,1,대출상품,-,-,-,한도 소진 시까지,-,202507010700
1833,202506,277,서울시 중소기업 육성자금 지원(경영안정자금_혁신형도약자금),30000만원,고정금리,3.5%,"2, 5년",1년,4년,"균등분할상환, 일시상환",...,Y,-,1,대출상품,-,-,-,상시,-,202507010700

In [122]:
final['hdlInst']

0                     농협은행, BNK경남은행
1838                       서울신용보증재단
1831                       대구신용보증재단
1832                   아이엠뱅크, 새마을금고
1833                       서울신용보증재단
                   ...
17                       미소금융 전국 지점
23                       미소금융 전국 지점
24                       미소금융 전국 지점
25      한국법무보호복지공단, 나눔과기쁨, 더불어사는사람들
2498           NH농협은행 경남본부, BNK경남은행
Name: hdlInst, Length: 193, dtype: object

In [128]:
final['prdCtg2'].value_counts()

prdCtg2
-    193
Name: count, dtype: int64

변수명 영어->한글 & 필요한 변수만 불러오기

In [131]:
# 열 이름 변경
final = final.rename(columns={
    'basYm': '기준년월',
    'finPrdNm': '금융상품명',
    'lnLmt': '대출한도',
    'irtCtg': '금리구분',
    'irt': '금리',
    'rdptMthd': '상환방법',
    'usge': '용도',
    'trgt': '대상',
    'ofrInstNm': '제공기관명',
    'rsdAreaPamtEqltIstm': '거주지역원금균등분할상환',
    'suprTgtDtlCond': '지원대상 상세조건',
    'crdtSc': '신용등급',
    'rfrcCnpl': '문의처 및 연락처',
    'jnMthd': '가입(신청)방법',
    'ovItrYr': '연체이자율(연)',
    'prftAddIrtCond': '우대금리/가산금리 조건',
    'cnpl': '연락처',
    'rltSite': '관련 사이트',
    'tgtFltr': '대상_필터',
    'hdlInstDtlVw': '취급기관_상세보기용',
    'prdExisYn': '상품존재여부',
    'prdNm': '상품명',
    'mgmDln': '운영기한'
})

# 바꾼 열만 선택
columns_to_keep = [
    '기준년월', '금융상품명', '대출한도', '금리구분', '금리', '상환방법', '용도', '대상',
    '제공기관명', '거주지역원금균등분할상환', '지원대상 상세조건', '신용등급', '문의처 및 연락처',
    '가입(신청)방법', '연체이자율(연)', '우대금리/가산금리 조건', '연락처', '관련 사이트',
    '대상_필터', '취급기관_상세보기용', '상품존재여부', '상품명', '운영기한'
]

final = final[columns_to_keep]

In [134]:
final.to_csv("서민금융진흥원_상품정보.csv", index=False)

In [139]:
import pandas as pd
import os
import re
from typing import Union, List

# 🔧 유틸 함수
def is_missing(value: Union[str, List]) -> bool:
    return value is None or (isinstance(value, str) and value.strip() == "-")

def sanitize_filename(s: str) -> str:
    s = re.sub(r"[^\w가-힣]", "", s)
    return s[:30]

# 🧠 하나의 상품 정보를 자연어 문장으로 변환
def convert_row_to_text(data: dict) -> str:
    lines = []

    lines.append(f"[{data['기준년월']}] 기준 정보입니다.")
    lines.append(f"{data['제공기관명']}에서 '{data['금융상품명']}' 상품을 제공합니다.")
    lines.append(f"상품명(내부 코드용)은 '{data['상품명']}'입니다.")
    lines.append(f"운영기한은 {data['운영기한']}까지입니다.")
    lines.append(f"자금용도는 {data['용도']}입니다.")
    lines.append(f"대출 한도는 {data['대출한도']}입니다.")
    lines.append(f"금리 구분은 {data['금리구분']}이며, 금리는 {data['금리']}입니다.")
    lines.append(f"상환 방식은 {data['상환방법']}입니다.")
    lines.append(f"가입 대상은 {data['대상']}입니다.")

    if not is_missing(data.get("지원대상 상세조건")):
        lines.append(f"지원 대상의 세부 조건은 '{data['지원대상 상세조건']}'입니다.")

    if not is_missing(data.get("신용등급")):
        lines.append(f"요구되는 신용등급은 {data['신용등급']}입니다.")

    if not is_missing(data.get("거주지역원금균등분할상환")):
        lines.append(f"거주 지역에 따른 원금균등분할상환 조건은 {data['거주지역원금균등분할상환']}입니다.")

    if not is_missing(data.get("우대금리/가산금리 조건")):
        lines.append(f"우대금리 또는 가산금리는 다음 조건에 따라 적용됩니다: {data['우대금리/가산금리 조건']}.")

    if not is_missing(data.get("연체이자율(연)")):
        lines.append(f"연체 시 적용되는 이자율은 연 {data['연체이자율(연)']}입니다.")

    if not is_missing(data.get("가입(신청)방법")):
        lines.append(f"가입 또는 신청은 '{data['가입(신청)방법']}'을 통해 가능합니다.")

    if not is_missing(data.get("연락처")):
        lines.append(f"추가 문의는 {data['연락처']}로 가능합니다.")

    if not is_missing(data.get("문의처 및 연락처")):
        lines.append(f"문의처 및 담당 부서는 다음과 같습니다: {data['문의처 및 연락처']}.")

    if not is_missing(data.get("관련 사이트")):
        lines.append(f"자세한 정보는 다음 관련 사이트에서도 확인할 수 있습니다: {data['관련 사이트']}.")

    if not is_missing(data.get("대상_필터")):
        lines.append(f"이 상품은 '{data['대상_필터']}'에 해당하는 분들을 위한 상품입니다.")

    if not is_missing(data.get("취급기관_상세보기용")):
        lines.append(f"해당 상품은 '{data['취급기관_상세보기용']}'에서 취급합니다.")

    if not is_missing(data.get("상품존재여부")):
        lines.append(f"해당 상품은 현재 {'존재합니다' if 'Y' in data['상품존재여부'] else '존재하지 않습니다'}.")

    return "\n".join(lines)

# 📁 전체 CSV 처리 → 각 상품을 txt 파일로 저장
def process_csv_to_text(csv_path: str, output_dir: str = "서민금융_금융상품"):
    df = pd.read_csv(csv_path)
    os.makedirs(output_dir, exist_ok=True)

    for idx, row in df.iterrows():
        row_dict = row.to_dict()
        기관명 = sanitize_filename(str(row_dict.get("제공기관명", "unknown")))
        상품명 = sanitize_filename(str(row_dict.get("금융상품명", f"상품_{idx}")))

        filename = f"{str(idx+1).zfill(3)}_{기관명}_{상품명}.txt"
        filepath = os.path.join(output_dir, filename)

        text = convert_row_to_text(row_dict)

        with open(filepath, "w", encoding="utf-8") as out:
            out.write(text)

        print(f"✅ 저장 완료: {filename}")

# ✅ 실행
process_csv_to_text("서민금융진흥원_상품정보.csv")

✅ 저장 완료: 001_BNK경남은행_경상남도청년전세자금경상남도협약상품경상남도청년주택임차보증.txt
✅ 저장 완료: 002_서울신용보증재단_서울시중소기업육성자금지원특별자금_희망동행자금.txt
✅ 저장 완료: 003_대구신용보증재단_운송업화물택시및건설장비운영업저금리상생특별보증.txt
✅ 저장 완료: 004_대구신용보증재단_2024년북구소상공인경영안정자금지원특례보증Ⅱ.txt
✅ 저장 완료: 005_서울신용보증재단_서울시중소기업육성자금지원경영안정자금_혁신형도약자금.txt
✅ 저장 완료: 006_서울신용보증재단_서울시중소기업육성자금지원경영안정자금_이커머스입점피해회복.txt
✅ 저장 완료: 007_서울신용보증재단_서울시중소기업육성자금지원경영안정자금_성장기반자금.txt
✅ 저장 완료: 008_서울신용보증재단_서울시중소기업육성자금지원일반자금_신속드림자금.txt
✅ 저장 완료: 009_서울신용보증재단_서울시중소기업육성자금지원특별자금_안심금리자금20.txt
✅ 저장 완료: 010_서울신용보증재단_서울시중소기업육성자금지원특별자금_친환경기업자금.txt
✅ 저장 완료: 011_IBK기업은행_IBK청년전월세대출전세.txt
✅ 저장 완료: 012_서울신용보증재단_서울시중소기업육성자금_시설자금.txt
✅ 저장 완료: 013_울산신용보증재단_울산광역시저신용소상공인특례보증.txt
✅ 저장 완료: 014_울산신용보증재단_경남은행특별출연소기업소상공인새희망새출발금융지원협약보증.txt
✅ 저장 완료: 015_울산신용보증재단_내생애첫번째맞춤형특례보증.txt
✅ 저장 완료: 016_세종신용보증재단_희망어부바특별보증.txt
✅ 저장 완료: 017_전북신용보증재단_고창군희망더드림특례보증.txt
✅ 저장 완료: 018_전북신용보증재단_완주군희망더드림특례보증.txt
✅ 저장 완료: 019_대구신용보증재단_2024년달성군소상공인경영안정자금지원특례보증.txt
✅ 저장 완료: 020_대구신용보증재단_2024년서구소상공인경영안정자금지원특례보증.txt
✅ 저장 완료: 021_대구신용보증재단_2024년중구소상공인경영안정자금지원특례보증.txt
✅ 저장 완료: 022_대구신용보증재단_2024년수성구소상공인경영안정자금지원특례보증.txt
✅ 저장 완료: 023_전북신용보증재단_스마트소공인육성협약보증.txt
✅ 저장 완료: 024_충남신용보증재단_중소벤처기업부소상공인자금.txt
✅ 저장 완료: 025_충북신용보증재단_착한가격업소활성화지원특별보증.txt
✅ 저장 완료: 026_강원신용보증재단전북신용보증재단_기업가형소상공인육성협약보증.txt
✅ 저장 완료: 027_신용보증재단중앙회_소기업소상공인전환보증대환자금.txt
✅ 저장 완료: 028_강원신용보증재단_2024농협은행첫걸음금융지원협약보증.txt
✅ 저장 완료: 029_신용보증재단중앙회_전통시장금융지원협약보증.txt
✅ 저장 완료: 030_강원신용보증재단_문턱없애기Ⅱ협약보증.txt
✅ 저장 완료: 031_강원신용보증재단_2024아이엠뱅크특별출연을통한원주시상생금융지원협약보증.txt
✅ 저장 완료: 032_경기신용보증재단_경기도중소기업육성자금특별경영자금_재해피해.txt
✅ 저장 완료: 033_경기신용보증재단_경기도중소기업육성자금특별경영자금_해양오염수방류피해소상공.txt
✅ 저장 완료: 034_경기신용보증재단_모바일특별출연협약보증.txt
✅ 저장 완료: 035_경남신용보증재단경상남도진주시_진주시소상공인육성자금.txt
✅ 저장 완료: 036_경북신용보증재단_시군소상공인특례보증.txt
✅ 저장 완료: 037_경북신용보증재단_2024경북버팀금융이차보전.txt
✅ 저장 완료: 038_전북신용보증재단_부안군희망더드림특례보증일반소상공인.txt
✅ 저장 완료: 039_전북신용보증재단_부안군희망더드림특례보증청년소상공인.txt
✅ 저장 완료: 040_전북신용보증재단_청년소상공인등지원협약보증.txt
✅ 저장 완료: 041_경남신용보증재단_경상남도희망두드림특별자금함양.txt
✅ 저장 완료: 042_충북신용보증재단_옥천군중저신용소상공인특례보증.txt
✅ 저장 완료: 043_충북신용보증재단_충북형오프라인소상공인디지털전환특별보증.txt
✅ 저장 완료: 044_충북신용보증재단_충청북도출산장려정책활성화등지원특별보증.txt
✅ 저장 완료: 045_소상공인시장진흥공단_재도전특별자금.txt
✅ 저장 완료: 046_소상공인시장진흥공단_혁신성장촉진자금.txt
✅ 저장 완료: 047_소상공인시장진흥공단_민간투자연계형매칭융자.txt
✅ 저장 완료: 048_소상공인시장진흥공단_긴급경영안정자금재해피해소상공인.txt
✅ 저장 완료: 049_소상공인시장진흥공단_긴급경영안정자금일시적경영애로소상공인.txt
✅ 저장 완료: 050_부산신용보증재단_부산시임차소상공인지원협약보증.txt
✅ 저장 완료: 051_서울신용보증재단_미래유망기업성장지원보증.txt
✅ 저장 완료: 052_대구신용보증재단_대구스타트업리더스펀드협약보증.txt
✅ 저장 완료: 053_대구신용보증재단_북구청년창업특례보증.txt
✅ 저장 완료: 054_충북신용보증재단_수출유망소상공인지원특례보증수출두드림기업지원.txt
✅ 저장 완료: 055_충북신용보증재단_스마트소공인육성협약보증하나은행.txt
✅ 저장 완료: 056_전북신용보증재단_위기업종지원협약보증.txt
✅ 저장 완료: 057_충북신용보증재단_옥천군청년창업소상공인성장지원특례보증.txt
✅ 저장 완료: 058_경남신용보증재단_경상남도희망두드림특별자금.txt
✅ 저장 완료: 059_전북신용보증재단_녹색기업지원특례보증.txt
✅ 저장 완료: 060_광주신용보증재단_2024북구소상공인디딤돌특례보증.txt
✅ 저장 완료: 061_전북신용보증재단_익산시희망더드림특례보증Track1튼튼소상공인.txt
✅ 저장 완료: 062_전북신용보증재단_익산시희망더드림특례보증Track2탄탄소상공인.txt
✅ 저장 완료: 063_전북신용보증재단_군산시희망더드림특례보증.txt
✅ 저장 완료: 064_강원신용보증재단_취약계층소상공인금융지원협약보증.txt
✅ 저장 완료: 065_대구신용보증재단_2024대구성장지원특별보증.txt
✅ 저장 완료: 066_대구신용보증재단_대구전통시장상권활성화특별보증.txt
✅ 저장 완료: 067_대구신용보증재단_대구긴급금융특별보증.txt
✅ 저장 완료: 068_전남신용보증재단_전라남도수출피해기업지원보증.txt
✅ 저장 완료: 069_제주신용보증재단_내생애첫버팀목특별보증.txt
✅ 저장 완료: 070_제주신용보증재단_소기업소상공인내생애첫버팀목특별보증.txt
✅ 저장 완료: 071_제주신용보증재단_전통시장골목상권활성화특별보증.txt
✅ 저장 완료: 072_제주신용보증재단_중신용소기업소상공인특별보증.txt
✅ 저장 완료: 073_인천신용보증재단_전세사기피해지원특례보증.txt
✅ 저장 완료: 074_광주신용보증재단_2024년광주광역시소상공인골목상권특례보증.txt
✅ 저장 완료: 075_광주신용보증재단_2024광산구소상공인상생특례보증.txt
✅ 저장 완료: 076_충북신용보증재단_증평군소상공인지원자금.txt
✅ 저장 완료: 077_충북신용보증재단_보은군소상공인지원자금.txt
✅ 저장 완료: 078_경기신용보증재단_금융기관특별출연협약보증.txt
✅ 저장 완료: 079_서울신용보증재단_사업장임차자금특별보증.txt
✅ 저장 완료: 080_신협_VAN사업자대출금.txt
✅ 저장 완료: 081_신협_자영업자스피드대출금.txt
✅ 저장 완료: 082_울산신용보증재단_울산광역시소상공인경영안정자금.txt
✅ 저장 완료: 083_울산신용보증재단_울산광역시울주군소상공인경영안정자금.txt
✅ 저장 완료: 084_울산신용보증재단_3D프린팅연관기업특례보증.txt
✅ 저장 완료: 085_울산신용보증재단_울산광역시북구소상공인경영안정자금.txt
✅ 저장 완료: 086_울산신용보증재단_울산광역시남구소상공인경영안정자금.txt
✅ 저장 완료: 087_울산신용보증재단_울산광역시동구소상공인경영안정자금.txt
✅ 저장 완료: 088_울산신용보증재단_울산광역시중구소상공인경영안정자금.txt
✅ 저장 완료: 089_울산신용보증재단_국민은행최저임금인상부담완화를위한울산광역시소기업소상공인금.txt
✅ 저장 완료: 090_울산신용보증재단_신한은행특별출연소기업소상공인따뜻한금융지원협약보증.txt
✅ 저장 완료: 091_울산신용보증재단_우리은행특별출연울산광역시소상공인등금융지원및동반성장을위한.txt
✅ 저장 완료: 092_울산신용보증재단_BNK부산은행특별출연울산광역시소기업소상공인금유지원협약보.txt
✅ 저장 완료: 093_전남신용보증재단_전라남도소상공인창업자금.txt
✅ 저장 완료: 094_전남신용보증재단_전라남도소상공인경영안정자금.txt
✅ 저장 완료: 095_신용보증재단중앙회_스마트혁신성장소상공인지원특례보증.txt
✅ 저장 완료: 096_서울신용보증재단_창업자금특별보증.txt
✅ 저장 완료: 097_전북신용보증재단_익산시소상공인특례보증.txt
✅ 저장 완료: 098_서울신용보증재단_서울시중소기업육성자금지원운전_일자리창출우수기업자금.txt
✅ 저장 완료: 099_경기신용보증재단_경기도중소기업육성자금소상공인지원_점포임차자금경영개선재창.txt
✅ 저장 완료: 100_경기신용보증재단_개인택시운송사업면허양수비용지원특례보증.txt
✅ 저장 완료: 101_경기신용보증재단_전통시장특례보증.txt
✅ 저장 완료: 102_경기신용보증재단_한국은행경기본부중소기업지원자금연계보증.txt
✅ 저장 완료: 103_경기신용보증재단_콘텐츠기업지원특례보증.txt
✅ 저장 완료: 104_경기신용보증재단_경기도중소기업육성자금특별경영자금_재도전희망특례.txt
✅ 저장 완료: 105_경북신용보증재단_2024금융기관특별출연협약보증.txt
✅ 저장 완료: 106_광주신용보증재단_금융기관협약보증.txt
✅ 저장 완료: 107_광주신용보증재단_2024남구소상공인특례보증.txt
✅ 저장 완료: 108_광주신용보증재단_2024서구영세소상공인특례보증.txt
✅ 저장 완료: 109_서민금융진흥원_전통시장소액대출.txt
✅ 저장 완료: 110_서울신용보증재단_서울시중소기업육성자금지원운전_긴급자영업자금.txt
✅ 저장 완료: 111_서울신용보증재단_서울시중소기업육성자금지원운전_재해중소기업자금.txt
✅ 저장 완료: 112_서울신용보증재단_서울시중소기업육성자금지원운전_경제활성화자금.txt
✅ 저장 완료: 113_서울신용보증재단_서울시중소기업육성자금지원운전_창업기업자금.txt
✅ 저장 완료: 114_전북신용보증재단_정읍시소상공인특례보증.txt
✅ 저장 완료: 115_전북신용보증재단_순창군소상공인특례보증.txt
✅ 저장 완료: 116_강원신용보증재단_2024강원도소상공인경영안정자금협약보증.txt
✅ 저장 완료: 117_부산신용보증재단_소상공인3無플러스특별자금.txt
✅ 저장 완료: 118_서울신용보증재단_태양광발전시설설치지원특별보증.txt
✅ 저장 완료: 119_신용보증재단중앙회_재창업특례보증.txt
✅ 저장 완료: 120_인천신용보증재단_지하도상가활성화지원특례보증.txt
✅ 저장 완료: 121_대전신용보증재단_ESG실천소기업소상공인지원특례보증.txt
✅ 저장 완료: 122_부산신용보증재단_부산디지털기업지원협약보증.txt
✅ 저장 완료: 123_서울신용보증재단_서울시중소기업육성자금지원운전_포용금융자금.txt
✅ 저장 완료: 124_서울신용보증재단_서울시중소기업육성자금지원운전_재기지원자금.txt
✅ 저장 완료: 125_전북신용보증재단_전라북도소상공인민생회복금융지원사업Track2소기업육성4.txt
✅ 저장 완료: 126_전북신용보증재단_전라북도소상공인민생회복금융지원사업Track2소기업육성4.txt
✅ 저장 완료: 127_전북신용보증재단_전라북도소상공인민생회복금융지원사업Track3자영업자다시.txt
✅ 저장 완료: 128_충북신용보증재단_충북스타트업활성화지원특별보증.txt
✅ 저장 완료: 129_전남신용보증재단_시군소상공인융자금이차보전사업.txt
✅ 저장 완료: 130_세종신용보증재단_세종특별자치시소상공인자금.txt
✅ 저장 완료: 131_충남신용보증재단_충청남도소상공인자금.txt
✅ 저장 완료: 132_강원신용보증재단_2024춘천시출연협약보증.txt
✅ 저장 완료: 133_부산신용보증재단_저축은행출연부협약보증.txt
✅ 저장 완료: 134_광주신용보증재단_2024년광주광역시청년창업특례보증.txt
✅ 저장 완료: 135_전북신용보증재단_진안군소상공인특례보증.txt
✅ 저장 완료: 136_충북신용보증재단_단양군소상공인지원자금.txt
✅ 저장 완료: 137_전북신용보증재단_김제시소상공인특례보증.txt
✅ 저장 완료: 138_전북신용보증재단_코로나금융사각지대특례보증.txt
✅ 저장 완료: 139_전북신용보증재단_전북특별자치도천년명가육성특례보증.txt
✅ 저장 완료: 140_지역신용보증재단_장애인기업특례보증.txt
✅ 저장 완료: 141_지역신용보증재단_영세관광사업자특별금융지원협약보증.txt
✅ 저장 완료: 142_지역신용보증재단_외식업자영업자금융지원협약보증.txt
✅ 저장 완료: 143_지역신용보증재단_재도전지원특례보증.txt
✅ 저장 완료: 144_충북신용보증재단_충청북도소상공인육성자금.txt
✅ 저장 완료: 145_충북신용보증재단_청주형소상공인육성자금.txt
✅ 저장 완료: 146_충북신용보증재단_충주시소상공인지원자금.txt
✅ 저장 완료: 147_충북신용보증재단_제천시소상공인지원자금.txt
✅ 저장 완료: 148_충북신용보증재단_옥천군소상공인지원자금.txt
✅ 저장 완료: 149_충북신용보증재단_옥천군소상공인지원자금_청년창업전용.txt
✅ 저장 완료: 150_충북신용보증재단_영동군소상공인지원자금.txt
✅ 저장 완료: 151_충북신용보증재단_모범납세자우대보증.txt
✅ 저장 완료: 152_BNK경남은행_우리지역氣Up서포트론영세소기업소상공인.txt
✅ 저장 완료: 153_강원신용보증재단_강원도형사회적경제기업특례보증.txt
✅ 저장 완료: 154_주택도시보증공사_중소기업취업청년전월세보증금대출.txt
✅ 저장 완료: 155_지역신용보증재단_재해중소기업특례보증.txt
✅ 저장 완료: 156_주택도시보증공사_오피스텔구입자금.txt
✅ 저장 완료: 157_주택도시보증공사_손익공유형모기지.txt
✅ 저장 완료: 158_주택도시기금_수익공유형모기지.txt
✅ 저장 완료: 159_주택도시기금_내집마련디딤돌대출.txt
✅ 저장 완료: 160_주택도시기금_노후고시원거주자주거이전대출.txt
✅ 저장 완료: 161_주택도시보증공사_버팀목전세자금.txt
✅ 저장 완료: 162_주택도시기금_신혼부부전용전세자금.txt
✅ 저장 완료: 163_주택도시보증공사_청년전용버팀목전세자금.txt
✅ 저장 완료: 164_주택도시기금_청년전용보증부월세대출.txt
✅ 저장 완료: 165_서민금융진흥원_최저신용자특례보증.txt
✅ 저장 완료: 166_주택도시보증공사_창업시설조성자금.txt
✅ 저장 완료: 167_주택도시보증공사_공동협업공간조성자금.txt
✅ 저장 완료: 168_서민금융진흥원_햇살론119.txt
✅ 저장 완료: 169_전북신용보증재단_군산산업위기대응특별지역지원특례보증.txt
✅ 저장 완료: 170_서민금융진흥원_민간사업수행기관생활안정자금_재단법인밴드.txt
✅ 저장 완료: 171_서민금융진흥원_민간사업수행기관생활안정자금_기업과공동체.txt
✅ 저장 완료: 172_서민금융진흥원_민간사업수행기관생활안정자금_신나는조합.txt
✅ 저장 완료: 173_서민금융진흥원_민간사업수행기관생활안정자금_나눔과기쁨.txt
✅ 저장 완료: 174_주택도시보증공사_임대상가조성자금.txt
✅ 저장 완료: 175_주택도시보증공사_상가리모델링자금.txt
✅ 저장 완료: 176_주택도시보증공사_주거안정월세대출.txt
✅ 저장 완료: 177_주택도시보증공사_신혼부부전용구입자금.txt
✅ 저장 완료: 178_서민금융진흥원_미소금융재기자금123_운영자금.txt
✅ 저장 완료: 179_서민금융진흥원_미소금융운영자금.txt
✅ 저장 완료: 180_서민금융진흥원_미소금융창업자금_창업초기시설자금.txt
✅ 저장 완료: 181_서민금융진흥원_미소금융사업수행기관창업운영자금_운영자금.txt
✅ 저장 완료: 182_서민금융진흥원_미소금융사업수행기관창업운영자금_창업자금.txt
✅ 저장 완료: 183_서민금융진흥원_햇살론카드.txt
✅ 저장 완료: 184_서민금융진흥원_햇살론15.txt
✅ 저장 완료: 185_SGI서울보증_사잇돌Ⅱ대출_대환형.txt
✅ 저장 완료: 186_SGI서울보증_사잇돌Ⅱ대출_표준.txt
✅ 저장 완료: 187_IBK기업은행_IBK청년전월세대출월세.txt
✅ 저장 완료: 188_서민금융진흥원_미소금융사업수행기관창업운영자금_시설개선자금.txt
✅ 저장 완료: 189_서민금융진흥원_미소금융창업자금_생계형차량구입자금.txt
✅ 저장 완료: 190_서민금융진흥원_미소금융창업자금_무등록사업자.txt
✅ 저장 완료: 191_서민금융진흥원_미소금융운영자금_무등록사업자.txt
✅ 저장 완료: 192_서민금융진흥원_민간사업수행기관창업운영자금_창업자금.txt
✅ 저장 완료: 193_경상남도_소상공인사업장구입자금.txt

### 기업마당 크롤링

##### 1페이지만 크롤링

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from bs4 import BeautifulSoup
import time
import pandas as pd


options = Options()
# options.add_argument("--headless")  
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")
options.add_argument("--start-maximized")

driver = webdriver.Chrome(options=options)
url = "https://finlife.fss.or.kr/finlife/ldng/indvlBusi/list.do?menuNo=700072"
driver.get(url)

# 금융상품 검색 클릭
search_btn = WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.XPATH, '//button[contains(text(), "금융상품 검색")]'))
)
search_btn.click()
print("✅ 검색 버튼 클릭 완료")

# 페이지 끝까지 스크롤 내리기 
prev_height = driver.execute_script('return document.body.scrollHeight')
while True:
    driver.execute_script('window.scrollTo(0, document.body.scrollHeight);')
    time.sleep(5)
    
    curr_height = driver.execute_script('return document.body.scrollHeight')
    if curr_height == prev_height:
        break
    prev_height = curr_height

html = BeautifulSoup(driver.page_source)
txt = html.find_all(class_ = 'onOffTr')
text_list = [i.text for i in txt]

# 크롤링한 데이터 df화 
columns = ['금융회사', '상품명', '자금용도', '가입대상', '대출종류', '금리방식', '상환방식', '전월 평균금리', '대표번호']
cleaned_data = []

for raw in text_list:
    # 줄 단위로 나누고 공백 제거
    lines = [line.strip() for line in raw.strip().split('\n') if line.strip()]

    if len(lines) >= 8:
        # 기본 정보 8개 추출
        base_info = lines[:8]
        
        # 대표번호 찾기: 숫자만 있고 '대표번호' 근처에 있는 값 찾기
        phone_number = ''
        for i, val in enumerate(lines):
            if '대표번호' in val and i > 0:
                candidate = lines[i - 1]
                if candidate.replace('-', '').isdigit():
                    phone_number = candidate
                    break

        # 한 행 완성
        row = base_info + [phone_number]
        cleaned_data.append(row)

# DataFrame으로 변환
df = pd.DataFrame(cleaned_data, columns=columns)

# 출력
print(df.head())

# 저장 (선택)
# df.to_csv("개인사업자대출_상품정보.csv", index=False)

✅ 검색 버튼 클릭 완료
       금융회사                상품명 자금용도  가입대상              대출종류        금리방식  \
0      국민은행     KB 동반성장협약 상생대출   일반  제한없음              담보대출  고정금리, 변동금리
1  농협은행주식회사             채움 상생론   일반  제한없음  담보대출, 보증대출, 신용대출        변동금리
2      우리은행  우리CUBE론-X(BIZ프라임)   일반    기타  담보대출, 보증대출, 신용대출  고정금리, 변동금리
3    중소기업은행       IBK일자리Plus대출   일반    기타  담보대출, 보증대출, 신용대출  고정금리, 변동금리
4  농협은행주식회사           NH산업단지대출   일반  제한없음              담보대출  고정금리, 변동금리

                      상환방식 전월 평균금리      대표번호
0                   만기일시상환   1.04%  15889999
1  만기일시상환, 원금분할상환, 원리금분할상환   2.58%  16613000
2     만기일시상환, 원금분할상환, 임의상환   2.64%  15885000
3  만기일시상환, 원금분할상환, 원리금분할상환   2.77%  15662566
4  만기일시상환, 원금분할상환, 원리금분할상환   3.14%  16613000

##### 5페이지까지 크롤링

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from bs4 import BeautifulSoup
import pandas as pd
import time

options = Options()
options.add_argument("--start-maximized")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")

driver = webdriver.Chrome(options=options)
url = "https://finlife.fss.or.kr/finlife/ldng/indvlBusi/list.do?menuNo=700072"
driver.get(url)

# "금융상품 검색" 클릭
WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.XPATH, '//button[contains(text(), "금융상품 검색")]'))
).click()

time.sleep(2)

columns = ['금융회사', '상품명', '자금용도', '가입대상', '대출종류', '금리방식', '상환방식', '전월 평균금리', '대표번호']
all_data = []

current_page = 1
max_page = 5
all_data = []

while current_page <= max_page:
    # 페이지 끝까지 스크롤 내리기 
    prev_height = driver.execute_script('return document.body.scrollHeight')
    while True:
        driver.execute_script('window.scrollTo(0, document.body.scrollHeight);')
        time.sleep(5)
    
        curr_height = driver.execute_script('return document.body.scrollHeight')
        if curr_height == prev_height:
            break
        prev_height = curr_height

    time.sleep(2)
    soup = BeautifulSoup(driver.page_source, "html.parser")
    items = soup.find_all(class_="onOffTr")

    for item in items:
        lines = [line.strip() for line in item.text.strip().split('\n') if line.strip()]
        if len(lines) >= 8:
            base_info = lines[:8]
            phone = ''
            for i, val in enumerate(lines):
                if '대표번호' in val and i > 0:
                    candidate = lines[i - 1]
                    if candidate.replace('-', '').isdigit():
                        phone = candidate
                        break
            all_data.append(base_info + [phone])
    print(f"✅ {current_page}페이지 완료")

    # 페이지 클릭 로직 
    if current_page < max_page:
        try:
            next_page = current_page + 1
            next_btn = WebDriverWait(driver, 10).until(
                EC.element_to_be_clickable(
                    (By.CSS_SELECTOR, f'a[data-pageindex="{next_page}"]')
                )
            )
            driver.execute_script("arguments[0].click();", next_btn)  # JS로 클릭
            current_page += 1
            time.sleep(2)  
        except Exception as e:
            print(f"❌ {next_page}페이지 클릭 실패: {e}")
            break
    else:
        break


# 데이터프레임 생성
import pandas as pd
columns = ['금융회사', '상품명', '자금용도', '가입대상', '대출종류', '금리방식', '상환방식', '전월 평균금리', '대표번호']
df = pd.DataFrame(all_data, columns=columns)
print(df.head())

✅ 1페이지 완료
✅ 2페이지 완료
✅ 3페이지 완료
✅ 4페이지 완료
✅ 5페이지 완료
       금융회사                상품명 자금용도  가입대상              대출종류        금리방식  \
0      국민은행     KB 동반성장협약 상생대출   일반  제한없음              담보대출  고정금리, 변동금리
1  농협은행주식회사             채움 상생론   일반  제한없음  담보대출, 보증대출, 신용대출        변동금리
2      우리은행  우리CUBE론-X(BIZ프라임)   일반    기타  담보대출, 보증대출, 신용대출  고정금리, 변동금리
3    중소기업은행       IBK일자리Plus대출   일반    기타  담보대출, 보증대출, 신용대출  고정금리, 변동금리
4  농협은행주식회사           NH산업단지대출   일반  제한없음              담보대출  고정금리, 변동금리

                      상환방식 전월 평균금리      대표번호
0                   만기일시상환   1.04%  15889999
1  만기일시상환, 원금분할상환, 원리금분할상환   2.58%  16613000
2     만기일시상환, 원금분할상환, 임의상환   2.64%  15885000
3  만기일시상환, 원금분할상환, 원리금분할상환   2.77%  15662566
4  만기일시상환, 원금분할상환, 원리금분할상환   3.14%  16613000

In [34]:
df

,금융회사,상품명,자금용도,가입대상,대출종류,금리방식,상환방식,전월 평균금리,대표번호
0,국민은행,KB 동반성장협약 상생대출,일반,제한없음,담보대출,"고정금리, 변동금리",만기일시상환,1.04%,15889999
1,농협은행주식회사,채움 상생론,일반,제한없음,"담보대출, 보증대출, 신용대출",변동금리,"만기일시상환, 원금분할상환, 원리금분할상환",2.58%,16613000
2,우리은행,우리CUBE론-X(BIZ프라임),일반,기타,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 임의상환",2.64%,15885000
3,중소기업은행,IBK일자리Plus대출,일반,기타,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",2.77%,15662566
4,농협은행주식회사,NH산업단지대출,일반,제한없음,담보대출,"고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.14%,16613000
5,주식회사 케이뱅크,사장님 부동산담보대출,"일반,대환",제한없음,담보대출,변동금리,"만기일시상환, 원금분할상환, 임의상환",3.19%,15221000
6,농협은행주식회사,행복채움 프랜차이즈론,일반,기타,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환, 임의상환",3.21%,16613000
7,중소기업은행,중기부R&D사업화자금대출,일반,기타,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.39%,15662566
8,우리은행,우리CUBE론-X(우리자산신탁),일반,제한없음,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 임의상환",3.40%,15885000
9,국민은행,KB 우량산업단지기업 우대대출,일반,제한없음,"담보대출, 보증대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.43%,15889999
10,중소기업은행,IBK스마트공장지원대출,일반,기타,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.44%,15662566
11,중소기업은행,IBK시설투자대출,일반,기타,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.47%,15662566
12,중소기업은행,동반성장협력대출,일반,기타,"담보대출, 보증대출, 신용대출","고정금리, 변동금리",만기일시상환,3.52%,15662566
13,중소기업은행,ESG경영성공지원시설자금대출,일반,기타,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.54%,15662566
14,한국스탠다드차타드은행,비즈니스모기지(Mortgage),일반,제한없음,담보대출,"고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.54%,15881599
15,국민은행,KB 더드림(The Dream) 소호대출,일반,제한없음,담보대출,"고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.57%,15889999
16,국민은행,KB 유망분야 성장기업 우대대출,일반,제한없음,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환",3.57%,15889999
17,농협은행주식회사,중소기업보증료지원대출,일반,제한없음,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환, 임의상환",3.60%,16613000
18,중소기업은행,IBK혁신창업대출,일반,기타,보증대출,"고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.63%,15662566
19,국민은행,KB 일사천리소호대출,일반,제한없음,담보대출,"고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.65%,15889999
20,국민은행,기업일반시설자금대출,일반,제한없음,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.66%,15889999
21,중소기업은행,첨단기술기업 육성자금대출,일반,제한없음,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.67%,15662566
22,중소기업은행,IBK문화콘텐츠대출,일반,기타,보증대출,"고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.68%,15662566
23,우리은행,"우리CUBE론-X(일반,산업단지)",일반,제한없음,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 임의상환",3.69%,15885000
24,농협은행주식회사,NH기업성장론_착한임대인우대(임대사업자 전용),일반,기타,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환, 임의상환",3.72%,16613000
25,수협은행,Sh전문직사업자파트너론,"일반,대환",기타,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.74%,15881515
26,아이엠뱅크,무브온(Move-On) 특별대출,일반,제한없음,"담보대출, 신용대출",변동금리,"만기일시상환, 원금분할상환",3.74%,15885050
27,중소기업은행,e커머스소상공인성공보증부대출,일반,기타,보증대출,변동금리,원금분할상환,3.75%,15662566
28,농협은행주식회사,채움 성공비즈니스대출,일반,제한없음,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.76%,16613000
29,농협은행주식회사,NH기술평가우수기업대출,일반,제한없음,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환, 임의상환",3.77%,16613000
30,제주은행,전문직우대론,일반,전문직,신용대출,변동금리,만기일시상환,3.78%,15880079
31,중소기업은행,IBK소상공인스마트화지원대출,일반,기타,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.79%,15662566
32,중소기업은행,가치성장대출,일반,기타,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.80%,15662566
33,아이엠뱅크,기업시설자금대출,일반,제한없음,"담보대출, 신용대출",변동금리,"만기일시상환, 원금분할상환",3.84%,15885050
34,아이엠뱅크,착한 건물주 특별대출,일반,제한없음,"담보대출, 신용대출",변동금리,"만기일시상환, 원금분할상환",3.84%,15885050
35,국민은행,KB 투게더론,일반,제한없음,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.86%,15889999
36,국민은행,KB 모아드림론,일반,제한없음,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.87%,15889999
37,중소기업은행,IBK성공창업대출,일반,기타,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환, 임의상환",3.90%,15662566
38,국민은행,기업일반운전자금대출,일반,제한없음,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.91%,15889999
39,국민은행,KB 커머셜모기지론,일반,제한없음,담보대출,"고정금리, 변동금리","만기일시상환, 원금분할상환",3.93%,15889999
40,농협은행주식회사,NH다같이성장론,일반,제한없음,신용대출,변동금리,만기일시상환,3.93%,16613000
41,주식회사 하나은행,파워메디론,"일반,창업",전문직,신용대출,"고정금리, 변동금리",만기일시상환,3.93%,15991111
42,농협은행주식회사,토지분양중도금대출,일반,제한없음,담보대출,"고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.94%,16613000
43,중소기업은행,IBK토지분양협약대출,일반,기타,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.95%,15662566
44,국민은행,ONE KB 기업 우대대출,일반,제한없음,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.97%,15889999
45,우리은행,우리 동산·채권담보대출,일반,기타,담보대출,"고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.98%,15885000
46,수협은행,New땡큐사장님대출,"일반,대환",기타,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",4.00%,15881515
47,주식회사 하나은행,HANA 전문직 소호대출,"일반,창업",전문직,신용대출,"고정금리, 변동금리",만기일시상환,4.01%,15991111
48,농협은행주식회사,NH기업성장론,일반,제한없음,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환, 임의상환",4.02%,16613000
49,아이엠뱅크,Tech biz(테크비즈)론,일반,제한없음,"담보대출, 신용대출",변동금리,"만기일시상환, 원금분할상환",4.04%,15885050

##### 모든 페이지 크롤링

In [38]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from bs4 import BeautifulSoup
import pandas as pd
import time

options = Options()
options.add_argument("--start-maximized")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")

driver = webdriver.Chrome(options=options)
url = "https://finlife.fss.or.kr/finlife/ldng/indvlBusi/list.do?menuNo=700072"
driver.get(url)

# "금융상품 검색" 클릭
WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.XPATH, '//button[contains(text(), "금융상품 검색")]'))
).click()

time.sleep(2)

columns = ['금융회사', '상품명', '자금용도', '가입대상', '대출종류', '금리방식', '상환방식', '전월 평균금리', '대표번호']
all_data = []

current_page = 1
max_page = 72
all_data = []

while current_page <= max_page:
    # 페이지 끝까지 스크롤 내리기 
    prev_height = driver.execute_script('return document.body.scrollHeight')
    while True:
        driver.execute_script('window.scrollTo(0, document.body.scrollHeight);')
        time.sleep(5)
    
        curr_height = driver.execute_script('return document.body.scrollHeight')
        if curr_height == prev_height:
            break
        prev_height = curr_height

    time.sleep(2)
    soup = BeautifulSoup(driver.page_source, "html.parser")
    items = soup.find_all(class_="onOffTr")

    for item in items:
        lines = [line.strip() for line in item.text.strip().split('\n') if line.strip()]
        if len(lines) >= 8:
            base_info = lines[:8]
            phone = ''
            for i, val in enumerate(lines):
                if '대표번호' in val and i > 0:
                    candidate = lines[i - 1]
                    if candidate.replace('-', '').isdigit():
                        phone = candidate
                        break
            all_data.append(base_info + [phone])
    print(f"✅ {current_page}페이지 완료")

    # 페이지 클릭 로직 
    if current_page < max_page:
        try:
            next_page = current_page + 1
            next_btn = WebDriverWait(driver, 10).until(
                EC.element_to_be_clickable(
                    (By.CSS_SELECTOR, f'a[data-pageindex="{next_page}"]')
                )
            )
            driver.execute_script("arguments[0].click();", next_btn)  # JS로 클릭
            current_page += 1
            time.sleep(2)  
        except Exception as e:
            print(f"❌ {next_page}페이지 클릭 실패: {e}")
            break
    else:
        break


# 데이터프레임 생성
import pandas as pd
columns = ['금융회사', '상품명', '자금용도', '가입대상', '대출종류', '금리방식', '상환방식', '전월 평균금리', '대표번호']
df = pd.DataFrame(all_data, columns=columns)
print(df.head())

# 종료
driver.quit()

✅ 1페이지 완료
✅ 2페이지 완료
✅ 3페이지 완료
✅ 4페이지 완료
✅ 5페이지 완료
✅ 6페이지 완료
✅ 7페이지 완료
✅ 8페이지 완료
✅ 9페이지 완료
✅ 10페이지 완료
✅ 11페이지 완료
✅ 12페이지 완료
✅ 13페이지 완료
✅ 14페이지 완료
✅ 15페이지 완료
✅ 16페이지 완료
✅ 17페이지 완료
✅ 18페이지 완료
✅ 19페이지 완료
✅ 20페이지 완료
✅ 21페이지 완료
✅ 22페이지 완료
✅ 23페이지 완료
✅ 24페이지 완료
✅ 25페이지 완료
✅ 26페이지 완료
✅ 27페이지 완료
✅ 28페이지 완료
✅ 29페이지 완료
✅ 30페이지 완료
✅ 31페이지 완료
✅ 32페이지 완료
✅ 33페이지 완료
✅ 34페이지 완료
✅ 35페이지 완료
✅ 36페이지 완료
✅ 37페이지 완료
✅ 38페이지 완료
✅ 39페이지 완료
✅ 40페이지 완료
✅ 41페이지 완료
✅ 42페이지 완료
✅ 43페이지 완료
✅ 44페이지 완료
✅ 45페이지 완료
✅ 46페이지 완료
✅ 47페이지 완료
✅ 48페이지 완료
✅ 49페이지 완료
✅ 50페이지 완료
✅ 51페이지 완료
✅ 52페이지 완료
✅ 53페이지 완료
✅ 54페이지 완료
✅ 55페이지 완료
✅ 56페이지 완료
✅ 57페이지 완료
✅ 58페이지 완료
✅ 59페이지 완료
✅ 60페이지 완료
✅ 61페이지 완료
✅ 62페이지 완료
✅ 63페이지 완료
✅ 64페이지 완료
✅ 65페이지 완료
✅ 66페이지 완료
✅ 67페이지 완료
✅ 68페이지 완료
✅ 69페이지 완료
✅ 70페이지 완료
✅ 71페이지 완료
✅ 72페이지 완료
       금융회사                상품명 자금용도  가입대상              대출종류        금리방식  \
0      국민은행     KB 동반성장협약 상생대출   일반  제한없음              담보대출  고정금리, 변동금리
1  농협은행주식회사             채움 상생론   일반  제한없음  담보대출, 보증대출, 신용대출        변동금리
2      우리은행  우리CUBE론-X(BIZ프라임)   일반    기타  담보대출, 보증대출, 신용대출  고정금리, 변동금리
3    중소기업은행       IBK일자리Plus대출   일반    기타  담보대출, 보증대출, 신용대출  고정금리, 변동금리
4  농협은행주식회사           NH산업단지대출   일반  제한없음              담보대출  고정금리, 변동금리

                      상환방식 전월 평균금리      대표번호
0                   만기일시상환   1.04%  15889999
1  만기일시상환, 원금분할상환, 원리금분할상환   2.58%  16613000
2     만기일시상환, 원금분할상환, 임의상환   2.64%  15885000
3  만기일시상환, 원금분할상환, 원리금분할상환   2.77%  15662566
4  만기일시상환, 원금분할상환, 원리금분할상환   3.14%  16613000

In [46]:
df

,금융회사,상품명,자금용도,가입대상,대출종류,금리방식,상환방식,전월 평균금리,대표번호
0,국민은행,KB 동반성장협약 상생대출,일반,제한없음,담보대출,"고정금리, 변동금리",만기일시상환,1.04%,15889999
1,농협은행주식회사,채움 상생론,일반,제한없음,"담보대출, 보증대출, 신용대출",변동금리,"만기일시상환, 원금분할상환, 원리금분할상환",2.58%,16613000
2,우리은행,우리CUBE론-X(BIZ프라임),일반,기타,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 임의상환",2.64%,15885000
3,중소기업은행,IBK일자리Plus대출,일반,기타,"담보대출, 보증대출, 신용대출","고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",2.77%,15662566
4,농협은행주식회사,NH산업단지대출,일반,제한없음,담보대출,"고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",3.14%,16613000
...,...,...,...,...,...,...,...,...,...
708,KB저축은행,PF대출,"일반,창업,대환",제한없음,담보대출,"고정금리, 변동금리","만기일시상환, 임의상환",-,18990900
709,MS저축은행,부동산담보대출,일반,제한없음,담보대출,"고정금리, 변동금리","만기일시상환, 원금분할상환, 원리금분할상환",-,0537565200
710,MS저축은행,할인어음,일반,제한없음,"담보대출, 신용대출","고정금리, 변동금리",만기일시상환,-,0537565200
711,OK저축은행,숙박업OK론Ⅱ,일반,제한없음,담보대출,고정금리,"만기일시상환, 원금분할상환, 원리금분할상환",-,18997979
712,OK저축은행,NPL채권매입자금대출,일반,제한없음,담보대출,고정금리,"만기일시상환, 원금분할상환, 원리금분할상환",-,18997979

In [47]:
# csv로 저장
df.to_csv("기업마당_개인사업자대출.csv", index=False)

#### 상세정보도 크롤링

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from bs4 import BeautifulSoup
import pandas as pd
import time

options = Options()
options.add_argument("--start-maximized")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")

driver = webdriver.Chrome(options=options)
url = "https://finlife.fss.or.kr/finlife/ldng/indvlBusi/list.do?menuNo=700072"
driver.get(url)

# "금융상품 검색" 클릭
WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.XPATH, '//button[contains(text(), "금융상품 검색")]'))
).click()

time.sleep(2)

columns = ['금융회사', '상품명', '자금용도', '가입대상', '대출종류', '금리방식', '상환방식', '전월 평균금리', '대표번호','상세정보']
all_data = []

current_page = 1
max_page = 2
all_data = []

while current_page <= max_page:
    # 페이지 끝까지 스크롤
    driver.execute_script('window.scrollTo(0, document.body.scrollHeight);')
    time.sleep(2)

    # BeautifulSoup 파싱
    soup = BeautifulSoup(driver.page_source, "html.parser")
    items = soup.find_all(class_="onOffTr")

    for idx, item in enumerate(items):
        # 기본 정보 추출
        lines = [line.strip() for line in item.text.strip().split('\n') if line.strip()]
        if len(lines) < 8:
            continue
        base_info = lines[:8]

        # 대표번호 추출
        phone = ''
        for i, val in enumerate(lines):
            if '대표번호' in val and i > 0:
                candidate = lines[i - 1]
                if candidate.replace('-', '').isdigit():
                    phone = candidate
                    break

        # 상세 버튼 클릭
        try:
            detail_buttons = driver.find_elements(By.CSS_SELECTOR, 'a.tabel-more')
            driver.execute_script("arguments[0].click();", detail_buttons[idx])
            time.sleep(1.5)

            # 상세정보가 포함된 show-box 파싱
            detail_soup = BeautifulSoup(driver.page_source, "html.parser")
            show_boxes = detail_soup.select("tr.show-box")
            detail_text = show_boxes[idx].get_text(separator=' | ', strip=True) if idx < len(show_boxes) else ''

        except Exception as e:
            print(f"❌ 상세 정보 추출 실패 (index {idx}): {e}")
            detail_text = ''

        all_data.append(base_info + [phone, detail_text])
        print(f"✅ {current_page}페이지 - {idx+1}번째 상품 완료")

    # 다음 페이지 클릭
    if current_page < max_page:
        try:
            next_page = current_page + 1
            next_btn = WebDriverWait(driver, 10).until(
                EC.element_to_be_clickable((By.CSS_SELECTOR, f'a[data-pageindex="{next_page}"]'))
            )
            driver.execute_script("arguments[0].click();", next_btn)
            current_page += 1
            time.sleep(2)
        except Exception as e:
            print(f"❌ {next_page}페이지 클릭 실패: {e}")
            break
    else:
        break

# 데이터 저장
df = pd.DataFrame(all_data, columns=columns)
print(df.head())
# 종료
driver.quit()

✅ 1페이지 - 1번째 상품 완료
✅ 1페이지 - 2번째 상품 완료
✅ 1페이지 - 3번째 상품 완료
✅ 1페이지 - 4번째 상품 완료
✅ 1페이지 - 5번째 상품 완료
✅ 1페이지 - 6번째 상품 완료
✅ 1페이지 - 7번째 상품 완료
✅ 1페이지 - 8번째 상품 완료
✅ 1페이지 - 9번째 상품 완료
✅ 1페이지 - 10번째 상품 완료
✅ 2페이지 - 1번째 상품 완료
✅ 2페이지 - 2번째 상품 완료
✅ 2페이지 - 3번째 상품 완료
✅ 2페이지 - 4번째 상품 완료
✅ 2페이지 - 5번째 상품 완료
✅ 2페이지 - 6번째 상품 완료
✅ 2페이지 - 7번째 상품 완료
✅ 2페이지 - 8번째 상품 완료
✅ 2페이지 - 9번째 상품 완료
✅ 2페이지 - 10번째 상품 완료
       금융회사                상품명 자금용도  가입대상              대출종류        금리방식  \
0      국민은행     KB 동반성장협약 상생대출   일반  제한없음              담보대출  고정금리, 변동금리
1  농협은행주식회사             채움 상생론   일반  제한없음  담보대출, 보증대출, 신용대출        변동금리
2      우리은행  우리CUBE론-X(BIZ프라임)   일반    기타  담보대출, 보증대출, 신용대출  고정금리, 변동금리
3    중소기업은행       IBK일자리Plus대출   일반    기타  담보대출, 보증대출, 신용대출  고정금리, 변동금리
4  농협은행주식회사           NH산업단지대출   일반  제한없음              담보대출  고정금리, 변동금리

                      상환방식 전월 평균금리      대표번호  \
0                   만기일시상환   1.04%  15889999
1  만기일시상환, 원금분할상환, 원리금분할상환   2.58%  16613000
2     만기일시상환, 원금분할상환, 임의상환   2.64%  15885000
3  만기일시상환, 원금분할상환, 원리금분할상환   2.77%  15662566
4  만기일시상환, 원금분할상환, 원리금분할상환   3.14%  16613000

                                                상세정보
0  비교공시일 : | 2025-07-11 | 적용가능 금리 | 최고금리: 4.56% |...
1  비교공시일 : | 2025-07-16 | 900점 초과 | 801~900점 | 70...
2  비교공시일 : | 2025-07-17 | 900점 초과 | 801~900점 | 70...
3  비교공시일 : | 2025-07-17 | 900점 초과 | 801~900점 | 70...
4  비교공시일 : | 2025-07-16 | 적용가능 금리 | 최고금리: 5.73% |...

In [7]:
df.to_csv("금융상품_상세정보포함.csv", index=False, encoding='utf-8-sig')

##### JSON 파일로 저장(최종)

In [47]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from bs4 import BeautifulSoup
import json
import time

# ✅ Selenium 옵션 설정
options = Options()
options.add_argument("--start-maximized")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")

driver = webdriver.Chrome(options=options)
url = "https://finlife.fss.or.kr/finlife/ldng/indvlBusi/list.do?menuNo=700072"
driver.get(url)

# ✅ "금융상품 검색" 클릭
WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.XPATH, '//button[contains(text(), "금융상품 검색")]'))
).click()
time.sleep(2)

# ✅ 상세항목 파싱 함수
def extract_detailed_info(soup):
    target_keys = [
        "적용가능 금리", "대출한도", "가입대상 세부요건", "가입방법",
        "우대금리", "중도상환 수수료", "대출부대비용", "연체이자율", "담당부서 및 연락처"
    ]
    data = {}

    dl_sets = soup.select("div.dl-set > dl")
    for dl in dl_sets:
        dt_tag = dl.find("dt")
        dd_tags = dl.find_all("dd")

        if not dt_tag or not dd_tags:
            continue

        key = dt_tag.get_text(strip=True).replace('\xa0', ' ').strip()
        if key not in target_keys:
            # 유사 항목 대응 (예: 공백이 다른 경우 등)
            matched = [k for k in target_keys if k in key]
            if matched:
                key = matched[0]
            else:
                continue

        combined_lines = []
        for dd_tag in dd_tags:
            raw_html = dd_tag.decode_contents().replace('\xa0', ' ')
            if "<br>" in raw_html:
                lines = [BeautifulSoup(line, 'html.parser').get_text(strip=True)
                         for line in raw_html.split('<br>') if line.strip()]
                combined_lines.extend(lines)
            else:
                text = dd_tag.get_text(separator="\n", strip=True).replace('\xa0', ' ')
                lines = [line.strip() for line in text.split('\n') if line.strip()]
                combined_lines.extend(lines)

        data[key] = combined_lines if len(combined_lines) > 1 else combined_lines[0] if combined_lines else ""

    # 누락된 항목 기본값 추가
    for key in target_keys:
        if key not in data:
            data[key] = ""

    return data

# ✅ 크롤링 시작
start_time = time.time()
all_products = []
current_page = 1
max_page = 72
success_count = 0
fail_count = 0

while current_page <= max_page:
    driver.execute_script('window.scrollTo(0, document.body.scrollHeight);')
    time.sleep(2)

    soup = BeautifulSoup(driver.page_source, "html.parser")
    items = soup.find_all(class_="onOffTr")

    for idx, item in enumerate(items):
        lines = [line.strip() for line in item.text.strip().split('\n') if line.strip()]
        if len(lines) < 8:
            print(f"⚠️ {current_page}페이지 - {idx+1}번 상품: 기본 정보 부족으로 스킵")
            fail_count += 1
            continue

        base_info = lines[:8]

        try:
            detail_buttons = driver.find_elements(By.CSS_SELECTOR, 'a.tabel-more')
            driver.execute_script("arguments[0].click();", detail_buttons[idx])
            time.sleep(1.5)

            detail_soup = BeautifulSoup(driver.page_source, "html.parser")
            detailed_info = extract_detailed_info(detail_soup)

            product = {
                "금융회사": base_info[0],
                "상품명": base_info[1],
                "자금용도": base_info[2],
                "가입대상": base_info[3],
                "대출종류": base_info[4],
                "금리방식": base_info[5],
                "상환방식": base_info[6],
                "전월 평균금리": base_info[7],
                **detailed_info
            }

            all_products.append(product)
            success_count += 1

        except Exception as e:
            print(f"❌ {current_page}페이지 - {idx+1}번 상품: 상세 클릭 실패 → {e}")
            fail_count += 1
    print(f"✅ {current_page}페이지 수집 완료")

    # 다음 페이지 이동
    if current_page < max_page:
        try:
            next_page = current_page + 1
            next_btn = WebDriverWait(driver, 10).until(
                EC.element_to_be_clickable((By.CSS_SELECTOR, f'a[data-pageindex="{next_page}"]'))
            )
            driver.execute_script("arguments[0].click();", next_btn)
            current_page += 1
            time.sleep(2)
        except Exception as e:
            print(f"❌ {next_page}페이지 이동 실패: {e}")
            break
    else:
        break

# ✅ JSON 저장
with open("금융상품한눈에.json", "w", encoding="utf-8") as f:
    json.dump(all_products, f, ensure_ascii=False, indent=2)

end_time = time.time()
print(f"\n📦 총 상품 수집 성공: {success_count}개")
print(f"⚠️ 실패 또는 누락 상품: {fail_count}개")
print("📁 금융상품 데이터를 JSON 형식으로 저장 완료!")
print(f"\n⏱️ 총 소요 시간: {end_time - start_time:.2f}초")

driver.quit()

✅ 1페이지 수집 완료
✅ 2페이지 수집 완료
✅ 3페이지 수집 완료
✅ 4페이지 수집 완료
✅ 5페이지 수집 완료
✅ 6페이지 수집 완료
✅ 7페이지 수집 완료
✅ 8페이지 수집 완료
✅ 9페이지 수집 완료
✅ 10페이지 수집 완료
✅ 11페이지 수집 완료
✅ 12페이지 수집 완료
✅ 13페이지 수집 완료
✅ 14페이지 수집 완료
✅ 15페이지 수집 완료
✅ 16페이지 수집 완료
✅ 17페이지 수집 완료
✅ 18페이지 수집 완료
✅ 19페이지 수집 완료
✅ 20페이지 수집 완료
✅ 21페이지 수집 완료
✅ 22페이지 수집 완료
✅ 23페이지 수집 완료
✅ 24페이지 수집 완료
✅ 25페이지 수집 완료
✅ 26페이지 수집 완료
✅ 27페이지 수집 완료
✅ 28페이지 수집 완료
✅ 29페이지 수집 완료
✅ 30페이지 수집 완료
✅ 31페이지 수집 완료
✅ 32페이지 수집 완료
✅ 33페이지 수집 완료
✅ 34페이지 수집 완료
✅ 35페이지 수집 완료
✅ 36페이지 수집 완료
✅ 37페이지 수집 완료
✅ 38페이지 수집 완료
✅ 39페이지 수집 완료
✅ 40페이지 수집 완료
✅ 41페이지 수집 완료
✅ 42페이지 수집 완료
✅ 43페이지 수집 완료
✅ 44페이지 수집 완료
✅ 45페이지 수집 완료
✅ 46페이지 수집 완료
✅ 47페이지 수집 완료
✅ 48페이지 수집 완료
✅ 49페이지 수집 완료
✅ 50페이지 수집 완료
✅ 51페이지 수집 완료
✅ 52페이지 수집 완료
✅ 53페이지 수집 완료
✅ 54페이지 수집 완료
✅ 55페이지 수집 완료
✅ 56페이지 수집 완료
✅ 57페이지 수집 완료
✅ 58페이지 수집 완료
✅ 59페이지 수집 완료
✅ 60페이지 수집 완료
✅ 61페이지 수집 완료
✅ 62페이지 수집 완료
✅ 63페이지 수집 완료
✅ 64페이지 수집 완료
✅ 65페이지 수집 완료
✅ 66페이지 수집 완료
✅ 67페이지 수집 완료
✅ 68페이지 수집 완료
✅ 69페이지 수집 완료
✅ 70페이지 수집 완료
✅ 71페이지 수집 완료
✅ 72페이지 수집 완료

📦 총 상품 수집 성공: 713개
⚠️ 실패 또는 누락 상품: 0개
📁 금융상품 데이터를 JSON 형식으로 저장 완료!

⏱️ 총 소요 시간: 1489.36초

In [46]:
from collections import OrderedDict
import json

# 저장한 파일 경로
file_path = "금융상품한눈에.json"

with open("금융상품한눈에.json", "r", encoding="utf-8") as f:
    data = json.load(f, object_pairs_hook=OrderedDict)

# 개수 확인
print(f"총 상품 개수: {len(data)}개")

# 첫 번째 상품 미리보기
import pprint
pprint.pprint(data[1], width=120)

총 상품 개수: 10개
OrderedDict([('금융회사', '농협은행주식회사'),
             ('상품명', '채움 상생론'),
             ('자금용도', '일반'),
             ('가입대상', '제한없음'),
             ('대출종류', '담보대출, 보증대출, 신용대출'),
             ('금리방식', '변동금리'),
             ('상환방식', '만기일시상환, 원금분할상환, 원리금분할상환'),
             ('전월 평균금리', '2.58%'),
             ('적용가능 금리', ['최고금리: 5.04%', '최저금리: 5.04%']),
             ('대출한도', '개별협약 내용에 따름'),
             ('가입대상 세부요건', 'NH농협은행과 상생펀드 구성 협약을 체결한 대기업의 협력 중소기업(개인사업자 포함)'),
             ('가입방법', '영업점'),
             ('우대금리', '-'),
             ('중도상환 수수료',
              ['· 중도상환해약금 = [중도상환원금×적용요율×(잔여기간÷대출기간)]',
               '※ 중도상환해약금 적용 요율',
               '[고정금리대출인 경우]',
               '- 기업대출(부동산담보) : 1.4%',
               '- 기업대출(신용/보증서/기타담보) : 1.1%',
               '[변동금리대출인 경우]',
               '- 기업대출(부동산담보) : 1.2%',
               '- 기업대출(신용/보증서/기타담보) : 1.0%',
               '※ 대출취급일로부터 3년까지 적용합니다.']),
             ('대출부대비용',
              ['· 인지세(공통)',
               '인지세법에 의해 대출약정 체결 시 납부하는 세금으로 대출금액에 따라 차등 적용되며, 각 50%씩 고객님과 농협은행이 부담합니다.',
               '- 5천만원 이하 : 비과세',
               '- 5천만원 초과 1억원 이하 : 7만원',
               '- 1억원 초과 10억원 이하 : 15만원',
               '- 10억원 초과 : 35만원']),
             ('연체이자율',
              '지연배상금률은 연체기간에 관계없이 연체일수 × (채무자 대출금리 + 3%) ÷ 365(윤년은 366)를 적용하되, 지연배상금률이 연 15%를 초과하는 경우에는 연 15%를 적용합니다.'),
             ('담당부서 및 연락처', '개인고객부, 02-2080-3420(개인 여신 상품), 3395(개인 수신 상품)')])

# JSON → 자연어 서술형 변환 코드

### 리스트 있는 형식

In [56]:
import json
import os
import re
from typing import Union, List

def is_missing(value: Union[str, List]) -> bool:
    if value is None:
        return True
    if isinstance(value, str) and value.strip() == "-":
        return True
    return False

def sanitize_filename(s: str) -> str:
    s = re.sub(r"[^\w가-힣]", "", s)
    return s[:30]

def convert_loan_json_to_text(data):
    lines = []

    lines.append(f"{data['금융회사']}에서는 '{data['상품명']}' 상품을 제공합니다.")
    lines.append(f"자금용도는 {data['자금용도']}입니다.")
    lines.append(f"대출 종류는 {data['대출종류']}입니다.")
    lines.append(f"금리 방식은 {data['금리방식']}입니다.")
    lines.append(f"상환 방식은 {data['상환방식']}입니다.")
    lines.append(f"가입 대상은 {data['가입대상']}입니다.")

    if not is_missing(data.get("가입대상 세부요건")):
        lines.append(f"구체적인 가입 요건은 '{data['가입대상 세부요건']}'입니다.")

    if not is_missing(data.get("전월 평균금리")):
        lines.append(f"전월 평균금리는 {data['전월 평균금리']}입니다.")
    else:
        lines.append("전월 평균금리는 제공되지 않았습니다.")

    if isinstance(data.get("적용가능 금리"), list) and len(data["적용가능 금리"]) == 2:
        최고금리 = data["적용가능 금리"][0].split(": ")[1]
        최저금리 = data["적용가능 금리"][1].split(": ")[1]
        lines.append(f"적용 가능 금리는 최고 {최고금리}, 최저 {최저금리}입니다.")

    if not is_missing(data.get("대출한도")):
        lines.append(f"대출 한도는 {data['대출한도']}입니다.")

    if not is_missing(data.get("우대금리")):
        lines.append(f"우대금리는 {data['우대금리']}입니다.")

    if not is_missing(data.get("가입방법")):
        lines.append(f"가입은 {data['가입방법']}을 통해 가능합니다.")

    수수료 = data.get("중도상환 수수료")
    if 수수료 and not is_missing(수수료):
        if isinstance(수수료, list):
            lines.append("중도상환 수수료:")
            lines.extend([f"- {s.strip('-').strip()}" for s in 수수료])
        else:
            lines.append(f"중도상환 수수료는 {수수료}입니다.")

    비용 = data.get("대출부대비용")
    if 비용 and not is_missing(비용):
        if isinstance(비용, list):
            lines.append("대출 부대비용:")
            lines.extend([f"- {b.strip('-').strip()}" for b in 비용])
        else:
            lines.append(f"대출 부대비용에는 {비용} 등이 포함됩니다.")

    연체 = data.get("연체이자율")
    if 연체 and not is_missing(연체):
        if isinstance(연체, list):
            lines.append("연체 이자율:")
            lines.extend([f"- {r}" for r in 연체])
        else:
            lines.append(f"연체 이자율은 {연체}입니다.")

    담당 = data.get("담당부서 및 연락처")
    if 담당 and not is_missing(담당):
        if isinstance(담당, list):
            lines.append("담당 부서 및 연락처:")
            lines.extend([f"- {d}" for d in 담당])
        else:
            lines.append(f"담당 부서 및 연락처는 {담당}입니다.")

    return "\n".join(lines)

def process_json_to_text(input_json_path, output_dir):
    with open(input_json_path, "r", encoding="utf-8") as f:
        items = json.load(f)

    os.makedirs(output_dir, exist_ok=True)

    for idx, item in enumerate(items, start=1):
        금융회사 = sanitize_filename(item.get("금융회사", "unknown"))
        상품명 = sanitize_filename(item.get("상품명", f"상품_{idx}"))

        filename = f"{str(idx).zfill(3)}_{금융회사}_{상품명}.txt"
        filepath = os.path.join(output_dir, filename)

        text = convert_loan_json_to_text(item)

        with open(filepath, "w", encoding="utf-8") as out:
            out.write(text)

        print(f"✅ 저장 완료: {filename}")

# 실행 예시
process_json_to_text("금융상품한눈에.json", "금융상품_chunks")

✅ 저장 완료: 001_국민은행_KB동반성장협약상생대출.txt
✅ 저장 완료: 002_농협은행주식회사_채움상생론.txt
✅ 저장 완료: 003_우리은행_우리CUBE론XBIZ프라임.txt
✅ 저장 완료: 004_중소기업은행_IBK일자리Plus대출.txt
✅ 저장 완료: 005_농협은행주식회사_NH산업단지대출.txt
✅ 저장 완료: 006_주식회사케이뱅크_사장님부동산담보대출.txt
✅ 저장 완료: 007_농협은행주식회사_행복채움프랜차이즈론.txt
✅ 저장 완료: 008_중소기업은행_중기부RD사업화자금대출.txt
✅ 저장 완료: 009_우리은행_우리CUBE론X우리자산신탁.txt
✅ 저장 완료: 010_국민은행_KB우량산업단지기업우대대출.txt
✅ 저장 완료: 011_중소기업은행_IBK스마트공장지원대출.txt
✅ 저장 완료: 012_중소기업은행_IBK시설투자대출.txt
✅ 저장 완료: 013_중소기업은행_동반성장협력대출.txt
✅ 저장 완료: 014_중소기업은행_ESG경영성공지원시설자금대출.txt
✅ 저장 완료: 015_한국스탠다드차타드은행_비즈니스모기지Mortgage.txt
✅ 저장 완료: 016_국민은행_KB더드림TheDream소호대출.txt
✅ 저장 완료: 017_국민은행_KB유망분야성장기업우대대출.txt
✅ 저장 완료: 018_농협은행주식회사_중소기업보증료지원대출.txt
✅ 저장 완료: 019_중소기업은행_IBK혁신창업대출.txt
✅ 저장 완료: 020_국민은행_KB일사천리소호대출.txt
✅ 저장 완료: 021_국민은행_기업일반시설자금대출.txt
✅ 저장 완료: 022_중소기업은행_첨단기술기업육성자금대출.txt
✅ 저장 완료: 023_중소기업은행_IBK문화콘텐츠대출.txt
✅ 저장 완료: 024_우리은행_우리CUBE론X일반산업단지.txt
✅ 저장 완료: 025_농협은행주식회사_NH기업성장론_착한임대인우대임대사업자전용.txt
✅ 저장 완료: 026_수협은행_Sh전문직사업자파트너론.txt
✅ 저장 완료: 027_아이엠뱅크_무브온MoveOn특별대출.txt
✅ 저장 완료: 028_중소기업은행_e커머스소상공인성공보증부대출.txt
✅ 저장 완료: 029_농협은행주식회사_채움성공비즈니스대출.txt
✅ 저장 완료: 030_농협은행주식회사_NH기술평가우수기업대출.txt
✅ 저장 완료: 031_제주은행_전문직우대론.txt
✅ 저장 완료: 032_중소기업은행_IBK소상공인스마트화지원대출.txt
✅ 저장 완료: 033_중소기업은행_가치성장대출.txt
✅ 저장 완료: 034_아이엠뱅크_기업시설자금대출.txt
✅ 저장 완료: 035_아이엠뱅크_착한건물주특별대출.txt
✅ 저장 완료: 036_국민은행_KB투게더론.txt
✅ 저장 완료: 037_국민은행_KB모아드림론.txt
✅ 저장 완료: 038_중소기업은행_IBK성공창업대출.txt
✅ 저장 완료: 039_국민은행_기업일반운전자금대출.txt
✅ 저장 완료: 040_국민은행_KB커머셜모기지론.txt
✅ 저장 완료: 041_농협은행주식회사_NH다같이성장론.txt
✅ 저장 완료: 042_주식회사하나은행_파워메디론.txt
✅ 저장 완료: 043_농협은행주식회사_토지분양중도금대출.txt
✅ 저장 완료: 044_중소기업은행_IBK토지분양협약대출.txt
✅ 저장 완료: 045_국민은행_ONEKB기업우대대출.txt
✅ 저장 완료: 046_우리은행_우리동산채권담보대출.txt
✅ 저장 완료: 047_수협은행_New땡큐사장님대출.txt
✅ 저장 완료: 048_주식회사하나은행_HANA전문직소호대출.txt
✅ 저장 완료: 049_농협은행주식회사_NH기업성장론.txt
✅ 저장 완료: 050_아이엠뱅크_Techbiz테크비즈론.txt
✅ 저장 완료: 051_국민은행_KB상생결제론.txt
✅ 저장 완료: 052_국민은행_KB메디칼론.txt
✅ 저장 완료: 053_신한은행_신용보증재단특례보증대출재창업소상공인지원.txt
✅ 저장 완료: 054_신한은행_신용보증재단협약보증대출청년소상공인지원.txt
✅ 저장 완료: 055_중소기업은행_턴업기업지원자금대출.txt
✅ 저장 완료: 056_국민은행_KBGreenGrowthLoan.txt
✅ 저장 완료: 057_수협은행_Sh소호대출.txt
✅ 저장 완료: 058_주식회사하나은행_닥터클럽대출플래티늄.txt
✅ 저장 완료: 059_중소기업은행_무역금융.txt
✅ 저장 완료: 060_수협은행_부동산경락대금대출.txt
✅ 저장 완료: 061_중소기업은행_스마트동산담보대출.txt
✅ 저장 완료: 062_농협은행주식회사_이노메인비즈대출.txt
✅ 저장 완료: 063_아이엠뱅크_탑티어TopTier전문직사업자대출.txt
✅ 저장 완료: 064_농협은행주식회사_NH트러스트온보증대출.txt
✅ 저장 완료: 065_아이엠뱅크_기업운전자금대출.txt
✅ 저장 완료: 066_국민은행_KB우수기술기업TCB신용대출.txt
✅ 저장 완료: 067_국민은행_KB동반성장네트워크론AType.txt
✅ 저장 완료: 068_농협은행주식회사_NH농식품기업우대론.txt
✅ 저장 완료: 069_한국스탠다드차타드은행_보증서담보대출GIL.txt
✅ 저장 완료: 070_농협은행주식회사_NH농식품그린성장론.txt
✅ 저장 완료: 071_중소기업은행_해내리대출.txt
✅ 저장 완료: 072_신한은행_신용보증재단특례보증대출재창업소상공인지원분할상환.txt
✅ 저장 완료: 073_농협은행주식회사_기업구매자금대출.txt
✅ 저장 완료: 074_신한은행_신한온택트보증서대출.txt
✅ 저장 완료: 075_중소기업은행_IBK소상공인희망대출.txt
✅ 저장 완료: 076_국민은행_KBe구매자금대출.txt
✅ 저장 완료: 077_국민은행_기업일반통장자동대출.txt
✅ 저장 완료: 078_중소기업은행_iONE동반성장신용대출.txt
✅ 저장 완료: 079_중소기업은행_B2B팩토링.txt
✅ 저장 완료: 080_중소기업은행_트러스트온보증부대출.txt
✅ 저장 완료: 081_우리은행_우리상생파트너론.txt
✅ 저장 완료: 082_농협은행주식회사_전자방식외상매출채권담보대출.txt
✅ 저장 완료: 083_신한은행_강원신용보증재단특례보증대출.txt
✅ 저장 완료: 084_제주은행_기술평가우수기업대출.txt
✅ 저장 완료: 085_중소기업은행_원자재가격부담완화지원대출.txt
✅ 저장 완료: 086_중소기업은행_BOX개인사업자신용대출.txt
✅ 저장 완료: 087_농협은행주식회사_NH기업성공대출.txt
✅ 저장 완료: 088_중소기업은행_클린플러스보증부대출.txt
✅ 저장 완료: 089_국민은행_KB프랜차이즈대출.txt
✅ 저장 완료: 090_광주은행_KJBSOLARLOAN.txt
✅ 저장 완료: 091_우리은행_B2BPLUS대출.txt
✅ 저장 완료: 092_중소기업은행_소상공인초장기분할상환특별대출.txt
✅ 저장 완료: 093_국민은행_외상매출채권전자대출순구매방식.txt
✅ 저장 완료: 094_국민은행_KB공급망밸류업대출.txt
✅ 저장 완료: 095_중소기업은행_복합위기극복지원대출.txt
✅ 저장 완료: 096_국민은행_유형자산담보대출.txt
✅ 저장 완료: 097_우리은행_우리메디플러스론.txt
✅ 저장 완료: 098_우리은행_B2B대출.txt
✅ 저장 완료: 099_중소기업은행_소부장혁신지원대출.txt
✅ 저장 완료: 100_광주은행_비즈니스파트너론.txt
✅ 저장 완료: 101_수협은행_Sh숙박사업자파트너론.txt
✅ 저장 완료: 102_신한은행_신한사업자대출IN네이버페이.txt
✅ 저장 완료: 103_제주은행_JJB가맹점우대론.txt
✅ 저장 완료: 104_국민은행_외상매출채권전자대출역구매방식.txt
✅ 저장 완료: 105_국민은행_KB셀러론.txt
✅ 저장 완료: 106_국민은행_KB더드림TheDream소호신용대출.txt
✅ 저장 완료: 107_삼성생명보험주식회사_상업용부동산담보대출.txt
✅ 저장 완료: 108_농협은행주식회사_SOHO가맹점주우대대출.txt
✅ 저장 완료: 109_국민은행_전문직사업자우대대출.txt
✅ 저장 완료: 110_광주은행_기업튼튼보증서대출.txt
✅ 저장 완료: 111_수협은행_토지분양자금대출.txt
✅ 저장 완료: 112_국민은행_전자채권담보대출.txt
✅ 저장 완료: 113_국민은행_KB지식산업센터중도금대출.txt
✅ 저장 완료: 114_국민은행_KB구매론.txt
✅ 저장 완료: 115_국민은행_KB소상공인신용대출.txt
✅ 저장 완료: 116_농협은행주식회사_EZ구매론.txt
✅ 저장 완료: 117_수협은행_기업운전자금대출.txt
✅ 저장 완료: 118_아이엠뱅크_상업어음할인.txt
✅ 저장 완료: 119_국민은행_협약에의한토지분양자금대출.txt
✅ 저장 완료: 120_신한은행_신한사업자대출INSOL.txt
✅ 저장 완료: 121_신한은행_신한사업자대출IN토스.txt
✅ 저장 완료: 122_국민은행_KB상생플러스론AType.txt
✅ 저장 완료: 123_우리은행_우리사장님대출.txt
✅ 저장 완료: 124_제주은행_태양광발전사업자대출.txt
✅ 저장 완료: 125_중소기업은행_기업회전대출.txt
✅ 저장 완료: 126_삼성화재해상보험주식회사_삼성소호아파트.txt
✅ 저장 완료: 127_중소기업은행_해양수산기술사업화자금.txt
✅ 저장 완료: 128_수협은행_기업시설자금대출.txt
✅ 저장 완료: 129_광주은행_비즈니스아파트론.txt
✅ 저장 완료: 130_농협은행주식회사_NH메디칼론.txt
✅ 저장 완료: 131_비엠더블유파이낸셜서비스코리아_재고금융A.txt
✅ 저장 완료: 132_중소기업은행_수시로대출.txt
✅ 저장 완료: 133_주식회사케이뱅크_사장님신용대출.txt
✅ 저장 완료: 134_주식회사하나은행_프랜차이즈가맹점대출.txt
✅ 저장 완료: 135_제주은행_JJB부동산담보대출.txt
✅ 저장 완료: 136_중소기업은행_롯데마트패밀리론.txt
✅ 저장 완료: 137_신한은행_신한사업자대출INSOL분할상환.txt
✅ 저장 완료: 138_신한은행_신한사업자대출IN토스분할상환.txt
✅ 저장 완료: 139_농협은행주식회사_NH지식산업센터중도금대출.txt
✅ 저장 완료: 140_수협은행_집단주택자금대출.txt
✅ 저장 완료: 141_중소기업은행_싸이클론.txt
✅ 저장 완료: 142_중소기업은행_iONE가맹점성공대출.txt
✅ 저장 완료: 143_아이엠뱅크_iM으뜸사장님특별대출.txt
✅ 저장 완료: 144_농협은행주식회사_B2B구매자금대출.txt
✅ 저장 완료: 145_국민은행_KB소호신용대출.txt
✅ 저장 완료: 146_중소기업은행_iONE소상공인대출.txt
✅ 저장 완료: 147_농협은행주식회사_채움중소기업우대론.txt
✅ 저장 완료: 148_제주은행_병원약국우대대출.txt
✅ 저장 완료: 149_신한은행_신한사업자대출IN네이버페이분할상환.txt
✅ 저장 완료: 150_국민은행_상업어음할인.txt
✅ 저장 완료: 151_모아저축은행_부동산담보대출.txt
✅ 저장 완료: 152_중소기업은행_B2B구매자금대출.txt
✅ 저장 완료: 153_중소기업은행_네트워크론.txt
✅ 저장 완료: 154_현대커머셜_현대자동차신차할부.txt
✅ 저장 완료: 155_농협은행주식회사_NH베스트닥터론.txt
✅ 저장 완료: 156_우리은행_파워브랜드가맹점창업대출.txt
✅ 저장 완료: 157_우리은행_우리동네사장님대출.txt
✅ 저장 완료: 158_중소기업은행_B2B전자구매론.txt
✅ 저장 완료: 159_국민은행_KB메가셀러론.txt
✅ 저장 완료: 160_국민은행_사장님마이너스통장.txt
✅ 저장 완료: 161_산은캐피탈_신차승용오토론.txt
✅ 저장 완료: 162_중소기업은행_기업구매자금대출.txt
✅ 저장 완료: 163_중소기업은행_전자채권담보대출.txt
✅ 저장 완료: 164_농협은행주식회사_유형자산담보대출.txt
✅ 저장 완료: 165_중소기업은행_조달청제휴네트워크론.txt
✅ 저장 완료: 166_주식회사카카오뱅크_개인사업자신용대출.txt
✅ 저장 완료: 167_하나캐피탈_정상오토론.txt
✅ 저장 완료: 168_엔에이치농협캐피탈_할부수입상용1.txt
✅ 저장 완료: 169_중소기업은행_할인어음.txt
✅ 저장 완료: 170_신한은행_신한프랜차이즈론분할상환운전자금.txt
✅ 저장 완료: 171_우리은행_협력기업상생대출.txt
✅ 저장 완료: 172_중소기업은행_외화대출.txt
✅ 저장 완료: 173_농협은행주식회사_네트워크론.txt
✅ 저장 완료: 174_아산저축은행_일반자금대출.txt
✅ 저장 완료: 175_중소기업은행_전자방식외상매출채권담보대출.txt
✅ 저장 완료: 176_흥국화재해상보험주식회사_2502흥국SOHO아파트대출.txt
✅ 저장 완료: 177_아이엠뱅크_기업통장대출.txt
✅ 저장 완료: 178_케이비캐피탈_수입신차.txt
✅ 저장 완료: 179_중소기업은행_협동조합B2B구매카드대출.txt
✅ 저장 완료: 180_엔에이치농협캐피탈_할부수입상용2.txt
✅ 저장 완료: 181_중소기업은행_공공구매론.txt
✅ 저장 완료: 182_엔에이치농협캐피탈_사료구매자금대출.txt
✅ 저장 완료: 183_현대커머셜_부동산PF.txt
✅ 저장 완료: 184_엔에이치농협캐피탈_국내상용론1.txt
✅ 저장 완료: 185_엔에이치농협캐피탈_할부특장.txt
✅ 저장 완료: 186_비엔케이캐피탈_신차승용구매담보대출.txt
✅ 저장 완료: 187_현대커머셜_현대자동차신차특장차할부.txt
✅ 저장 완료: 188_중소기업은행_한전파워에너지론.txt
✅ 저장 완료: 189_엔에이치농협캐피탈_할부건설기계.txt
✅ 저장 완료: 190_현대커머셜_HD현대건설기계신차건설기계할부.txt
✅ 저장 완료: 191_우리은행_우리카드가맹점우대대출.txt
✅ 저장 완료: 192_신한은행_땡겨요사업자대출.txt
✅ 저장 완료: 193_아이엠캐피탈_장비대출_신차화물중소형.txt
✅ 저장 완료: 194_비엠더블유파이낸셜서비스코리아_재고금융B.txt
✅ 저장 완료: 195_대신저축은행_부동산담보대출.txt
✅ 저장 완료: 196_토스뱅크주식회사_사장님신용대출.txt
✅ 저장 완료: 197_아이엠캐피탈_장비대출_신차건기.txt
✅ 저장 완료: 198_롯데캐피탈_운영자금오토론.txt
✅ 저장 완료: 199_비엔케이캐피탈_자동차재고금융대출.txt
✅ 저장 완료: 200_농협은행주식회사_NHe사장님바로대출.txt
✅ 저장 완료: 201_엔에이치농협캐피탈_특장론2.txt
✅ 저장 완료: 202_아이엠캐피탈_장비대출_신차화물대형.txt
✅ 저장 완료: 203_현대해상화재보험주식회사_현대해상사업자론아파트.txt
✅ 저장 완료: 204_현대커머셜_HD현대건설기계신차건설기계어태치포함형할부.txt
✅ 저장 완료: 205_엔에이치농협캐피탈_건설기계론.txt
✅ 저장 완료: 206_아이엠캐피탈_신차오토론.txt
✅ 저장 완료: 207_케이비캐피탈_신차상용.txt
✅ 저장 완료: 208_농협은행주식회사_NH개인택시우대대출.txt
✅ 저장 완료: 209_엔에이치농협캐피탈_할부국내상용2.txt
✅ 저장 완료: 210_볼보파이낸셜서비스코리아_상용차론.txt
✅ 저장 완료: 211_볼보파이낸셜서비스코리아_상용차할부.txt
✅ 저장 완료: 212_현대커머셜_운영자금대출사료구매론.txt
✅ 저장 완료: 213_모아저축은행_중도금대출.txt
✅ 저장 완료: 214_키움예스저축은행_개인사업자아파트담보대출후순위만기일시.txt
✅ 저장 완료: 215_아이엠캐피탈_장비대출_신차버스일반.txt
✅ 저장 완료: 216_BNK저축은행_중도금대출비주택.txt
✅ 저장 완료: 217_엔에이치농협캐피탈_할부산업기계.txt
✅ 저장 완료: 218_엔에이치농협캐피탈_산업기계론.txt
✅ 저장 완료: 219_엔에이치농협캐피탈_주택사업자금대출선.txt
✅ 저장 완료: 220_현대커머셜_현대자동차신차트럭변동금리형할부.txt
✅ 저장 완료: 221_현대캐피탈_사업자프라임모기지론5년고정후순위.txt
✅ 저장 완료: 222_비엔케이캐피탈_산업재구입자금대출.txt
✅ 저장 완료: 223_오릭스캐피탈코리아_사업자담보대출.txt
✅ 저장 완료: 224_BNK저축은행_BNK아파트사업자금대출.txt
✅ 저장 완료: 225_제이비우리캐피탈_중고승용재고금융.txt
✅ 저장 완료: 226_푸른저축은행_부동산담보대출.txt
✅ 저장 완료: 227_하나저축은행_기타부동산담보대출.txt
✅ 저장 완료: 228_엔에이치농협캐피탈_할부국내상용1.txt
✅ 저장 완료: 229_우리은행_우리은행네이버스마트스토어대출.txt
✅ 저장 완료: 230_우리은행_우리은행네이버스마트플레이스대출.txt
✅ 저장 완료: 231_한국캐피탈_재고금융.txt
✅ 저장 완료: 232_현대캐피탈_사업자프라임모기지론5년고정1순위.txt
✅ 저장 완료: 233_현대커머셜_동해기계항공신차특장차할부.txt
✅ 저장 완료: 234_진주저축은행_부동산담보대출.txt
✅ 저장 완료: 235_진주저축은행_전문직마스터론.txt
✅ 저장 완료: 236_토스뱅크주식회사_사장님마이너스통장.txt
✅ 저장 완료: 237_현대커머셜_HD현대사이트솔루션신차건설기계할부.txt
✅ 저장 완료: 238_볼보파이낸셜서비스코리아_건설기계론.txt
✅ 저장 완료: 239_볼보파이낸셜서비스코리아_건설기계할부.txt
✅ 저장 완료: 240_케이비캐피탈_재고금융.txt
✅ 저장 완료: 241_아산저축은행_종합통장대출.txt
✅ 저장 완료: 242_한국투자저축은행_숙박시설지원자금대출.txt
✅ 저장 완료: 243_신한은행_신한프랜차이즈론운전자금.txt
✅ 저장 완료: 244_우리은행_우리Oh5클릭대출.txt
✅ 저장 완료: 245_오릭스캐피탈코리아_재고금융.txt
✅ 저장 완료: 246_삼호저축은행_햇살론.txt
✅ 저장 완료: 247_진주저축은행_지분론.txt
✅ 저장 완료: 248_평택저축은행_주택담보대출아파트외.txt
✅ 저장 완료: 249_오릭스캐피탈코리아_승용신차일반대출.txt
✅ 저장 완료: 250_현대캐피탈_사업자프라임모기지론후순위.txt
✅ 저장 완료: 251_하나캐피탈_제휴파트너론중고차.txt
✅ 저장 완료: 252_엔에이치농협캐피탈_주택사업자금대출후.txt
✅ 저장 완료: 253_하나캐피탈_디지털중고차론.txt
✅ 저장 완료: 254_키움예스저축은행_개인사업자부동산담보대출.txt
✅ 저장 완료: 255_애큐온저축은행_아파트후순위대출.txt
✅ 저장 완료: 256_산은캐피탈_중고상용오토론.txt
✅ 저장 완료: 257_하나캐피탈_재고금융ll특화중고차.txt
✅ 저장 완료: 258_비엔케이캐피탈_신차상용구매담보대출.txt
✅ 저장 완료: 259_하나캐피탈_재고금융중고차.txt
✅ 저장 완료: 260_아이비케이캐피탈_부동산담보대출.txt
✅ 저장 완료: 261_데라게란덴_시설자금대출.txt
✅ 저장 완료: 262_우리금융캐피탈_우리금융캐피탈모기지론사업자금_고정_수도권.txt
✅ 저장 완료: 263_주식회사하나은행_개인사업자장기분할상환.txt
✅ 저장 완료: 264_롯데캐피탈_오토론.txt
✅ 저장 완료: 265_현대캐피탈_사업자프라임모기지론1순위.txt
✅ 저장 완료: 266_아이엠캐피탈_인수금대출.txt
✅ 저장 완료: 267_한국투자저축은행_부동산담보대출.txt
✅ 저장 완료: 268_알씨아이파이낸셜서비스코리아_재고금융인벤토리론.txt
✅ 저장 완료: 269_하나캐피탈_재고금융ll중고차.txt
✅ 저장 완료: 270_아이엠캐피탈_장비대출건설기계중고구매.txt
✅ 저장 완료: 271_메리츠캐피탈_건설장비기계개인사업자대출.txt
✅ 저장 완료: 272_페퍼저축은행_건설기계구입자금대출종합통장대출.txt
✅ 저장 완료: 273_한국자산캐피탈_일반자금대출.txt
✅ 저장 완료: 274_하나캐피탈_개인사업자아파트담보대출.txt
✅ 저장 완료: 275_아이엠캐피탈_장비대출건설기계중고운영.txt
✅ 저장 완료: 276_에코캐피탈_개인사업자신용대출기타보증대출.txt
✅ 저장 완료: 277_아이엠캐피탈_장비대출건설기계신품.txt
✅ 저장 완료: 278_한국투자저축은행_사업자아파트담보대출.txt
✅ 저장 완료: 279_현대커머셜_현대커머셜신차론.txt
✅ 저장 완료: 280_유안타저축은행_유안타비즈론만기일시.txt
✅ 저장 완료: 281_롯데카드_건설기계담보대출.txt
✅ 저장 완료: 282_유안타저축은행_유안타비즈론원리금균등.txt
✅ 저장 완료: 283_한국캐피탈_운전.txt
✅ 저장 완료: 284_비엔케이캐피탈_사업자금대출.txt
✅ 저장 완료: 285_케이비캐피탈_운영자금.txt
✅ 저장 완료: 286_페퍼저축은행_페퍼비즈니스론.txt
✅ 저장 완료: 287_비엠더블유파이낸셜서비스코리아_재고금융C.txt
✅ 저장 완료: 288_엠지캐피탈_주택담보대출.txt
✅ 저장 완료: 289_페퍼저축은행_건설기계담보대출일반자금대출.txt
✅ 저장 완료: 290_신한저축은행_사업자아파트담보대출.txt
✅ 저장 완료: 291_현대커머셜_현대커머셜신차특장차론.txt
✅ 저장 완료: 292_애큐온저축은행_건설기계담보대출크레인.txt
✅ 저장 완료: 293_오릭스캐피탈코리아_건설장비담보대출.txt
✅ 저장 완료: 294_OK저축은행_OK모기지론.txt
✅ 저장 완료: 295_엔에이치농협캐피탈_NH특수장비론1.txt
✅ 저장 완료: 296_신한은행_소상공인상생매일땡겨드림대출.txt
✅ 저장 완료: 297_안양저축은행_종합통장대출.txt
✅ 저장 완료: 298_엠지캐피탈_기타담보.txt
✅ 저장 완료: 299_롯데캐피탈_건설기계론.txt
✅ 저장 완료: 300_안양저축은행_일반자금대출.txt
✅ 저장 완료: 301_애큐온캐피탈_Captive산업차량.txt
✅ 저장 완료: 302_애큐온저축은행_건설기계구입대출크레인.txt
✅ 저장 완료: 303_엔에이치농협캐피탈_NH산업재론.txt
✅ 저장 완료: 304_현대커머셜_현대커머셜중고크레인구입론.txt
✅ 저장 완료: 305_농협은행주식회사_NH지식재산권IP담보대출.txt
✅ 저장 완료: 306_트라톤파이낸셜서비스코리아_일반대출.txt
✅ 저장 완료: 307_고려저축은행_사업자후순위부동산담보대출.txt
✅ 저장 완료: 308_아이엠캐피탈_장비대출산업기계재고금융.txt
✅ 저장 완료: 309_아이엠캐피탈_장비대출중고건기상용구매.txt
✅ 저장 완료: 310_인천저축은행_이동형크레인담보대출.txt
✅ 저장 완료: 311_비엔케이캐피탈_중고상용구매담보대출.txt
✅ 저장 완료: 312_애큐온캐피탈_Commercial기업대출.txt
✅ 저장 완료: 313_국민은행_KB매출더하기론통합플랫폼.txt
✅ 저장 완료: 314_OK저축은행_사업자후순위아파트OK론.txt
✅ 저장 완료: 315_현대커머셜_현대커머셜중고크레인담보론.txt
✅ 저장 완료: 316_오릭스캐피탈코리아_중고승용담보대출.txt
✅ 저장 완료: 317_케이비캐피탈_중고상용.txt
✅ 저장 완료: 318_도이치파이낸셜_재고금융.txt
✅ 저장 완료: 319_메리츠캐피탈_의료인사업자대출.txt
✅ 저장 완료: 320_비엔케이캐피탈_중고승용구매담보대출.txt
✅ 저장 완료: 321_애큐온캐피탈_NonCaptive건설기계.txt
✅ 저장 완료: 322_오릭스캐피탈코리아_대형상용담보대출.txt
✅ 저장 완료: 323_국민은행_KB메가셀러론글로벌.txt
✅ 저장 완료: 324_하나캐피탈_리텐션론.txt
✅ 저장 완료: 325_한국캐피탈_중고상용.txt
✅ 저장 완료: 326_웰컴저축은행_웰컴부동산하이브리드.txt
✅ 저장 완료: 327_한국캐피탈_중고승용.txt
✅ 저장 완료: 328_아이엠캐피탈_장비대출중고건기상용대환운영.txt
✅ 저장 완료: 329_메리츠캐피탈_국산중고개인사업자대출수입중고개인사업자대출.txt
✅ 저장 완료: 330_애큐온캐피탈_주택담보대출후순위.txt
✅ 저장 완료: 331_메리츠캐피탈_중고상용차오토론.txt
✅ 저장 완료: 332_고려저축은행_메디칼론.txt
✅ 저장 완료: 333_OSB저축은행_오비즈론신잔액COFIXPA5.txt
✅ 저장 완료: 334_대백저축은행_외상채권비어음선취.txt
✅ 저장 완료: 335_대백저축은행_할인어음상업어음.txt
✅ 저장 완료: 336_웰컴저축은행_웰컴사업자아파트대출.txt
✅ 저장 완료: 337_OSB저축은행_오비즈론신잔액COFIXIO3PA2.txt
✅ 저장 완료: 338_제이비우리캐피탈_중고승용구입대출.txt
✅ 저장 완료: 339_안양저축은행_할인어음.txt
✅ 저장 완료: 340_한국투자캐피탈_자산플러스론.txt
✅ 저장 완료: 341_애큐온캐피탈_Captive건설기계.txt
✅ 저장 완료: 342_비엠더블유파이낸셜서비스코리아_재고금융D.txt
✅ 저장 완료: 343_현대커머셜_중고다이렉트담보론사전한도추가일반.txt
✅ 저장 완료: 344_케이비캐피탈_중고차대출.txt
✅ 저장 완료: 345_애큐온캐피탈_NonCaptive상용차.txt
✅ 저장 완료: 346_현대커머셜_중고다이렉트담보론사전한도리스케줄일반.txt
✅ 저장 완료: 347_키움예스저축은행_음악저작권담보대출.txt
✅ 저장 완료: 348_현대커머셜_중고다이렉트추가담보론중고연계.txt
✅ 저장 완료: 349_현대커머셜_중고다이렉트담보론사전한도종료일반.txt
✅ 저장 완료: 350_현대커머셜_중고다이렉트일반담보론.txt
✅ 저장 완료: 351_현대커머셜_중고다이렉트담보론추가일반신차연계.txt
✅ 저장 완료: 352_애큐온캐피탈_주택담보대출선순위.txt
✅ 저장 완료: 353_현대커머셜_중고다이렉트구입론.txt
✅ 저장 완료: 354_케이비캐피탈_중고차할부.txt
✅ 저장 완료: 355_제이비우리캐피탈_중고승용세이빙카.txt
✅ 저장 완료: 356_현대커머셜_중고다이렉트담보론리스케줄신차연계.txt
✅ 저장 완료: 357_현대커머셜_현대커머셜중고담보론.txt
✅ 저장 완료: 358_현대커머셜_현대커머셜중고구입론.txt
✅ 저장 완료: 359_현대커머셜_중고다이렉트추가담보론중고연계.txt
✅ 저장 완료: 360_제이비우리캐피탈_중고승용할부구입대출.txt
✅ 저장 완료: 361_현대커머셜_개인사업자신용대출.txt
✅ 저장 완료: 362_한국캐피탈_소매담보.txt
✅ 저장 완료: 363_웰컴저축은행_웰컴PC론.txt
✅ 저장 완료: 364_아이엠캐피탈_SOHO아파트론.txt
✅ 저장 완료: 365_제이비우리캐피탈_주택담보생활자금대출.txt
✅ 저장 완료: 366_케이비캐피탈_신용대출.txt
✅ 저장 완료: 367_하나캐피탈_행복아파트론.txt
✅ 저장 완료: 368_하나캐피탈_원큐자동차담보대출.txt
✅ 저장 완료: 369_하나캐피탈_추가대출.txt
✅ 저장 완료: 370_아이엠캐피탈_연계오토담보론.txt
✅ 저장 완료: 371_아이엠캐피탈_리치론.txt
✅ 저장 완료: 372_하나캐피탈_원큐자동차담보대출대환.txt
✅ 저장 완료: 373_아이엠캐피탈_연계중금리론.txt
✅ 저장 완료: 374_하나캐피탈_XSELL론.txt
✅ 저장 완료: 375_우리금융캐피탈_사업자아파트신용대출인다이렉트.txt
✅ 저장 완료: 376_케이비국민카드_KB국민개인사업자대출.txt
✅ 저장 완료: 377_비씨카드_BC카드가맹점대출.txt
✅ 저장 완료: 378_미래에셋캐피탈_스마트스토어대출.txt
✅ 저장 완료: 379_상상인플러스저축은행_오토론.txt
✅ 저장 완료: 380_한국투자캐피탈_자산플러스론.txt
✅ 저장 완료: 381_한국투자캐피탈_오토플러스론.txt
✅ 저장 완료: 382_우리카드_개인사업자신용대출.txt
✅ 저장 완료: 383_아이엠캐피탈_아파트론1.txt
✅ 저장 완료: 384_다올저축은행_Fi사업자Npay.txt
✅ 저장 완료: 385_아이엠캐피탈_오토담보론.txt
✅ 저장 완료: 386_우리금융캐피탈_우수고객_추가대출개인사업자.txt
✅ 저장 완료: 387_우리금융캐피탈_사업자자산론인다이렉트.txt
✅ 저장 완료: 388_페퍼저축은행_GREENE오토론사업자선순위.txt
✅ 저장 완료: 389_다올저축은행_Fi사업자toss.txt
✅ 저장 완료: 390_우리금융캐피탈_사업자자산론다이렉트.txt
✅ 저장 완료: 391_우리금융캐피탈_우수고객_추가대출개인사업자.txt
✅ 저장 완료: 392_다올저축은행_Fi사업자B.txt
✅ 저장 완료: 393_제이비우리캐피탈_개인신용대출.txt
✅ 저장 완료: 394_삼호저축은행_예쓰론C자동차담보대출.txt
✅ 저장 완료: 395_웰컴저축은행_웰컴희망대출.txt
✅ 저장 완료: 396_도이치파이낸셜_오토담보론.txt
✅ 저장 완료: 397_웰컴저축은행_웰컴자동차담보대출.txt
✅ 저장 완료: 398_한국캐피탈_신용.txt
✅ 저장 완료: 399_제이비우리캐피탈_자동차담보대출.txt
✅ 저장 완료: 400_페퍼저축은행_오토담보론사업자.txt
✅ 저장 완료: 401_비엔케이캐피탈_신용대출PLUS.txt
✅ 저장 완료: 402_한국캐피탈_오토담보.txt
✅ 저장 완료: 403_제이비우리캐피탈_자산론.txt
✅ 저장 완료: 404_한성저축은행_가맹점대출.txt
✅ 저장 완료: 405_한성저축은행_성업대출.txt
✅ 저장 완료: 406_웰컴저축은행_웰컴뱅크론.txt
✅ 저장 완료: 407_마스턴캐피탈_사업자담보대출.txt
✅ 저장 완료: 408_아이비케이캐피탈_기업어음할인.txt
✅ 저장 완료: 409_아이비케이캐피탈_기업자금대출.txt
✅ 저장 완료: 410_아이비케이캐피탈_리스금융.txt
✅ 저장 완료: 411_아이비케이캐피탈_비대면팩토링.txt
✅ 저장 완료: 412_아이비케이캐피탈_팩토링.txt
✅ 저장 완료: 413_아이비케이캐피탈_할부대출건설기계.txt
✅ 저장 완료: 414_아이비케이캐피탈_할부대출상용차.txt
✅ 저장 완료: 415_아이엠캐피탈_개인사업자대상기업일반대출담보.txt
✅ 저장 완료: 416_아이엠캐피탈_개인사업자대상기업일반대출신용.txt
✅ 저장 완료: 417_아이엠캐피탈_다이렉트아파트론.txt
✅ 저장 완료: 418_에이치비캐피탈_사업자신용대출.txt
✅ 저장 완료: 419_광주은행_기술창조우수기업대출.txt
✅ 저장 완료: 420_광주은행_메디컬파트너론.txt
✅ 저장 완료: 421_광주은행_사회적경제기업SUPPORT_LOAN.txt
✅ 저장 완료: 422_광주은행_센트럴요양원대출.txt
✅ 저장 완료: 423_광주은행_쏠쏠센트럴비즈론.txt
✅ 저장 완료: 424_광주은행_특화산업단지대출.txt
✅ 저장 완료: 425_광주은행_포용금융특별대출.txt
✅ 저장 완료: 426_광주은행_ESGSUPPORTLOAN.txt
✅ 저장 완료: 427_광주은행_KJBTRUSTON보증서대출.txt
✅ 저장 완료: 428_광주은행_KJB동산담보대출.txt
✅ 저장 완료: 429_국민은행_기업당좌대출.txt
✅ 저장 완료: 430_국민은행_매출채권담보대출.txt
✅ 저장 완료: 431_국민은행_무역금융.txt
✅ 저장 완료: 432_국민은행_예부적금관계대출.txt
✅ 저장 완료: 433_국민은행_외화대출.txt
✅ 저장 완료: 434_국민은행_장기분할상환부동산담보대출.txt
✅ 저장 완료: 435_국민은행_재고자산담보대출.txt
✅ 저장 완료: 436_국민은행_B2BKB일석e조매출채권보험담보대출.txt
✅ 저장 완료: 437_국민은행_B2B공공기관하도급대금담보대출.txt
✅ 저장 완료: 438_국민은행_B2B동반성장매출채권담보대출.txt
✅ 저장 완료: 439_국민은행_KBBiz장기분할시설자금대출.txt
✅ 저장 완료: 440_국민은행_KBGreenWaveESG우수기업대출.txt
✅ 저장 완료: 441_국민은행_KB노란우산공제기업우대대출.txt
✅ 저장 완료: 442_국민은행_KB더드림지식재산IP담보대출.txt
✅ 저장 완료: 443_국민은행_KB미래성장기업우대대출.txt
✅ 저장 완료: 444_국민은행_KB민간협약토지분양자금대출.txt
✅ 저장 완료: 445_국민은행_KB사회적경제기업우대대출.txt
✅ 저장 완료: 446_국민은행_KB소규모주택사업자건설자금대출.txt
✅ 저장 완료: 447_국민은행_KB수출기업우대대출.txt
✅ 저장 완료: 448_국민은행_KB업무시설오피스중도금대출.txt
✅ 저장 완료: 449_국민은행_KB우수상권우대대출.txt
✅ 저장 완료: 450_국민은행_KB재해복구금융지원프로그램.txt
✅ 저장 완료: 451_국민은행_KB지식산업센터입주기업대출.txt
✅ 저장 완료: 452_국민은행_KB태양광발전사업자우대대출.txt
✅ 저장 완료: 453_국민은행_KB특화산업단지입주기업대출.txt
✅ 저장 완료: 454_국민은행_KB플러스론.txt
✅ 저장 완료: 455_국민은행_KB동반성장네트워크론BType.txt
✅ 저장 완료: 456_국민은행_KB상생플러스론BType.txt
✅ 저장 완료: 457_국제저축은행_일반자금대출.txt
✅ 저장 완료: 458_금화저축은행_개인사업자대출.txt
✅ 저장 완료: 459_농협은행주식회사_농축수산물담보대출.txt
✅ 저장 완료: 460_농협은행주식회사_매출채권담보대출.txt
✅ 저장 완료: 461_농협은행주식회사_어린이집대출.txt
✅ 저장 완료: 462_농협은행주식회사_재고자산담보대출.txt
✅ 저장 완료: 463_농협은행주식회사_전자채권담보대출.txt
✅ 저장 완료: 464_농협은행주식회사_NH모바일지자체협약대출.txt
✅ 저장 완료: 465_농협은행주식회사_NH모바일지자체협약대출경기보증재단.txt
✅ 저장 완료: 466_농협은행주식회사_NH스마트팜론.txt
✅ 저장 완료: 467_농협은행주식회사_NH일자리창업농식품기업우대대출.txt
✅ 저장 완료: 468_농협은행주식회사_NH한금우대론.txt
✅ 저장 완료: 469_다올저축은행_Fi비즈론.txt
✅ 저장 완료: 470_다올저축은행_Fi주식담보대출.txt
✅ 저장 완료: 471_다올저축은행_Fi주택담보대출.txt
✅ 저장 완료: 472_대명상호저축은행_사업자아파트월수분할.txt
✅ 저장 완료: 473_대명상호저축은행_사업자아파트월수일시.txt
✅ 저장 완료: 474_대백저축은행_공장담보대출월수일시.txt
✅ 저장 완료: 475_대백저축은행_기운일대월수일시.txt
✅ 저장 완료: 476_대백저축은행_기운종합통장대출.txt
✅ 저장 완료: 477_대백저축은행_상가담보대출월수분할.txt
✅ 저장 완료: 478_대백저축은행_상가담보대출월수일시.txt
✅ 저장 완료: 479_대백저축은행_자영업자주택담보대출월수일시.txt
✅ 저장 완료: 480_대백저축은행_토지담보대출월수일시.txt
✅ 저장 완료: 481_대신저축은행_대신비즈론.txt
✅ 저장 완료: 482_드림저축은행_기업신용대출월수일시.txt
✅ 저장 완료: 483_드림저축은행_기타부동산담보대출월수일시.txt
✅ 저장 완료: 484_드림저축은행_아파트담보대출사업자고정금리.txt
✅ 저장 완료: 485_디비캐피탈_사료대출.txt
✅ 저장 완료: 486_라온저축은행_일반자금대출.txt
✅ 저장 완료: 487_라온저축은행_일반자금대출.txt
✅ 저장 완료: 488_롯데캐피탈_신용대출.txt
✅ 저장 완료: 489_롯데캐피탈_자동차담보대출.txt
✅ 저장 완료: 490_리딩에이스캐피탈_사업자아파트담보대출.txt
✅ 저장 완료: 491_볼보파이낸셜서비스코리아_중고건설기계론.txt
✅ 저장 완료: 492_볼보파이낸셜서비스코리아_중고건설기계할부.txt
✅ 저장 완료: 493_볼보파이낸셜서비스코리아_중고상용차론.txt
✅ 저장 완료: 494_비엔케이캐피탈_건설기계장비담보대출.txt
✅ 저장 완료: 495_비엔케이캐피탈_신용대출.txt
✅ 저장 완료: 496_비엔케이캐피탈_제휴사운영자금대출.txt
✅ 저장 완료: 497_비엔케이캐피탈_제휴사임차보증금대출.txt
✅ 저장 완료: 498_삼성화재해상보험주식회사_삼성소호주택.txt
✅ 저장 완료: 499_삼호저축은행_일반자금대출부동산담보.txt
✅ 저장 완료: 500_삼호저축은행_일반자금대출신용.txt
✅ 저장 완료: 501_상상인저축은행_부동산담보대출.txt
✅ 저장 완료: 502_상상인저축은행_프로젝트파이낸싱.txt
✅ 저장 완료: 503_솔브레인저축은행_일반자금대출월수균등.txt
✅ 저장 완료: 504_솔브레인저축은행_일반자금대출월수분할.txt
✅ 저장 완료: 505_솔브레인저축은행_일반자금대출월수일시.txt
✅ 저장 완료: 506_솔브레인저축은행_종합통장대출.txt
✅ 저장 완료: 507_수협은행_고시원사업자대출.txt
✅ 저장 완료: 508_수협은행_냉동수산물담보대출.txt
✅ 저장 완료: 509_수협은행_더해드림론.txt
✅ 저장 완료: 510_수협은행_매입조건부주택건축자금대출.txt
✅ 저장 완료: 511_수협은행_상업어음할인.txt
✅ 저장 완료: 512_수협은행_예적금담보대출.txt
✅ 저장 완료: 513_수협은행_카마스터즈론.txt
✅ 저장 완료: 514_수협은행_B2B구매자금대출.txt
✅ 저장 완료: 515_수협은행_MY편의점대출.txt
✅ 저장 완료: 516_수협은행_ShESG우수기업대출.txt
✅ 저장 완료: 517_수협은행_Sh기술평가우수기업대출.txt
✅ 저장 완료: 518_수협은행_Sh서울시협약주택보증대출.txt
✅ 저장 완료: 519_수협은행_Sh신용보증서Plus대출.txt
✅ 저장 완료: 520_수협은행_Sh안전협약주택보증대출.txt
✅ 저장 완료: 521_수협은행_Sh창업기업지원보증서대출.txt
✅ 저장 완료: 522_수협은행_Sh특별출연협약보증대출.txt
✅ 저장 완료: 523_수협은행_Sh프라임주택건설보증대출.txt
✅ 저장 완료: 524_신한은행_신한프랜차이즈론분할상환시설자금.txt
✅ 저장 완료: 525_신한은행_신한프랜차이즈론시설자금.txt
✅ 저장 완료: 526_신한은행_신한프랜차이즈론종합통장대출.txt
✅ 저장 완료: 527_신한저축은행_사업자담보대출신한.txt
✅ 저장 완료: 528_신한저축은행_사업자신용대출신한.txt
✅ 저장 완료: 529_신한저축은행_참신한사업자론.txt
✅ 저장 완료: 530_신한캐피탈_일반기업대출.txt
✅ 저장 완료: 531_안국저축은행_일반자금대출월수균등.txt
✅ 저장 완료: 532_안국저축은행_일반자금대출월수일시.txt
✅ 저장 완료: 533_알씨아이파이낸셜서비스코리아_운영자금대출워킹캐피탈.txt
✅ 저장 완료: 534_애큐온저축은행_사업자신용대출셀러론.txt
✅ 저장 완료: 535_애큐온저축은행_아파트선순위대출.txt
✅ 저장 완료: 536_엔에이치농협캐피탈_국내상용론2.txt
✅ 저장 완료: 537_엔에이치농협캐피탈_국산오토론.txt
✅ 저장 완료: 538_엔에이치농협캐피탈_수입상용론1.txt
✅ 저장 완료: 539_엔에이치농협캐피탈_수입상용론2.txt
✅ 저장 완료: 540_엔에이치농협캐피탈_수입오토론.txt
✅ 저장 완료: 541_엔에이치저축은행_순수일반담보APT.txt
✅ 저장 완료: 542_엔에이치저축은행_순수일반담보기타.txt
✅ 저장 완료: 543_엔에이치저축은행_순수일반신용.txt
✅ 저장 완료: 544_엔에이치저축은행_일대프로젝트파이낸싱회전식.txt
✅ 저장 완료: 545_엔에이치저축은행_일반신용기타.txt
✅ 저장 완료: 546_엔에이치저축은행_일반자금대출회전식.txt
✅ 저장 완료: 547_엔에이치저축은행_종통프로젝트파이낸싱.txt
✅ 저장 완료: 548_엔에이치저축은행_종합통장대출.txt
✅ 저장 완료: 549_엔에이치저축은행_중도금대출회전식.txt
✅ 저장 완료: 550_엔에이치저축은행_하우징론.txt
✅ 저장 완료: 551_엔에이치저축은행_NH사업자행복대출.txt
✅ 저장 완료: 552_엔에이치저축은행_NH잔금대출.txt
✅ 저장 완료: 553_엔에이치저축은행_NH투게더론.txt
✅ 저장 완료: 554_엠지캐피탈_기타부동산담보.txt
✅ 저장 완료: 555_오릭스캐피탈코리아_대형상용건설장비부가세유예담보대출.txt
✅ 저장 완료: 556_오릭스캐피탈코리아_중도금대출.txt
✅ 저장 완료: 557_오릭스캐피탈코리아_테슬라오토론.txt
✅ 저장 완료: 558_오케이캐피탈_OKAPT론.txt
✅ 저장 완료: 559_오케이캐피탈_OKLADY론.txt
✅ 저장 완료: 560_오케이캐피탈_OKPAY론.txt
✅ 저장 완료: 561_우리금융저축은행_비타WON주택.txt
✅ 저장 완료: 562_우리금융캐피탈_사업자아파트신용대출다이렉트.txt
✅ 저장 완료: 563_우리금융캐피탈_우리금융캐피탈모기지론사업자금_고정_비수도권.txt
✅ 저장 완료: 564_우리은행_단기수요자금융.txt
✅ 저장 완료: 565_우리은행_상생플러스론.txt
✅ 저장 완료: 566_우리은행_세이프e구매자금대출.txt
✅ 저장 완료: 567_우리은행_세이프e구매카드대출.txt
✅ 저장 완료: 568_우리은행_소상공인119Plus당행대환.txt
✅ 저장 완료: 569_우리은행_우리ESG혁신기업대출.txt
✅ 저장 완료: 570_우리은행_우리SGI협약운전자금대출.txt
✅ 저장 완료: 571_우리은행_우리신성장동력대출.txt
✅ 저장 완료: 572_우리은행_우리중진공투게더론.txt
✅ 저장 완료: 573_우리은행_우리프랜차이즈론.txt
✅ 저장 완료: 574_우리은행_우리프리미엄비즈센터론.txt
✅ 저장 완료: 575_우리은행_우리CUBE론IP.txt
✅ 저장 완료: 576_우리은행_우리CUBE론X수출기업.txt
✅ 저장 완료: 577_우리은행_우리WON사장님담보대출.txt
✅ 저장 완료: 578_우리은행_우리드림카대출상용차.txt

### 리스트 없이 줄글 형식

In [ ]:
import json
import os
import re
from typing import Union, List

# 값 누락 확인
def is_missing(value: Union[str, List]) -> bool:
    if value is None:
        return True
    if isinstance(value, str) and value.strip() == "-":
        return True
    return False

# 파일명 안전하게 정리
def sanitize_filename(s: str) -> str:
    s = re.sub(r"[^\w가-힣]", "", s)
    return s[:30]

# 대출부대비용 등 일반 리스트 → 문장 처리
def format_list_to_sentences(items: List[str]) -> List[str]:
    formatted = []
    for item in items:
        item = item.lstrip("-").strip()
        if ":" in item:
            key, value = item.split(":", 1)
            sentence = f"{key.strip()}는 {value.strip()}"
        else:
            sentence = item

        if sentence.endswith("니다.") or sentence.endswith("다."):
            formatted.append(sentence)
        else:
            formatted.append(sentence + "입니다.")
    return formatted

# 중도상환 수수료 특수 처리
def format_prepayment_fee_sentences(items: List[str]) -> List[str]:
    result = []
    for item in items:
        item = item.strip()
        if any(op in item for op in ["X", "x", "÷", "*", "="]):
            result.append(f'"{item}"으로 계산됩니다.')
        elif "최장" in item or "발생" in item:
            result.append(item if item.endswith("다.") else item + "합니다.")
        elif "수수료율" in item:
            result.append("수수료율은 다음과 같습니다.")
        elif item.startswith("-"):
            try:
                title, value = item.lstrip("-").strip().split(":", 1)
                result.append(f"{title.strip()}의 수수료율은 {value.strip()}입니다.")
            except ValueError:
                sentence = item.lstrip("-").strip()
                result.append(sentence if sentence.endswith("니다.") or sentence.endswith("다.") else sentence + "입니다.")
        else:
            result.append(item if item.endswith("니다.") or item.endswith("다.") else item + "입니다.")
    return result

# 전체 상품 정보를 문장으로 변환
def convert_loan_json_to_text(data):
    lines = [f"{data['금융회사']}에서 '{data['상품명']}' 상품을 제공합니다."]
    lines.append(f"자금용도는 {data['자금용도']}입니다.")
    lines.append(f"대출 종류는 {data['대출종류']}입니다.")
    lines.append(f"금리 방식은 {data['금리방식']}입니다.")
    lines.append(f"상환 방식은 {data['상환방식']}입니다.")
    lines.append(f"가입 대상은 {data['가입대상']}입니다.")

    if not is_missing(data.get("가입대상 세부요건")):
        lines.append(f"구체적인 가입 요건은 '{data['가입대상 세부요건']}'입니다.")

    if not is_missing(data.get("전월 평균금리")):
        lines.append(f"전월 평균금리는 {data['전월 평균금리']}입니다.")
    else:
        lines.append("전월 평균금리는 제공되지 않았습니다.")

    if isinstance(data.get("적용가능 금리"), list) and len(data["적용가능 금리"]) == 2:
        최고금리 = data["적용가능 금리"][0].split(": ")[1]
        최저금리 = data["적용가능 금리"][1].split(": ")[1]
        lines.append(f"적용 가능 금리는 최고 {최고금리}, 최저 {최저금리}입니다.")

    if not is_missing(data.get("대출한도")):
        lines.append(f"대출 한도는 {data['대출한도']}입니다.")

    if not is_missing(data.get("우대금리")):
        lines.append(f"우대금리는 {data['우대금리']}입니다.")

    if not is_missing(data.get("가입방법")):
        lines.append(f"가입은 {data['가입방법']}을 통해 가능합니다.")

    수수료 = data.get("중도상환 수수료")
    if 수수료 and not is_missing(수수료):
        lines.append("중도상환 수수료는 다음과 같습니다.")
        if isinstance(수수료, list):
            lines.extend(format_prepayment_fee_sentences(수수료))
        else:
            lines.append(f"{수수료}입니다.")

    비용 = data.get("대출부대비용")
    if 비용 and not is_missing(비용):
        lines.append("대출 부대비용은 다음과 같습니다.")
        if isinstance(비용, list):
            lines.extend(format_list_to_sentences(비용))
        else:
            lines.append(f"{비용} 등이 포함됩니다.")

    연체 = data.get("연체이자율")
    if 연체 and not is_missing(연체):
        if isinstance(연체, list):
            lines.append(f"연체 이자율은 {' '.join(연체)}입니다.")
        else:
            lines.append(f"연체 이자율은 {연체}입니다.")

    담당 = data.get("담당부서 및 연락처")
    if 담당 and not is_missing(담당):
        lines.append("담당 부서 및 연락처는 다음과 같습니다.")
        if isinstance(담당, list):
            for d in 담당:
                d = d.strip()
                if d.endswith("니다.") or d.endswith("다."):
                    lines.append(d)
                else:
                    lines.append(f"{d}입니다.")
        else:
            d = 담당.strip()
            if d.endswith("니다.") or d.endswith("다."):
                lines.append(d)
            else:
                lines.append(f"{d}입니다.")

    return "\n".join(lines)

# 실행 함수
def process_json_to_text(input_json_path, output_dir):
    with open(input_json_path, "r", encoding="utf-8") as f:
        items = json.load(f)

    os.makedirs(output_dir, exist_ok=True)

    for idx, item in enumerate(items, start=1):
        금융회사 = sanitize_filename(item.get("금융회사", "unknown"))
        상품명 = sanitize_filename(item.get("상품명", f"상품_{idx}"))
        filename = f"{str(idx).zfill(3)}_{금융회사}_{상품명}.txt"
        filepath = os.path.join(output_dir, filename)

        text = convert_loan_json_to_text(item)

        with open(filepath, "w", encoding="utf-8") as out:
            out.write(text)

        print(f"✅ 저장 완료: {filename}")

# 실행 예시
process_json_to_text("금융상품한눈에.json", "금융상품_chunks")

✅ 저장 완료: 001_국민은행_KB동반성장협약상생대출.txt
✅ 저장 완료: 002_농협은행주식회사_채움상생론.txt
✅ 저장 완료: 003_우리은행_우리CUBE론XBIZ프라임.txt
✅ 저장 완료: 004_중소기업은행_IBK일자리Plus대출.txt
✅ 저장 완료: 005_농협은행주식회사_NH산업단지대출.txt
✅ 저장 완료: 006_주식회사케이뱅크_사장님부동산담보대출.txt
✅ 저장 완료: 007_농협은행주식회사_행복채움프랜차이즈론.txt
✅ 저장 완료: 008_중소기업은행_중기부RD사업화자금대출.txt
✅ 저장 완료: 009_우리은행_우리CUBE론X우리자산신탁.txt
✅ 저장 완료: 010_국민은행_KB우량산업단지기업우대대출.txt
✅ 저장 완료: 011_중소기업은행_IBK스마트공장지원대출.txt
✅ 저장 완료: 012_중소기업은행_IBK시설투자대출.txt
✅ 저장 완료: 013_중소기업은행_동반성장협력대출.txt
✅ 저장 완료: 014_중소기업은행_ESG경영성공지원시설자금대출.txt
✅ 저장 완료: 015_한국스탠다드차타드은행_비즈니스모기지Mortgage.txt
✅ 저장 완료: 016_국민은행_KB더드림TheDream소호대출.txt
✅ 저장 완료: 017_국민은행_KB유망분야성장기업우대대출.txt
✅ 저장 완료: 018_농협은행주식회사_중소기업보증료지원대출.txt
✅ 저장 완료: 019_중소기업은행_IBK혁신창업대출.txt
✅ 저장 완료: 020_국민은행_KB일사천리소호대출.txt
✅ 저장 완료: 021_국민은행_기업일반시설자금대출.txt
✅ 저장 완료: 022_중소기업은행_첨단기술기업육성자금대출.txt
✅ 저장 완료: 023_중소기업은행_IBK문화콘텐츠대출.txt
✅ 저장 완료: 024_우리은행_우리CUBE론X일반산업단지.txt
✅ 저장 완료: 025_농협은행주식회사_NH기업성장론_착한임대인우대임대사업자전용.txt
✅ 저장 완료: 026_수협은행_Sh전문직사업자파트너론.txt
✅ 저장 완료: 027_아이엠뱅크_무브온MoveOn특별대출.txt
✅ 저장 완료: 028_중소기업은행_e커머스소상공인성공보증부대출.txt
✅ 저장 완료: 029_농협은행주식회사_채움성공비즈니스대출.txt
✅ 저장 완료: 030_농협은행주식회사_NH기술평가우수기업대출.txt
✅ 저장 완료: 031_제주은행_전문직우대론.txt
✅ 저장 완료: 032_중소기업은행_IBK소상공인스마트화지원대출.txt
✅ 저장 완료: 033_중소기업은행_가치성장대출.txt
✅ 저장 완료: 034_아이엠뱅크_기업시설자금대출.txt
✅ 저장 완료: 035_아이엠뱅크_착한건물주특별대출.txt
✅ 저장 완료: 036_국민은행_KB투게더론.txt
✅ 저장 완료: 037_국민은행_KB모아드림론.txt
✅ 저장 완료: 038_중소기업은행_IBK성공창업대출.txt
✅ 저장 완료: 039_국민은행_기업일반운전자금대출.txt
✅ 저장 완료: 040_국민은행_KB커머셜모기지론.txt
✅ 저장 완료: 041_농협은행주식회사_NH다같이성장론.txt
✅ 저장 완료: 042_주식회사하나은행_파워메디론.txt
✅ 저장 완료: 043_농협은행주식회사_토지분양중도금대출.txt
✅ 저장 완료: 044_중소기업은행_IBK토지분양협약대출.txt
✅ 저장 완료: 045_국민은행_ONEKB기업우대대출.txt
✅ 저장 완료: 046_우리은행_우리동산채권담보대출.txt
✅ 저장 완료: 047_수협은행_New땡큐사장님대출.txt
✅ 저장 완료: 048_주식회사하나은행_HANA전문직소호대출.txt
✅ 저장 완료: 049_농협은행주식회사_NH기업성장론.txt
✅ 저장 완료: 050_아이엠뱅크_Techbiz테크비즈론.txt
✅ 저장 완료: 051_국민은행_KB상생결제론.txt
✅ 저장 완료: 052_국민은행_KB메디칼론.txt
✅ 저장 완료: 053_신한은행_신용보증재단특례보증대출재창업소상공인지원.txt
✅ 저장 완료: 054_신한은행_신용보증재단협약보증대출청년소상공인지원.txt
✅ 저장 완료: 055_중소기업은행_턴업기업지원자금대출.txt
✅ 저장 완료: 056_국민은행_KBGreenGrowthLoan.txt
✅ 저장 완료: 057_수협은행_Sh소호대출.txt
✅ 저장 완료: 058_주식회사하나은행_닥터클럽대출플래티늄.txt
✅ 저장 완료: 059_중소기업은행_무역금융.txt
✅ 저장 완료: 060_수협은행_부동산경락대금대출.txt
✅ 저장 완료: 061_중소기업은행_스마트동산담보대출.txt
✅ 저장 완료: 062_농협은행주식회사_이노메인비즈대출.txt
✅ 저장 완료: 063_아이엠뱅크_탑티어TopTier전문직사업자대출.txt
✅ 저장 완료: 064_농협은행주식회사_NH트러스트온보증대출.txt
✅ 저장 완료: 065_아이엠뱅크_기업운전자금대출.txt
✅ 저장 완료: 066_국민은행_KB우수기술기업TCB신용대출.txt
✅ 저장 완료: 067_국민은행_KB동반성장네트워크론AType.txt
✅ 저장 완료: 068_농협은행주식회사_NH농식품기업우대론.txt
✅ 저장 완료: 069_한국스탠다드차타드은행_보증서담보대출GIL.txt
✅ 저장 완료: 070_농협은행주식회사_NH농식품그린성장론.txt
✅ 저장 완료: 071_중소기업은행_해내리대출.txt
✅ 저장 완료: 072_신한은행_신용보증재단특례보증대출재창업소상공인지원분할상환.txt
✅ 저장 완료: 073_농협은행주식회사_기업구매자금대출.txt
✅ 저장 완료: 074_신한은행_신한온택트보증서대출.txt
✅ 저장 완료: 075_중소기업은행_IBK소상공인희망대출.txt
✅ 저장 완료: 076_국민은행_KBe구매자금대출.txt
✅ 저장 완료: 077_국민은행_기업일반통장자동대출.txt
✅ 저장 완료: 078_중소기업은행_iONE동반성장신용대출.txt
✅ 저장 완료: 079_중소기업은행_B2B팩토링.txt
✅ 저장 완료: 080_중소기업은행_트러스트온보증부대출.txt
✅ 저장 완료: 081_우리은행_우리상생파트너론.txt
✅ 저장 완료: 082_농협은행주식회사_전자방식외상매출채권담보대출.txt
✅ 저장 완료: 083_신한은행_강원신용보증재단특례보증대출.txt
✅ 저장 완료: 084_제주은행_기술평가우수기업대출.txt
✅ 저장 완료: 085_중소기업은행_원자재가격부담완화지원대출.txt
✅ 저장 완료: 086_중소기업은행_BOX개인사업자신용대출.txt
✅ 저장 완료: 087_농협은행주식회사_NH기업성공대출.txt
✅ 저장 완료: 088_중소기업은행_클린플러스보증부대출.txt
✅ 저장 완료: 089_국민은행_KB프랜차이즈대출.txt
✅ 저장 완료: 090_광주은행_KJBSOLARLOAN.txt
✅ 저장 완료: 091_우리은행_B2BPLUS대출.txt
✅ 저장 완료: 092_중소기업은행_소상공인초장기분할상환특별대출.txt
✅ 저장 완료: 093_국민은행_외상매출채권전자대출순구매방식.txt
✅ 저장 완료: 094_국민은행_KB공급망밸류업대출.txt
✅ 저장 완료: 095_중소기업은행_복합위기극복지원대출.txt
✅ 저장 완료: 096_국민은행_유형자산담보대출.txt
✅ 저장 완료: 097_우리은행_우리메디플러스론.txt
✅ 저장 완료: 098_우리은행_B2B대출.txt
✅ 저장 완료: 099_중소기업은행_소부장혁신지원대출.txt
✅ 저장 완료: 100_광주은행_비즈니스파트너론.txt
✅ 저장 완료: 101_수협은행_Sh숙박사업자파트너론.txt
✅ 저장 완료: 102_신한은행_신한사업자대출IN네이버페이.txt
✅ 저장 완료: 103_제주은행_JJB가맹점우대론.txt
✅ 저장 완료: 104_국민은행_외상매출채권전자대출역구매방식.txt
✅ 저장 완료: 105_국민은행_KB셀러론.txt
✅ 저장 완료: 106_국민은행_KB더드림TheDream소호신용대출.txt
✅ 저장 완료: 107_삼성생명보험주식회사_상업용부동산담보대출.txt
✅ 저장 완료: 108_농협은행주식회사_SOHO가맹점주우대대출.txt
✅ 저장 완료: 109_국민은행_전문직사업자우대대출.txt
✅ 저장 완료: 110_광주은행_기업튼튼보증서대출.txt
✅ 저장 완료: 111_수협은행_토지분양자금대출.txt
✅ 저장 완료: 112_국민은행_전자채권담보대출.txt
✅ 저장 완료: 113_국민은행_KB지식산업센터중도금대출.txt
✅ 저장 완료: 114_국민은행_KB구매론.txt
✅ 저장 완료: 115_국민은행_KB소상공인신용대출.txt
✅ 저장 완료: 116_농협은행주식회사_EZ구매론.txt
✅ 저장 완료: 117_수협은행_기업운전자금대출.txt
✅ 저장 완료: 118_아이엠뱅크_상업어음할인.txt
✅ 저장 완료: 119_국민은행_협약에의한토지분양자금대출.txt
✅ 저장 완료: 120_신한은행_신한사업자대출INSOL.txt
✅ 저장 완료: 121_신한은행_신한사업자대출IN토스.txt
✅ 저장 완료: 122_국민은행_KB상생플러스론AType.txt
✅ 저장 완료: 123_우리은행_우리사장님대출.txt
✅ 저장 완료: 124_제주은행_태양광발전사업자대출.txt
✅ 저장 완료: 125_중소기업은행_기업회전대출.txt
✅ 저장 완료: 126_삼성화재해상보험주식회사_삼성소호아파트.txt
✅ 저장 완료: 127_중소기업은행_해양수산기술사업화자금.txt
✅ 저장 완료: 128_수협은행_기업시설자금대출.txt
✅ 저장 완료: 129_광주은행_비즈니스아파트론.txt
✅ 저장 완료: 130_농협은행주식회사_NH메디칼론.txt
✅ 저장 완료: 131_비엠더블유파이낸셜서비스코리아_재고금융A.txt
✅ 저장 완료: 132_중소기업은행_수시로대출.txt
✅ 저장 완료: 133_주식회사케이뱅크_사장님신용대출.txt
✅ 저장 완료: 134_주식회사하나은행_프랜차이즈가맹점대출.txt
✅ 저장 완료: 135_제주은행_JJB부동산담보대출.txt
✅ 저장 완료: 136_중소기업은행_롯데마트패밀리론.txt
✅ 저장 완료: 137_신한은행_신한사업자대출INSOL분할상환.txt
✅ 저장 완료: 138_신한은행_신한사업자대출IN토스분할상환.txt
✅ 저장 완료: 139_농협은행주식회사_NH지식산업센터중도금대출.txt
✅ 저장 완료: 140_수협은행_집단주택자금대출.txt
✅ 저장 완료: 141_중소기업은행_싸이클론.txt
✅ 저장 완료: 142_중소기업은행_iONE가맹점성공대출.txt
✅ 저장 완료: 143_아이엠뱅크_iM으뜸사장님특별대출.txt
✅ 저장 완료: 144_농협은행주식회사_B2B구매자금대출.txt
✅ 저장 완료: 145_국민은행_KB소호신용대출.txt
✅ 저장 완료: 146_중소기업은행_iONE소상공인대출.txt
✅ 저장 완료: 147_농협은행주식회사_채움중소기업우대론.txt
✅ 저장 완료: 148_제주은행_병원약국우대대출.txt
✅ 저장 완료: 149_신한은행_신한사업자대출IN네이버페이분할상환.txt
✅ 저장 완료: 150_국민은행_상업어음할인.txt
✅ 저장 완료: 151_모아저축은행_부동산담보대출.txt
✅ 저장 완료: 152_중소기업은행_B2B구매자금대출.txt
✅ 저장 완료: 153_중소기업은행_네트워크론.txt
✅ 저장 완료: 154_현대커머셜_현대자동차신차할부.txt
✅ 저장 완료: 155_농협은행주식회사_NH베스트닥터론.txt
✅ 저장 완료: 156_우리은행_파워브랜드가맹점창업대출.txt
✅ 저장 완료: 157_우리은행_우리동네사장님대출.txt
✅ 저장 완료: 158_중소기업은행_B2B전자구매론.txt
✅ 저장 완료: 159_국민은행_KB메가셀러론.txt
✅ 저장 완료: 160_국민은행_사장님마이너스통장.txt
✅ 저장 완료: 161_산은캐피탈_신차승용오토론.txt
✅ 저장 완료: 162_중소기업은행_기업구매자금대출.txt
✅ 저장 완료: 163_중소기업은행_전자채권담보대출.txt
✅ 저장 완료: 164_농협은행주식회사_유형자산담보대출.txt
✅ 저장 완료: 165_중소기업은행_조달청제휴네트워크론.txt
✅ 저장 완료: 166_주식회사카카오뱅크_개인사업자신용대출.txt
✅ 저장 완료: 167_하나캐피탈_정상오토론.txt
✅ 저장 완료: 168_엔에이치농협캐피탈_할부수입상용1.txt
✅ 저장 완료: 169_중소기업은행_할인어음.txt
✅ 저장 완료: 170_신한은행_신한프랜차이즈론분할상환운전자금.txt
✅ 저장 완료: 171_우리은행_협력기업상생대출.txt
✅ 저장 완료: 172_중소기업은행_외화대출.txt
✅ 저장 완료: 173_농협은행주식회사_네트워크론.txt
✅ 저장 완료: 174_아산저축은행_일반자금대출.txt
✅ 저장 완료: 175_중소기업은행_전자방식외상매출채권담보대출.txt
✅ 저장 완료: 176_흥국화재해상보험주식회사_2502흥국SOHO아파트대출.txt
✅ 저장 완료: 177_아이엠뱅크_기업통장대출.txt
✅ 저장 완료: 178_케이비캐피탈_수입신차.txt
✅ 저장 완료: 179_중소기업은행_협동조합B2B구매카드대출.txt
✅ 저장 완료: 180_엔에이치농협캐피탈_할부수입상용2.txt
✅ 저장 완료: 181_중소기업은행_공공구매론.txt
✅ 저장 완료: 182_엔에이치농협캐피탈_사료구매자금대출.txt
✅ 저장 완료: 183_현대커머셜_부동산PF.txt
✅ 저장 완료: 184_엔에이치농협캐피탈_국내상용론1.txt
✅ 저장 완료: 185_엔에이치농협캐피탈_할부특장.txt
✅ 저장 완료: 186_비엔케이캐피탈_신차승용구매담보대출.txt
✅ 저장 완료: 187_현대커머셜_현대자동차신차특장차할부.txt
✅ 저장 완료: 188_중소기업은행_한전파워에너지론.txt
✅ 저장 완료: 189_엔에이치농협캐피탈_할부건설기계.txt
✅ 저장 완료: 190_현대커머셜_HD현대건설기계신차건설기계할부.txt
✅ 저장 완료: 191_우리은행_우리카드가맹점우대대출.txt
✅ 저장 완료: 192_신한은행_땡겨요사업자대출.txt
✅ 저장 완료: 193_아이엠캐피탈_장비대출_신차화물중소형.txt
✅ 저장 완료: 194_비엠더블유파이낸셜서비스코리아_재고금융B.txt
✅ 저장 완료: 195_대신저축은행_부동산담보대출.txt
✅ 저장 완료: 196_토스뱅크주식회사_사장님신용대출.txt
✅ 저장 완료: 197_아이엠캐피탈_장비대출_신차건기.txt
✅ 저장 완료: 198_롯데캐피탈_운영자금오토론.txt
✅ 저장 완료: 199_비엔케이캐피탈_자동차재고금융대출.txt
✅ 저장 완료: 200_농협은행주식회사_NHe사장님바로대출.txt
✅ 저장 완료: 201_엔에이치농협캐피탈_특장론2.txt
✅ 저장 완료: 202_아이엠캐피탈_장비대출_신차화물대형.txt
✅ 저장 완료: 203_현대해상화재보험주식회사_현대해상사업자론아파트.txt
✅ 저장 완료: 204_현대커머셜_HD현대건설기계신차건설기계어태치포함형할부.txt
✅ 저장 완료: 205_엔에이치농협캐피탈_건설기계론.txt
✅ 저장 완료: 206_아이엠캐피탈_신차오토론.txt
✅ 저장 완료: 207_케이비캐피탈_신차상용.txt
✅ 저장 완료: 208_농협은행주식회사_NH개인택시우대대출.txt
✅ 저장 완료: 209_엔에이치농협캐피탈_할부국내상용2.txt
✅ 저장 완료: 210_볼보파이낸셜서비스코리아_상용차론.txt
✅ 저장 완료: 211_볼보파이낸셜서비스코리아_상용차할부.txt
✅ 저장 완료: 212_현대커머셜_운영자금대출사료구매론.txt
✅ 저장 완료: 213_모아저축은행_중도금대출.txt
✅ 저장 완료: 214_키움예스저축은행_개인사업자아파트담보대출후순위만기일시.txt
✅ 저장 완료: 215_아이엠캐피탈_장비대출_신차버스일반.txt
✅ 저장 완료: 216_BNK저축은행_중도금대출비주택.txt
✅ 저장 완료: 217_엔에이치농협캐피탈_할부산업기계.txt
✅ 저장 완료: 218_엔에이치농협캐피탈_산업기계론.txt
✅ 저장 완료: 219_엔에이치농협캐피탈_주택사업자금대출선.txt
✅ 저장 완료: 220_현대커머셜_현대자동차신차트럭변동금리형할부.txt
✅ 저장 완료: 221_현대캐피탈_사업자프라임모기지론5년고정후순위.txt
✅ 저장 완료: 222_비엔케이캐피탈_산업재구입자금대출.txt
✅ 저장 완료: 223_오릭스캐피탈코리아_사업자담보대출.txt
✅ 저장 완료: 224_BNK저축은행_BNK아파트사업자금대출.txt
✅ 저장 완료: 225_제이비우리캐피탈_중고승용재고금융.txt
✅ 저장 완료: 226_푸른저축은행_부동산담보대출.txt
✅ 저장 완료: 227_하나저축은행_기타부동산담보대출.txt
✅ 저장 완료: 228_엔에이치농협캐피탈_할부국내상용1.txt
✅ 저장 완료: 229_우리은행_우리은행네이버스마트스토어대출.txt
✅ 저장 완료: 230_우리은행_우리은행네이버스마트플레이스대출.txt
✅ 저장 완료: 231_한국캐피탈_재고금융.txt
✅ 저장 완료: 232_현대캐피탈_사업자프라임모기지론5년고정1순위.txt
✅ 저장 완료: 233_현대커머셜_동해기계항공신차특장차할부.txt
✅ 저장 완료: 234_진주저축은행_부동산담보대출.txt
✅ 저장 완료: 235_진주저축은행_전문직마스터론.txt
✅ 저장 완료: 236_토스뱅크주식회사_사장님마이너스통장.txt
✅ 저장 완료: 237_현대커머셜_HD현대사이트솔루션신차건설기계할부.txt
✅ 저장 완료: 238_볼보파이낸셜서비스코리아_건설기계론.txt
✅ 저장 완료: 239_볼보파이낸셜서비스코리아_건설기계할부.txt
✅ 저장 완료: 240_케이비캐피탈_재고금융.txt
✅ 저장 완료: 241_아산저축은행_종합통장대출.txt
✅ 저장 완료: 242_한국투자저축은행_숙박시설지원자금대출.txt
✅ 저장 완료: 243_신한은행_신한프랜차이즈론운전자금.txt
✅ 저장 완료: 244_우리은행_우리Oh5클릭대출.txt
✅ 저장 완료: 245_오릭스캐피탈코리아_재고금융.txt
✅ 저장 완료: 246_삼호저축은행_햇살론.txt
✅ 저장 완료: 247_진주저축은행_지분론.txt
✅ 저장 완료: 248_평택저축은행_주택담보대출아파트외.txt
✅ 저장 완료: 249_오릭스캐피탈코리아_승용신차일반대출.txt
✅ 저장 완료: 250_현대캐피탈_사업자프라임모기지론후순위.txt
✅ 저장 완료: 251_하나캐피탈_제휴파트너론중고차.txt
✅ 저장 완료: 252_엔에이치농협캐피탈_주택사업자금대출후.txt
✅ 저장 완료: 253_하나캐피탈_디지털중고차론.txt
✅ 저장 완료: 254_키움예스저축은행_개인사업자부동산담보대출.txt
✅ 저장 완료: 255_애큐온저축은행_아파트후순위대출.txt
✅ 저장 완료: 256_산은캐피탈_중고상용오토론.txt
✅ 저장 완료: 257_하나캐피탈_재고금융ll특화중고차.txt
✅ 저장 완료: 258_비엔케이캐피탈_신차상용구매담보대출.txt
✅ 저장 완료: 259_하나캐피탈_재고금융중고차.txt
✅ 저장 완료: 260_아이비케이캐피탈_부동산담보대출.txt
✅ 저장 완료: 261_데라게란덴_시설자금대출.txt
✅ 저장 완료: 262_우리금융캐피탈_우리금융캐피탈모기지론사업자금_고정_수도권.txt
✅ 저장 완료: 263_주식회사하나은행_개인사업자장기분할상환.txt
✅ 저장 완료: 264_롯데캐피탈_오토론.txt
✅ 저장 완료: 265_현대캐피탈_사업자프라임모기지론1순위.txt
✅ 저장 완료: 266_아이엠캐피탈_인수금대출.txt
✅ 저장 완료: 267_한국투자저축은행_부동산담보대출.txt
✅ 저장 완료: 268_알씨아이파이낸셜서비스코리아_재고금융인벤토리론.txt
✅ 저장 완료: 269_하나캐피탈_재고금융ll중고차.txt
✅ 저장 완료: 270_아이엠캐피탈_장비대출건설기계중고구매.txt
✅ 저장 완료: 271_메리츠캐피탈_건설장비기계개인사업자대출.txt
✅ 저장 완료: 272_페퍼저축은행_건설기계구입자금대출종합통장대출.txt
✅ 저장 완료: 273_한국자산캐피탈_일반자금대출.txt
✅ 저장 완료: 274_하나캐피탈_개인사업자아파트담보대출.txt
✅ 저장 완료: 275_아이엠캐피탈_장비대출건설기계중고운영.txt
✅ 저장 완료: 276_에코캐피탈_개인사업자신용대출기타보증대출.txt
✅ 저장 완료: 277_아이엠캐피탈_장비대출건설기계신품.txt
✅ 저장 완료: 278_한국투자저축은행_사업자아파트담보대출.txt
✅ 저장 완료: 279_현대커머셜_현대커머셜신차론.txt
✅ 저장 완료: 280_유안타저축은행_유안타비즈론만기일시.txt
✅ 저장 완료: 281_롯데카드_건설기계담보대출.txt
✅ 저장 완료: 282_유안타저축은행_유안타비즈론원리금균등.txt
✅ 저장 완료: 283_한국캐피탈_운전.txt
✅ 저장 완료: 284_비엔케이캐피탈_사업자금대출.txt
✅ 저장 완료: 285_케이비캐피탈_운영자금.txt
✅ 저장 완료: 286_페퍼저축은행_페퍼비즈니스론.txt
✅ 저장 완료: 287_비엠더블유파이낸셜서비스코리아_재고금융C.txt
✅ 저장 완료: 288_엠지캐피탈_주택담보대출.txt
✅ 저장 완료: 289_페퍼저축은행_건설기계담보대출일반자금대출.txt
✅ 저장 완료: 290_신한저축은행_사업자아파트담보대출.txt
✅ 저장 완료: 291_현대커머셜_현대커머셜신차특장차론.txt
✅ 저장 완료: 292_애큐온저축은행_건설기계담보대출크레인.txt
✅ 저장 완료: 293_오릭스캐피탈코리아_건설장비담보대출.txt
✅ 저장 완료: 294_OK저축은행_OK모기지론.txt
✅ 저장 완료: 295_엔에이치농협캐피탈_NH특수장비론1.txt
✅ 저장 완료: 296_신한은행_소상공인상생매일땡겨드림대출.txt
✅ 저장 완료: 297_안양저축은행_종합통장대출.txt
✅ 저장 완료: 298_엠지캐피탈_기타담보.txt
✅ 저장 완료: 299_롯데캐피탈_건설기계론.txt
✅ 저장 완료: 300_안양저축은행_일반자금대출.txt
✅ 저장 완료: 301_애큐온캐피탈_Captive산업차량.txt
✅ 저장 완료: 302_애큐온저축은행_건설기계구입대출크레인.txt
✅ 저장 완료: 303_엔에이치농협캐피탈_NH산업재론.txt
✅ 저장 완료: 304_현대커머셜_현대커머셜중고크레인구입론.txt
✅ 저장 완료: 305_농협은행주식회사_NH지식재산권IP담보대출.txt
✅ 저장 완료: 306_트라톤파이낸셜서비스코리아_일반대출.txt
✅ 저장 완료: 307_고려저축은행_사업자후순위부동산담보대출.txt
✅ 저장 완료: 308_아이엠캐피탈_장비대출산업기계재고금융.txt
✅ 저장 완료: 309_아이엠캐피탈_장비대출중고건기상용구매.txt
✅ 저장 완료: 310_인천저축은행_이동형크레인담보대출.txt
✅ 저장 완료: 311_비엔케이캐피탈_중고상용구매담보대출.txt
✅ 저장 완료: 312_애큐온캐피탈_Commercial기업대출.txt
✅ 저장 완료: 313_국민은행_KB매출더하기론통합플랫폼.txt
✅ 저장 완료: 314_OK저축은행_사업자후순위아파트OK론.txt
✅ 저장 완료: 315_현대커머셜_현대커머셜중고크레인담보론.txt
✅ 저장 완료: 316_오릭스캐피탈코리아_중고승용담보대출.txt
✅ 저장 완료: 317_케이비캐피탈_중고상용.txt
✅ 저장 완료: 318_도이치파이낸셜_재고금융.txt
✅ 저장 완료: 319_메리츠캐피탈_의료인사업자대출.txt
✅ 저장 완료: 320_비엔케이캐피탈_중고승용구매담보대출.txt
✅ 저장 완료: 321_애큐온캐피탈_NonCaptive건설기계.txt
✅ 저장 완료: 322_오릭스캐피탈코리아_대형상용담보대출.txt
✅ 저장 완료: 323_국민은행_KB메가셀러론글로벌.txt
✅ 저장 완료: 324_하나캐피탈_리텐션론.txt
✅ 저장 완료: 325_한국캐피탈_중고상용.txt
✅ 저장 완료: 326_웰컴저축은행_웰컴부동산하이브리드.txt
✅ 저장 완료: 327_한국캐피탈_중고승용.txt
✅ 저장 완료: 328_아이엠캐피탈_장비대출중고건기상용대환운영.txt
✅ 저장 완료: 329_메리츠캐피탈_국산중고개인사업자대출수입중고개인사업자대출.txt
✅ 저장 완료: 330_애큐온캐피탈_주택담보대출후순위.txt
✅ 저장 완료: 331_메리츠캐피탈_중고상용차오토론.txt
✅ 저장 완료: 332_고려저축은행_메디칼론.txt
✅ 저장 완료: 333_OSB저축은행_오비즈론신잔액COFIXPA5.txt
✅ 저장 완료: 334_대백저축은행_외상채권비어음선취.txt
✅ 저장 완료: 335_대백저축은행_할인어음상업어음.txt
✅ 저장 완료: 336_웰컴저축은행_웰컴사업자아파트대출.txt
✅ 저장 완료: 337_OSB저축은행_오비즈론신잔액COFIXIO3PA2.txt
✅ 저장 완료: 338_제이비우리캐피탈_중고승용구입대출.txt
✅ 저장 완료: 339_안양저축은행_할인어음.txt
✅ 저장 완료: 340_한국투자캐피탈_자산플러스론.txt
✅ 저장 완료: 341_애큐온캐피탈_Captive건설기계.txt
✅ 저장 완료: 342_비엠더블유파이낸셜서비스코리아_재고금융D.txt
✅ 저장 완료: 343_현대커머셜_중고다이렉트담보론사전한도추가일반.txt
✅ 저장 완료: 344_케이비캐피탈_중고차대출.txt
✅ 저장 완료: 345_애큐온캐피탈_NonCaptive상용차.txt
✅ 저장 완료: 346_현대커머셜_중고다이렉트담보론사전한도리스케줄일반.txt
✅ 저장 완료: 347_키움예스저축은행_음악저작권담보대출.txt
✅ 저장 완료: 348_현대커머셜_중고다이렉트추가담보론중고연계.txt
✅ 저장 완료: 349_현대커머셜_중고다이렉트담보론사전한도종료일반.txt
✅ 저장 완료: 350_현대커머셜_중고다이렉트일반담보론.txt
✅ 저장 완료: 351_현대커머셜_중고다이렉트담보론추가일반신차연계.txt
✅ 저장 완료: 352_애큐온캐피탈_주택담보대출선순위.txt
✅ 저장 완료: 353_현대커머셜_중고다이렉트구입론.txt
✅ 저장 완료: 354_케이비캐피탈_중고차할부.txt
✅ 저장 완료: 355_제이비우리캐피탈_중고승용세이빙카.txt
✅ 저장 완료: 356_현대커머셜_중고다이렉트담보론리스케줄신차연계.txt
✅ 저장 완료: 357_현대커머셜_현대커머셜중고담보론.txt
✅ 저장 완료: 358_현대커머셜_현대커머셜중고구입론.txt
✅ 저장 완료: 359_현대커머셜_중고다이렉트추가담보론중고연계.txt
✅ 저장 완료: 360_제이비우리캐피탈_중고승용할부구입대출.txt
✅ 저장 완료: 361_현대커머셜_개인사업자신용대출.txt
✅ 저장 완료: 362_한국캐피탈_소매담보.txt
✅ 저장 완료: 363_웰컴저축은행_웰컴PC론.txt
✅ 저장 완료: 364_아이엠캐피탈_SOHO아파트론.txt
✅ 저장 완료: 365_제이비우리캐피탈_주택담보생활자금대출.txt
✅ 저장 완료: 366_케이비캐피탈_신용대출.txt
✅ 저장 완료: 367_하나캐피탈_행복아파트론.txt
✅ 저장 완료: 368_하나캐피탈_원큐자동차담보대출.txt
✅ 저장 완료: 369_하나캐피탈_추가대출.txt
✅ 저장 완료: 370_아이엠캐피탈_연계오토담보론.txt
✅ 저장 완료: 371_아이엠캐피탈_리치론.txt
✅ 저장 완료: 372_하나캐피탈_원큐자동차담보대출대환.txt
✅ 저장 완료: 373_아이엠캐피탈_연계중금리론.txt
✅ 저장 완료: 374_하나캐피탈_XSELL론.txt
✅ 저장 완료: 375_우리금융캐피탈_사업자아파트신용대출인다이렉트.txt
✅ 저장 완료: 376_케이비국민카드_KB국민개인사업자대출.txt
✅ 저장 완료: 377_비씨카드_BC카드가맹점대출.txt
✅ 저장 완료: 378_미래에셋캐피탈_스마트스토어대출.txt
✅ 저장 완료: 379_상상인플러스저축은행_오토론.txt
✅ 저장 완료: 380_한국투자캐피탈_자산플러스론.txt
✅ 저장 완료: 381_한국투자캐피탈_오토플러스론.txt
✅ 저장 완료: 382_우리카드_개인사업자신용대출.txt
✅ 저장 완료: 383_아이엠캐피탈_아파트론1.txt
✅ 저장 완료: 384_다올저축은행_Fi사업자Npay.txt
✅ 저장 완료: 385_아이엠캐피탈_오토담보론.txt
✅ 저장 완료: 386_우리금융캐피탈_우수고객_추가대출개인사업자.txt
✅ 저장 완료: 387_우리금융캐피탈_사업자자산론인다이렉트.txt
✅ 저장 완료: 388_페퍼저축은행_GREENE오토론사업자선순위.txt
✅ 저장 완료: 389_다올저축은행_Fi사업자toss.txt
✅ 저장 완료: 390_우리금융캐피탈_사업자자산론다이렉트.txt
✅ 저장 완료: 391_우리금융캐피탈_우수고객_추가대출개인사업자.txt
✅ 저장 완료: 392_다올저축은행_Fi사업자B.txt
✅ 저장 완료: 393_제이비우리캐피탈_개인신용대출.txt
✅ 저장 완료: 394_삼호저축은행_예쓰론C자동차담보대출.txt
✅ 저장 완료: 395_웰컴저축은행_웰컴희망대출.txt
✅ 저장 완료: 396_도이치파이낸셜_오토담보론.txt
✅ 저장 완료: 397_웰컴저축은행_웰컴자동차담보대출.txt
✅ 저장 완료: 398_한국캐피탈_신용.txt
✅ 저장 완료: 399_제이비우리캐피탈_자동차담보대출.txt
✅ 저장 완료: 400_페퍼저축은행_오토담보론사업자.txt
✅ 저장 완료: 401_비엔케이캐피탈_신용대출PLUS.txt
✅ 저장 완료: 402_한국캐피탈_오토담보.txt
✅ 저장 완료: 403_제이비우리캐피탈_자산론.txt
✅ 저장 완료: 404_한성저축은행_가맹점대출.txt
✅ 저장 완료: 405_한성저축은행_성업대출.txt
✅ 저장 완료: 406_웰컴저축은행_웰컴뱅크론.txt
✅ 저장 완료: 407_마스턴캐피탈_사업자담보대출.txt
✅ 저장 완료: 408_아이비케이캐피탈_기업어음할인.txt
✅ 저장 완료: 409_아이비케이캐피탈_기업자금대출.txt
✅ 저장 완료: 410_아이비케이캐피탈_리스금융.txt
✅ 저장 완료: 411_아이비케이캐피탈_비대면팩토링.txt
✅ 저장 완료: 412_아이비케이캐피탈_팩토링.txt
✅ 저장 완료: 413_아이비케이캐피탈_할부대출건설기계.txt
✅ 저장 완료: 414_아이비케이캐피탈_할부대출상용차.txt
✅ 저장 완료: 415_아이엠캐피탈_개인사업자대상기업일반대출담보.txt
✅ 저장 완료: 416_아이엠캐피탈_개인사업자대상기업일반대출신용.txt
✅ 저장 완료: 417_아이엠캐피탈_다이렉트아파트론.txt
✅ 저장 완료: 418_에이치비캐피탈_사업자신용대출.txt
✅ 저장 완료: 419_광주은행_기술창조우수기업대출.txt
✅ 저장 완료: 420_광주은행_메디컬파트너론.txt
✅ 저장 완료: 421_광주은행_사회적경제기업SUPPORT_LOAN.txt
✅ 저장 완료: 422_광주은행_센트럴요양원대출.txt
✅ 저장 완료: 423_광주은행_쏠쏠센트럴비즈론.txt
✅ 저장 완료: 424_광주은행_특화산업단지대출.txt
✅ 저장 완료: 425_광주은행_포용금융특별대출.txt
✅ 저장 완료: 426_광주은행_ESGSUPPORTLOAN.txt
✅ 저장 완료: 427_광주은행_KJBTRUSTON보증서대출.txt
✅ 저장 완료: 428_광주은행_KJB동산담보대출.txt
✅ 저장 완료: 429_국민은행_기업당좌대출.txt
✅ 저장 완료: 430_국민은행_매출채권담보대출.txt
✅ 저장 완료: 431_국민은행_무역금융.txt
✅ 저장 완료: 432_국민은행_예부적금관계대출.txt
✅ 저장 완료: 433_국민은행_외화대출.txt
✅ 저장 완료: 434_국민은행_장기분할상환부동산담보대출.txt
✅ 저장 완료: 435_국민은행_재고자산담보대출.txt
✅ 저장 완료: 436_국민은행_B2BKB일석e조매출채권보험담보대출.txt
✅ 저장 완료: 437_국민은행_B2B공공기관하도급대금담보대출.txt
✅ 저장 완료: 438_국민은행_B2B동반성장매출채권담보대출.txt
✅ 저장 완료: 439_국민은행_KBBiz장기분할시설자금대출.txt
✅ 저장 완료: 440_국민은행_KBGreenWaveESG우수기업대출.txt
✅ 저장 완료: 441_국민은행_KB노란우산공제기업우대대출.txt
✅ 저장 완료: 442_국민은행_KB더드림지식재산IP담보대출.txt
✅ 저장 완료: 443_국민은행_KB미래성장기업우대대출.txt
✅ 저장 완료: 444_국민은행_KB민간협약토지분양자금대출.txt
✅ 저장 완료: 445_국민은행_KB사회적경제기업우대대출.txt
✅ 저장 완료: 446_국민은행_KB소규모주택사업자건설자금대출.txt
✅ 저장 완료: 447_국민은행_KB수출기업우대대출.txt
✅ 저장 완료: 448_국민은행_KB업무시설오피스중도금대출.txt
✅ 저장 완료: 449_국민은행_KB우수상권우대대출.txt
✅ 저장 완료: 450_국민은행_KB재해복구금융지원프로그램.txt
✅ 저장 완료: 451_국민은행_KB지식산업센터입주기업대출.txt
✅ 저장 완료: 452_국민은행_KB태양광발전사업자우대대출.txt
✅ 저장 완료: 453_국민은행_KB특화산업단지입주기업대출.txt
✅ 저장 완료: 454_국민은행_KB플러스론.txt
✅ 저장 완료: 455_국민은행_KB동반성장네트워크론BType.txt
✅ 저장 완료: 456_국민은행_KB상생플러스론BType.txt
✅ 저장 완료: 457_국제저축은행_일반자금대출.txt
✅ 저장 완료: 458_금화저축은행_개인사업자대출.txt
✅ 저장 완료: 459_농협은행주식회사_농축수산물담보대출.txt
✅ 저장 완료: 460_농협은행주식회사_매출채권담보대출.txt
✅ 저장 완료: 461_농협은행주식회사_어린이집대출.txt
✅ 저장 완료: 462_농협은행주식회사_재고자산담보대출.txt
✅ 저장 완료: 463_농협은행주식회사_전자채권담보대출.txt
✅ 저장 완료: 464_농협은행주식회사_NH모바일지자체협약대출.txt
✅ 저장 완료: 465_농협은행주식회사_NH모바일지자체협약대출경기보증재단.txt
✅ 저장 완료: 466_농협은행주식회사_NH스마트팜론.txt
✅ 저장 완료: 467_농협은행주식회사_NH일자리창업농식품기업우대대출.txt
✅ 저장 완료: 468_농협은행주식회사_NH한금우대론.txt
✅ 저장 완료: 469_다올저축은행_Fi비즈론.txt
✅ 저장 완료: 470_다올저축은행_Fi주식담보대출.txt
✅ 저장 완료: 471_다올저축은행_Fi주택담보대출.txt
✅ 저장 완료: 472_대명상호저축은행_사업자아파트월수분할.txt
✅ 저장 완료: 473_대명상호저축은행_사업자아파트월수일시.txt
✅ 저장 완료: 474_대백저축은행_공장담보대출월수일시.txt
✅ 저장 완료: 475_대백저축은행_기운일대월수일시.txt
✅ 저장 완료: 476_대백저축은행_기운종합통장대출.txt
✅ 저장 완료: 477_대백저축은행_상가담보대출월수분할.txt
✅ 저장 완료: 478_대백저축은행_상가담보대출월수일시.txt
✅ 저장 완료: 479_대백저축은행_자영업자주택담보대출월수일시.txt
✅ 저장 완료: 480_대백저축은행_토지담보대출월수일시.txt
✅ 저장 완료: 481_대신저축은행_대신비즈론.txt
✅ 저장 완료: 482_드림저축은행_기업신용대출월수일시.txt
✅ 저장 완료: 483_드림저축은행_기타부동산담보대출월수일시.txt
✅ 저장 완료: 484_드림저축은행_아파트담보대출사업자고정금리.txt
✅ 저장 완료: 485_디비캐피탈_사료대출.txt
✅ 저장 완료: 486_라온저축은행_일반자금대출.txt
✅ 저장 완료: 487_라온저축은행_일반자금대출.txt
✅ 저장 완료: 488_롯데캐피탈_신용대출.txt
✅ 저장 완료: 489_롯데캐피탈_자동차담보대출.txt
✅ 저장 완료: 490_리딩에이스캐피탈_사업자아파트담보대출.txt
✅ 저장 완료: 491_볼보파이낸셜서비스코리아_중고건설기계론.txt
✅ 저장 완료: 492_볼보파이낸셜서비스코리아_중고건설기계할부.txt
✅ 저장 완료: 493_볼보파이낸셜서비스코리아_중고상용차론.txt
✅ 저장 완료: 494_비엔케이캐피탈_건설기계장비담보대출.txt
✅ 저장 완료: 495_비엔케이캐피탈_신용대출.txt
✅ 저장 완료: 496_비엔케이캐피탈_제휴사운영자금대출.txt
✅ 저장 완료: 497_비엔케이캐피탈_제휴사임차보증금대출.txt
✅ 저장 완료: 498_삼성화재해상보험주식회사_삼성소호주택.txt
✅ 저장 완료: 499_삼호저축은행_일반자금대출부동산담보.txt
✅ 저장 완료: 500_삼호저축은행_일반자금대출신용.txt
✅ 저장 완료: 501_상상인저축은행_부동산담보대출.txt
✅ 저장 완료: 502_상상인저축은행_프로젝트파이낸싱.txt
✅ 저장 완료: 503_솔브레인저축은행_일반자금대출월수균등.txt
✅ 저장 완료: 504_솔브레인저축은행_일반자금대출월수분할.txt
✅ 저장 완료: 505_솔브레인저축은행_일반자금대출월수일시.txt
✅ 저장 완료: 506_솔브레인저축은행_종합통장대출.txt
✅ 저장 완료: 507_수협은행_고시원사업자대출.txt
✅ 저장 완료: 508_수협은행_냉동수산물담보대출.txt
✅ 저장 완료: 509_수협은행_더해드림론.txt
✅ 저장 완료: 510_수협은행_매입조건부주택건축자금대출.txt
✅ 저장 완료: 511_수협은행_상업어음할인.txt
✅ 저장 완료: 512_수협은행_예적금담보대출.txt
✅ 저장 완료: 513_수협은행_카마스터즈론.txt
✅ 저장 완료: 514_수협은행_B2B구매자금대출.txt
✅ 저장 완료: 515_수협은행_MY편의점대출.txt
✅ 저장 완료: 516_수협은행_ShESG우수기업대출.txt
✅ 저장 완료: 517_수협은행_Sh기술평가우수기업대출.txt
✅ 저장 완료: 518_수협은행_Sh서울시협약주택보증대출.txt
✅ 저장 완료: 519_수협은행_Sh신용보증서Plus대출.txt
✅ 저장 완료: 520_수협은행_Sh안전협약주택보증대출.txt
✅ 저장 완료: 521_수협은행_Sh창업기업지원보증서대출.txt
✅ 저장 완료: 522_수협은행_Sh특별출연협약보증대출.txt
✅ 저장 완료: 523_수협은행_Sh프라임주택건설보증대출.txt
✅ 저장 완료: 524_신한은행_신한프랜차이즈론분할상환시설자금.txt
✅ 저장 완료: 525_신한은행_신한프랜차이즈론시설자금.txt
✅ 저장 완료: 526_신한은행_신한프랜차이즈론종합통장대출.txt
✅ 저장 완료: 527_신한저축은행_사업자담보대출신한.txt
✅ 저장 완료: 528_신한저축은행_사업자신용대출신한.txt
✅ 저장 완료: 529_신한저축은행_참신한사업자론.txt
✅ 저장 완료: 530_신한캐피탈_일반기업대출.txt
✅ 저장 완료: 531_안국저축은행_일반자금대출월수균등.txt
✅ 저장 완료: 532_안국저축은행_일반자금대출월수일시.txt
✅ 저장 완료: 533_알씨아이파이낸셜서비스코리아_운영자금대출워킹캐피탈.txt
✅ 저장 완료: 534_애큐온저축은행_사업자신용대출셀러론.txt
✅ 저장 완료: 535_애큐온저축은행_아파트선순위대출.txt
✅ 저장 완료: 536_엔에이치농협캐피탈_국내상용론2.txt
✅ 저장 완료: 537_엔에이치농협캐피탈_국산오토론.txt
✅ 저장 완료: 538_엔에이치농협캐피탈_수입상용론1.txt
✅ 저장 완료: 539_엔에이치농협캐피탈_수입상용론2.txt
✅ 저장 완료: 540_엔에이치농협캐피탈_수입오토론.txt
✅ 저장 완료: 541_엔에이치저축은행_순수일반담보APT.txt
✅ 저장 완료: 542_엔에이치저축은행_순수일반담보기타.txt
✅ 저장 완료: 543_엔에이치저축은행_순수일반신용.txt
✅ 저장 완료: 544_엔에이치저축은행_일대프로젝트파이낸싱회전식.txt
✅ 저장 완료: 545_엔에이치저축은행_일반신용기타.txt
✅ 저장 완료: 546_엔에이치저축은행_일반자금대출회전식.txt
✅ 저장 완료: 547_엔에이치저축은행_종통프로젝트파이낸싱.txt
✅ 저장 완료: 548_엔에이치저축은행_종합통장대출.txt
✅ 저장 완료: 549_엔에이치저축은행_중도금대출회전식.txt
✅ 저장 완료: 550_엔에이치저축은행_하우징론.txt
✅ 저장 완료: 551_엔에이치저축은행_NH사업자행복대출.txt
✅ 저장 완료: 552_엔에이치저축은행_NH잔금대출.txt
✅ 저장 완료: 553_엔에이치저축은행_NH투게더론.txt
✅ 저장 완료: 554_엠지캐피탈_기타부동산담보.txt
✅ 저장 완료: 555_오릭스캐피탈코리아_대형상용건설장비부가세유예담보대출.txt
✅ 저장 완료: 556_오릭스캐피탈코리아_중도금대출.txt
✅ 저장 완료: 557_오릭스캐피탈코리아_테슬라오토론.txt
✅ 저장 완료: 558_오케이캐피탈_OKAPT론.txt
✅ 저장 완료: 559_오케이캐피탈_OKLADY론.txt
✅ 저장 완료: 560_오케이캐피탈_OKPAY론.txt
✅ 저장 완료: 561_우리금융저축은행_비타WON주택.txt
✅ 저장 완료: 562_우리금융캐피탈_사업자아파트신용대출다이렉트.txt
✅ 저장 완료: 563_우리금융캐피탈_우리금융캐피탈모기지론사업자금_고정_비수도권.txt
✅ 저장 완료: 564_우리은행_단기수요자금융.txt
✅ 저장 완료: 565_우리은행_상생플러스론.txt
✅ 저장 완료: 566_우리은행_세이프e구매자금대출.txt
✅ 저장 완료: 567_우리은행_세이프e구매카드대출.txt
✅ 저장 완료: 568_우리은행_소상공인119Plus당행대환.txt
✅ 저장 완료: 569_우리은행_우리ESG혁신기업대출.txt
✅ 저장 완료: 570_우리은행_우리SGI협약운전자금대출.txt
✅ 저장 완료: 571_우리은행_우리신성장동력대출.txt
✅ 저장 완료: 572_우리은행_우리중진공투게더론.txt
✅ 저장 완료: 573_우리은행_우리프랜차이즈론.txt
✅ 저장 완료: 574_우리은행_우리프리미엄비즈센터론.txt
✅ 저장 완료: 575_우리은행_우리CUBE론IP.txt
✅ 저장 완료: 576_우리은행_우리CUBE론X수출기업.txt
✅ 저장 완료: 577_우리은행_우리WON사장님담보대출.txt
✅ 저장 완료: 578_우리은행_우리드림카대출상용차.txt

## png에서 텍스트 추출

In [7]:
pip install pytesseract pillow

Collecting pytesseract
  Downloading pytesseract-0.3.13-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: pillow in c:\users\소영\appdata\local\programs\python\python312\lib\site-packages (10.1.0)
Requirement already satisfied: packaging>=21.3 in c:\users\소영\appdata\local\programs\python\python312\lib\site-packages (from pytesseract) (23.2)
Downloading pytesseract-0.3.13-py3-none-any.whl (14 kB)
Installing collected packages: pytesseract
Successfully installed pytesseract-0.3.13
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
from PIL import Image
import pytesseract

# (Windows 사용 시 주석 해제 후 Tesseract 경로 지정)
pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'

# 이미지 열기
image_path = "공고문.png"  # 업로드한 이미지 경로
image = Image.open(image_path)

# 텍스트 추출
text = pytesseract.image_to_string(image, lang='kor+eng')  # 한글과 영어 동시 인식

# 결과 출력
print(text)

20258 SSA AAl SSS este w=

es AAW

O MASA: 4S Wl 74 aS 2 ae Se} MEY Soe
AGL Aat Sk AEMAlel Pus oppaal alee Fal
FEBS 7A baal 710}
* BE SESAME SCHARAD 1982('25.5.30,)
O Ws: su Asdas opoe Asaa Fo A e2hlal
- 100% 21 FRE] Ola AQ] Og ask HShipollAy ol7} apo] gl

ac =R2ue

Oana

O AFAAS FU 7ASASS BAe Su V4

O ASLAS +UGeupste] ASS aAzAAbs] Bar Eb alo)
STE HE SS MM SEL ASHE UAE Aly]

O ASS: 254 SSA ASS FB AAG SQ Hay)

LC) AMAA: 84 150098 tHe, Wesel, 14 clu] YA) Ast
+ CHEALO| SS7AKSe TALCH)O| DASH Bao] 1% ALS BeUEWIE 2.99%) HS
+ YD 32 HS ABAM BRLANS YA] Se HO SAA
» S712: NHSwSse

O WSs

O Bar AS 3azi atts AHS) Seat 9H 1~12.3L “See FOB 7}4))-2-
WA) He WI Bh 414, aE RE oy 21d
+ 32 342! AAO] SE AS, ADAG Be sQH WBOe HE AS
~ SBS AIHA GlA| SSDI, ASAE Soll We} HERTZ 2

C) AKSSEE: aid AHO] Ait el SS 7 al SPO URES: ORE ah

« a2 ABAM FAS At HSS ABST SE CHO] PISS, TIS BAAS WS

Ae B55 S7}
OF SIMCHA A9H)7I/Z#: ° 25. 1. 1. (42) ~7 25. 12. 31. >)
O tS At

E

Ed

ALUAL 4 As SM

Ciel Be AS)
Abe CA Sues aa eae

ae, AAW

A494 AEA
NHS BLY

(NS 2: r
LC) AAIIZE: oat 2A)
LD NAS: al 21G¢ 4} Sto] ©] me) 44 (hk0316@kfia.or.kr)
O AISA
O ASaAA PAS BA4AI4AA U2 AA 1s Hay)
+ SAAN FOIA AY Solapereel-1 ata)
O FFA4ZRI 14 US FS)
O 8aaae
O Az 3M ABA Fda SWF U aS)
+ YS] QHA USA SAANBS S72 a7ts le
O S€27)9 FIA sta a)
O Shr AAS ASA LEGEUM2 AA] 4e 4a)
O MARE 449 SAEU3 BaD)
% HEME te AS, of Se AS FE Bel OA TSE cha Ist
CO AAA ABAD SH: A AE FA SE VSdga
L) 4M 2a
O AAAT SR PHYE 10M Ol] AA 2= Aso AS
+ HAY, ABUS(SH712t OJIM)’ OF Adsto| SHauigle 314
+ HASH LO CHEBM SHA, HS SISHAI7] AS BS Bol WS
+ St Uy OAS Al ASIAR MA ala
0
L) A4Sa= AeZiI2 24 BEE Aalok sy, HY Al WSs
Ad a4, SUL S MASSE] 48, le AA S Bh
LC) ASNFS ANE ASAAG AVGzAA Wee) SE WAl7t
WSs YYOse Age BP ze dese) ales a ZAR
Aa t+ VS
L) 835) 44S Bho Bee] 37421 U] de Age 34] oh SHE AP
A 4a BBB SE 4), VES: SA RRRRPOW 4 aa
SS wad lel eS AZ Fe
* E)| Fo] HSAAE AE ALA MAoll Hsstol ZeW S ZAI
LC) el ARS ARS | SUS + QE *AGE WAS Aleellok ope]
Bs] 2A] VS Al, ze ASA Bele Met ARS AS
+ AZAN AQAA SUR, desea s
L) Sasa ze) 27), des alae] dey we] Soe olay Fa
BAS qew| Rt At, AAA SHzh FAs whl yal
2912 414) 3S AS ABAWN ASM AS
O ee 24 Qo] we me 71S Se Mae = US
LC) $2719, S7etsa SF BS BA BAM Bal Pa

hv | =a

L) Areialgated : A744 aS] AAMAS Area

Al AALS
(Cf 2-475 22)

NHS Yay AVS Ott

wat Asal ©} wil 2)
Fa a 02-3470-8126 jylee22@kfia.or.kr
Bata Are 02-3470-8157 hk0316@kfia.or.kr

O desea : NH S824

wea ae] o} wie)
sa] ata 02-2080-7586 lubseung@nonghyup.com
<z >

1. 20254 ASA TASS) AGes

2. POA ABA] -S Bel AA}

2-1. BAVA OHA 43 ARS

3. MAU 4d FA

4. 20254 14} ASAAMUZ BBs Aral aarea algal

In [39]:
import cv2
import numpy as np
from PIL import Image
import pytesseract

# ✅ Tesseract 경로 설정
pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'

# ✅ 이미지 경로
image_path = 'image.png'

# ✅ 이미지 불러오기 및 전처리
img = cv2.imread(image_path)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
_, thresh = cv2.threshold(gray, 150, 255, cv2.THRESH_BINARY)

# 예시: 일정 크기 이하의 정사각형 검정 기호 제거 (단순한 예)
contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
for cnt in contours:
    x, y, w, h = cv2.boundingRect(cnt)
    if w < 15 and h < 15:  # 네모 크기 기준
        cv2.rectangle(thresh, (x, y), (x+w, y+h), 255, -1)  # 흰색으로 덮기


# 이미지 확대
# scale_percent = 150  # 150% 확대
# width = int(thresh.shape[1] * scale_percent / 100)
# height = int(thresh.shape[0] * scale_percent / 100)
# resized = cv2.resize(thresh, (width, height), interpolation=cv2.INTER_CUBIC)

# ✅ OCR 수행
custom_config = r'--psm 6'  # 한 줄씩 읽는 구조

text = pytesseract.image_to_string(thresh, lang='kor', config=custom_config)


# ✅ 출력
print(text)

2025 년 식 품 소 재 업 계 경 영 안 정 자 금 지 원 안 내 문
매 사 이 개 요
니 사 업 목 적 : 식 품 원 자 재 가 격 상 승 및 환 율 글 리 ㆍ 유 가 변 동 성 등 으 로
경 영 난 을 겪 고 있 는 식 품 업 계 에 구 매 자 금 이 자 보 전 지 원 을 통 해
가 옹 식 품 가 격 안 정 에 기 어
* 관 련 : 농 림 축 산 식 품 부 푸 드 테 크 정 책 과 -1989(25.5.30.)

디 지 원 내 용 : 국 내 식 품 업 체 를 대 상 으 로 식 품 소 재 구 매 자 금 융 자 지 원
- 1500 익 원 규 모 의 이 차 보 전 사 엄 으 로 예 산 멈 위 내 에 서 이 자 자 액 지 원
때 주 489

니 지 원 대상
2 식 줌 소 재 률 수 입 하 여 가 공 식 품 을 생 산 하 는 국 내 업 체
ㅇ 식 품 소 재 를 수 입 ( 구 배 하 여 식 품 을 재 조 . 생 산 하 지 않 고 다 업 체 에 게
공 급 하 는 유 통 능 을 위 한 용 도 로 사 용 하 는 입 체 는 제 외
니 지 원 픔 목 : '25 년 한 당 관 세 지 원 품 목 및 유 지 류 등 ( 불 임1 참 고 )
디 치 원 조 건 : 융 자 1.500 억 원 규 모 , 변 동 금 리 , 1 년 이 내 일 시 상 환
* 다 출 시 점 에 금 융 기 괜 농 협 가 계 담 보 대 출 ! 이 고 사 하 는 금 라 에 1% 틀 차 슴 한 금 리 (6 돌 기 준 3.33%; 적 룡
* 최 근 3 년 간 해 당 식 품 소 재 평 균 수 입 액 을 넘 지 않 는 범 위 에 서 융 자 지 원
+ 대 출 기 관 : 4+{ 농 협 은 행
니 지 원 한 도
ㅇ 임 체 명 과근 3 간 해 당 식 품 4 빼 평 균 수 임 액 11~1231. 동 관 기 준 808 가 격 ) 을
넘 지 않 는 법 위 에 서 융 자 신 청 , 예 산 한 도 내 에 서 지 원
* 최 근 3 년 간 실 적 이 없 는 겸 후 , 최 근 연 도 평 균 수 입 액 기 준 므 로 한 도 산 출
＊ 융 자 금 온 사 업 대상 업 체 담 보 가 치. 신 용 상 태 등에 따 라 대 출 취 급 기 관 어 너 결 정
니 사 용 용 도 : 해 낭 삭 \4 패 의 산 규 7 매 보는 기 존 ㅜ 매 외 상 금 액 상 환 을 위 한 자 금
＊ 최 근 식 품 소 재 구 입 을 뭐 한 대 출 지 금 상 환 흥 도 로는 대 출 이 가 능 하 나 . 기 존 검 책 자 금 대 출
상 환 용 도 는 불 가
니 융 자 [ 대 출 실 행 ] 기 간 : `25. 1. 1. ( 수 ) ~`25. 12. 31. ()
니 자 금 지 원 절 차
=
니
{
《
[[ 때 자 금 지 원 신 청
니 신 청 기 간 : 예 산 소 진 시 까 지
[] 신 청 방 법 : 제 출 서유 작 성 하 여 이 메 일 접 수 00(0316@1[8.0..)
디 제 즐 서 류
ㅇ 식 줌 소 재 구 매 자 금 융 자 신 청 서 ( 붙 임 2 서 식 1 호 참 고 )
＊ 율 자 신 청 서 구 매 실 적 작 성 유 희 사 항 ( 붙 임 2-1 참 고 )
으 품 목 제 조 보 고 서 1 부 ( 대 표 줌 목 )
ㅇ 영 업 신 고 증 1 부
으 최 근 3 개 년 식 품 소 재 수 입 실 직 증 병 서 류 ( 수 입 신 고 필 증 *)
* 협 회 요 정 시 민 보 이 스 등 선 적 서 류 를 주 가 로 요 구 할 수 있 음
ㅇ 중 소 기 업 확 인 서 ( 해 당 업 체 )
으 율 자 급 사 용 계 획 서 1 부 ( 붙 입 2 서 식 4호 참 고 )
ㅇ 업 체 정 보 작 성 양 식 ( 불 임3 잠 고 )
※ 해 당 자 료 없 을 겸 우 , 이에 준 하 는 자 료 또 는 협 회 요 청 자 료 로 대 체 가 능함
[ 사 업 자 선 정 결 과 통 보 : 서 류 검 토 후 개 별 공 문 발 송 예 정
니 주 천 서 발 급
ㅇ 선 정 견 과 통보 날 로 부 터 10 일 이 내 서 식 2호 자 성 하 여 제 출
* ' 대 상 자 ', ' 전 경 내 용 ( 유 효 기 간 미 기 재 )' 만 작 성 하 여 한 금 파 일 로 회 신
* 배 정 금 맥 내 에 서 대 출 금 액 분 할 배 정 , 대 출 희 망 시기 조 청 등 별 도 협 의 가 능
* 기 한 내 미 제 출 시 사 업 자 선 정 취 소
[ 내 유 의 시 항
[ ] 신 청 업 체 는 자 글 지 원 은 신 청 용 도 대 로 사 용 해 야 하 며 . 위 반 시 대 출 금
진 액 회 수 . 농 협 은 행 등 연 체 대 줄 금 리 적 용 , 기타 제 재 등 무 과
디 제 출 서 뮤 를 허 위 로 제 출 하 거 나 신 청 자 격 에 부 합 하 지 않 는 업 체 가
무 당 한 망 법 으 로 신 청 한 경 우 지 원 대 상 에 서 제 외 하 거 나 배 정 된 자 금 을
귀소 함 수 있 음
[] 혐 희 추 천 서 를 받 은 날 로 부 터 3 개 월 내 대 출 신 행 을 하 지 아 니 하 는 경 우
선 정 취 소 및 반 납 능 조 치 , 만 남 액 은 농 림 축 산 식 품 부 에 서 취 함 후 재 배 정
난 대 출 신 정 배 정 금 액 내 에 서 분 할 신 정 가 능
＊ 포기 및 미 대 출 업 체 는 차 년 도 사 업 자 선 정 에 반 영 하 여 감 액 등 조 치
니 ] 구 매 자 금 사 용 후 중 병 할 수 있 는 * 서 류 를 분 기 변 로 제 출 헤 야 하 며
협 회 요 청이 있 을 경 우 , 자 금 사 용 실 태 확 인 을 위 한 자 료 를 제 출
＊ 칙 품 소 재 수 립 실 직 증 방 서 류 . 원 료 수 물 대 장 통
늬 추 천 금 액 자 진 포 기 , 대 출 취 급 기 관 의 대 출 신 청 만 려 능 으 로 인 해 추 천
금 액 을 데 출 받 지 못 한 경 우 , 식 품 소 재 구 매 자 금 추 천 금 액 반 납 신 청 서
( 발 인2 시 식 399 를 한 국 식 품 산 업 협 회 에 제 줄
디 향 후 정 무 정 젝 에 따 라 배 분 기 준 능 은 변 경 될 수 있 읍
니 중 소 기 입 , 물 가 한 정 능 정 무 정 잭 에 혐 조 한 업 체 우 대
매 둔 의 저
니 사 업 신 청 관 련 : 한 국 식 품 산 업 협 회 산 업 진 흥 본 무 산 업 기 획 팀
딘 당 자 연 락 저 이 메 인
이 가 세 제다
디 대 출 관 런 : 8 농 협 은 행
단 당 사 연 락 저 이 메 일
<묻 암>
1. 2025 년 식 품 소 재 업 계 구 매 자 금 ( 융 자 ) 지 원 품 목
2. 구 매 자 금 신 청 서 등 판 련 서 식
2-1 융 자 신 청 서 구 매 실 적 작 성 유 의 사 항
3. 업 체 정 보 작 성 양 식
4. 2025 년 1차 식 품 소 재 업 게 경 영 안 정 자 금 지 원 사 업 시 행 지침

In [21]:
with open('image.output.txt', 'w', encoding='utf-8') as f:
    f.write(text)

In [32]:
import cv2
import pytesseract
from PIL import Image
import numpy as np

# 경로 설정
pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'
image_path = "image.png"  

# 이미지 불러오기
img = cv2.imread(image_path)

# 전처리: 흑백 변환 + adaptive thresholding
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
gray = cv2.GaussianBlur(gray, (3, 3), 0)
thresh = cv2.adaptiveThreshold(
    gray, 255, 
    cv2.ADAPTIVE_THRESH_GAUSSIAN_C, 
    cv2.THRESH_BINARY, 11, 2
)

# 이미지 확대
scale_percent = 150  # 150% 확대
width = int(thresh.shape[1] * scale_percent / 100)
height = int(thresh.shape[0] * scale_percent / 100)
resized = cv2.resize(thresh, (width, height), interpolation=cv2.INTER_CUBIC)

# OCR 수행
custom_config = r'--oem 3 --psm 4'  # 문단 인식 중심
text = pytesseract.image_to_string(resized, lang='kor', config=custom_config)

print(text)

.2025 년 : 식 품 소 재 : 업 계 경 영 안 정 : 자 금 지 원 안 내 문.

| : |^자업개요
[ 사 업 복 적 : 식풍 원 자 체 가 격 : 상 승 및 환 율 큼 리 ㆍ 유 가 " 변 동 성 등 으 로
경 영 난 을 겪 고 . 있 는 식 품 업 계 에 구 매 자 금 : 이 차 보 전 지 원 을 통 해
가 공 식 품 가 격 안 정 에 기 여
ㅜ : 관 련 : 농 림 축 산 식 품 부 푸 드 테 크 정 책 과 -1982('25.5.80.)
[] 지 원 내 용 : 국 니 식 품 업 체 를 데 상 으 로 식 품 소제 구 매 자 금 융 자 지 원
- 1500 억 원 큐 모 의 이 차 보 전 : 사 엄 으 로 에 산 - 위 내 에 서 이 자 차 액 지 원

니 지 원 대상
으 식 품 소 제 를 . 수 입 하 여 . 가 공 식 품 을 ' 생 산 하 는 곡 내 업 체 .
ㅇ 식 품 소 재 를 수 입 (? 매 하 여 .: 식 품 율 제 조 - 생 산 하 지 ' 않 고 타 . 업 체 에 게
공 급 하 는 유 동 등 을 위 한 용 토 로 . 사 용 하 는 업 체 는 제 외
니 지 원 품 목 ::'25 년 할 당 관 세 지 원 품 목 및 : 유 지 류 ' 등 ( 붙 임 1、 참 고 )
디 지 원 조 건 : 융 자 1,500 억 원 규 모 , : 변 동 금 리 , 1 년 ' 이 내 일 시 상 환
* 대 충 시 점 에 금 융 기 관 농 협 기 게 덤 보 대 출 )이 고 시 하 는 금 리 에 1% 틀 치 감 한 금 리 (6 월 기 준 3339 적 용
: 최 근 .3 년 간 : 해 당 - 식 품 소 재 : 평 균 수 입 액 을 . 넘 지 : 않 는 - 법 위 에 서 용 자 지 원
…: 대 출 기 관 : 배 능 협 은 행
디 지 원 한 도 '
< ㅇ > 、 업 체 빌 최 근 3 년 간 해 당 식 품 소 재 : 평 균 수 입 액 1.1~1231. 동 관 기 준 .608- 가 격 ) 율
넘 지 않 는 범위에서 ~ 응 자 신 청 ,, 예 산 한 도 . 내 에 서 지 원
*: 최 근 '3 년 간 ' 실 적 이 없 는 경 우 , : 최 근 . 인 도 . 평 균 ' 수 입 액 기 준 으 로 ' 한 도 - 신 출 '
* 융 자 금 은 시 업 대상 업 체 담 보 가 치 , - 신 용 상 태 둥 에 띠 라 대 충 취 급 기 관 에 서 . 경 정 .
니 사 용 용 도 : 해 당 식 품 4 재 의 신 규 구 매 또 는 기 존 구 애 외 상 금 액 싱 환 은 위 한 지 금
* : 최 근 식 품 새 구 입 을 . 위 한 . 대 출 지 금 상 환 용 도 로는 대 춤이 가 능 하 냐 ,: 기 존 정 책 지 금 대 출
. 싱 환 용 도 는 불 가 -
디 융 자 [ 대 측 - 실 행 ] 기 간 : '.25. 1. 1. ( 수 ) ~"25.: 12..81. ( 수 )
니 자곧지윙절차
선창 자 류 여 응 | 으 ] 거로 아인 | 으 | 아다 구투 겐흠
. 사 엄 대 상 자 , ㅇ 쿡얕합델벵헬끓몇엄 횡,를1 한 국 식 품 산 업 힙 회

지 셰 베 | , | 어 순 부 톱

걀홉헬켈흐핼 04 농 협 은 행 . 사 업 대 상 자
자 금 지 원 신 청 : ~

디 신 청 기 간 } 에 산 소 진 시 까 지
디 신 청 방 법 :: 체 출 서 류 작 성 하 여 이 메 일 집 수 0(0316@&08.0 ㄷ 07
니 제 즐 서 류
ㅇ . 식 품 소 재 구 매 자 금 융2}신청서 (뿅。임2 서식 1 호 . 참 고 )'
*:' 융 자 신 청 서 - 구 매 실 적 작 성 유 의 사 항 ( 붙 임 2-1` 참 고 )
ㅇ 품 목 제 조 보 고 서 .1 부 ( 대 표 품 목 ).
ㅇ 영 업 신 고 중 1 부
ㅇ 최 근 3 개 년 식 품 소 재 수 입 실 적 ' 증 빙 서 류 ( 수 입 신 고 필 증
…: 협 회 요 청 시 ' 인 보 이 스 : 등 선 적 서 류 들 . 추 가 로 : 요 구 할 - 수 “ 있 음 .
ㅇ 중 소 기 업 확 인 서 ( 해 당 업 체 )
ㅇ 융 자 큼 . 사 용 계 획 서 :1 부 ( 불 일 2 서 식 4 호 . 참 고 )
ㅇ 업채정보 작 성 양 식 ( 불 임3 참 고 )
※ : 해 당 지 료 : 없 을 경 우 , 이에 준 하 는 지 료 또 는 협 회 요 청 . 자 료 로 , 대 체 : 가 능함
디 사 업 자 선 정 렬 파 통 보 : 서 류 검 토 후 개 별 . 공 문 발 송 예 정
니 추 천 서 발 급 :
ㅇ 전 정 결 과 동 보 : 날 로 부 터 30 일 : 이 내 : 서 식 2호 작 성 하 여 제 출 .
.*: ' 대 상 자 :, - 선 정 내 용 ( 유 효 기 간 . 미 기 재 )': 만 - 작 성 하 여 한 글 파 일 로 . 회 신 .

* 배 정 금 액 내 에 서 대 춤 금 액 : 분 할 배 정 , 대 출 희 망 시기 조 정 등 별 도 . 협 의 가 능
*- 기 한 내 미 제 출 시 사 업 자 : 선 정 ; 취 소

[00| 유 의 사 항

[」 신 줬 업 체 는 자 금 지 원 은 - 신 청 용 도 대 로 사 용 헤 야 하 며 , 위 반 시 대 출 금
전 액 회 수 , 농 협 은 행 등 ' 연 체 대 출 큼 리 적 용 , 기 타 : 제 재 . 등 . 부 과

니 제 출 서 류 를 허 위 로 . 제 출 하 거 나 . 신 청 자 격 에 부 합 하 지 않 는 업 체 가
무 당 한 방 법 으 로 신 청 한 - 굉 우 지 원 대 상 에 서 제 외 하 거 나 베 정 된 지 큼 을
취 소 할 수 있 음

니 힘 희 추 천 서 를 - 받 은 날 로 부티 3 캐 원 。 내 대 출 - 설 행 을 하 지 아 니 하 는 경 우
선 정 취 소 및 반 남 등 . 조 치 , : 반 님 액 은 농 림 축 산 식 품 부 에 서 취 합 후 . 재 배 정
' 냄 . 대 출 신 청 : 배 정 금 액 내 에 서 분 할 신 청 가 능
> : 포 기 : 및 미 . 대 출 업 체 는 - 차 년 도 사 업 자 선 경 에 빈 영 하 여 감 액 : 등 : 조 치.

니 구 매 자 큼 사 용 . 후 중 병 할 : 수 있 는 * 서 류 를 ` 분 기 별 로 제 줄 헤 야 하 며
협 회 요 청이 ' 있 을 경 우 , 자 금 사 용 실 태 . 확 인 을 위 한 자 료 를 제 줄
=" 식 품 소 재 ; 수 입 실 적 증 빙 서 류 , 원 료 수 불 대 장 : 등 :

니 추 천 금 액 ' 자 진 - 포 기 ,: 대 출 취 급 기 관 의 - 대 출 신 청 . 반 려 등 으 로 인 해 추 천
금 왜 율 대 출 받 지 ' 못 한 경 우 , 식 품 소 재 ' 구 매 자 금 `: 추 천 금 액 반 남 신 청 서
맘 임 8 지 식 :358) 를 한 국 식 품 산 업 협 회 에 제 출 :

니 향 후 - 징 부 정 책 에 : 따 라 배 분 기 준 .- 등 은 변 경 될 - 수 : 있 음

디 중 소 기 업 , 물 가 안 정 등 - 정 부 정 책 에 ' 혐 조 한 업 체 - 우 대

|\'| 문 의 저

디 사 업 신 칭 관 린 .:- 힌 국 식 품 산 업 협 회 ' 산 업 진 흥 본 부 산 업 기 획 팀

. 맘 당 자 . 원 막 치. 이 메 인 |
이 주 연 과장 11660802.0.1
경 타 김 사 왼 ｜ . 00867098187 . ｜ . 1081001 고 001

디 대 출 관 련 』.8. 농 협 은 행

` 답 당 자 : 이 메 인

이 승 회 차 장 ' 02=2080=7586 ㆍ 14056008@00081940.001

< 붐 임 >'
1. 28025 년 식 품 소 재 업 게 구 매 자 금 ( 융 자 ) 지 원 품 목

%: 구 매 자 금 ` 신 청 서 등 . 관 련 . 서 식 _ .

2-Ｌ 융 자 신 청 서 구 매 실 적 작 성 : 유 의 자 항

3. 업 체 정 보 작 성 양 식

: 2025 년 . 1차 직 품 소 재 업 계 . 경 영 안 정 . 자 금 지 원 사 업 . 시 행 지 침 :